import {defaultLayout,layoutIssues,type Layout} from '../modules/layout.ts';
import type {SceneEditor} from './scene-editor.ts';
import {layoutMap} from './layout-map.ts';
import {escape,modal,download,errorIn} from './ui.ts';
export function openLayout(editor:SceneEditor){
 const dialog=modal('Планировка 2.5D','<div class="layout-editor"></div><footer><button data-export>Экспорт планировки</button><button data-import>Импорт планировки</button><input type="file" data-file accept=".json" hidden><button data-add-room>＋ Комната</button><button data-add-door>＋ Дверь</button><button data-add-stair>＋ Лестница</button><button data-add-opening>＋ Окно</button><button data-undo>Отменить</button></footer>');
 if(!editor.document.moduleData?.layout)editor.mutate(d=>{d.moduleData||={};d.moduleData.layout=defaultLayout();});
 const layout=()=>editor.document.moduleData!.layout as Layout;
 const commit=(fn:(l:Layout)=>void)=>{editor.mutate(d=>fn(d.moduleData!.layout as Layout));render();};
 const number=(label:string,key:string,value:number,min=-100,max=100)=>`<label>${label}<input type="number" data-field="${key}" value="${value}" step=".1" min="${min}" max="${max}" aria-label="${label}"></label>`;
 function render(){const l=layout(),issues=layoutIssues(l),errorIds=new Set(issues.map(i=>i.id));
  dialog.querySelector('.layout-editor')!.innerHTML=`<p>Комнаты определяют стены, полы и границы движения. Двери соединяют комнаты на одном этаже, лестницы — соседние этажи. Красным отмечены ошибки.</p><div class="layout-map-host"></div><p class="ed-note">На схеме: перетаскивайте комнату или её правую границу. Числовые поля задают точные размеры.</p><div class="layout-global">${number('Высота этажа, м','floorHeight',l.floorHeight,2.3,8)}${number('Появление X, м','spawn.x',l.spawn.x)}${number('Этаж появления','spawn.floor',l.spawn.floor,-10,20)}</div>${(['rooms','doors','stairs','openings'] as const).map(type=>`<h3>${{rooms:'Комнаты',doors:'Двери',stairs:'Лестницы',openings:'Окна и проломы'}[type]}</h3>${l[type].map((item:any)=>`<fieldset class="${errorIds.has(item.id)?'invalid':''}" data-type="${type}" data-id="${escape(item.id)}"><legend><input aria-label="Название элемента" data-field="name" value="${escape(item.name)}"><button data-remove="${escape(item.id)}">Удалить</button></legend><div class="layout-fields">${type==='rooms'?number('Левая граница, м','x',item.x)+number('Ширина комнаты, м','width',item.width,1,100)+number('Этаж комнаты','floor',item.floor,-10,20)+number('Глубина комнаты, м','depth',item.depth,1,30):type==='doors'?number('Положение двери, м','x',item.x)+number('Этаж двери','floor',item.floor,-10,20)+`<label><input type="checkbox" data-field="open" ${item.open?'checked':''}>Открыта при запуске</label>`:type==='stairs'?`<label>Тип подъёма<select data-field="kind"><option value="stairs" ${item.kind!=='ladder'?'selected':''}>Марш</option><option value="ladder" ${item.kind==='ladder'?'selected':''}>Приставная лестница</option></select></label>`+number('Начало лестницы, м','a',item.a)+number('Конец лестницы, м','b',item.b)+number('Нижний этаж','from',item.from,-10,20)+number('Верхний этаж','to',item.to,-10,20):`<label>Тип проёма<select data-field="kind"><option value="window" ${item.kind==='window'?'selected':''}>Окно</option><option value="breach" ${item.kind==='breach'?'selected':''}>Пролом</option></select></label><label>Плоскость<select data-field="plane"><option value="back" ${item.plane!=='divider'?'selected':''}>Задняя стена — обзор и свет</option><option value="divider" ${item.plane==='divider'?'selected':''}>Перегородка — проход</option></select></label><label>Комната<select data-field="room">${l.rooms.map(r=>`<option value="${r.id}" ${r.id===item.room?'selected':''}>${escape(r.name)}</option>`).join('')}</select></label>`+number('Центр проёма, м','x',item.x)+number('Низ проёма, м','bottom',item.bottom)+number('Ширина проёма, м','width',item.width,.1,10)+number('Высота проёма, м','height',item.height,.1,8)}</div></fieldset>`).join('')}`).join('')}<div class="layout-issues" role="status">${issues.length?issues.map(i=>`<p>● ${escape(i.message)}</p>`).join(''):'✓ Планировка готова к запуску'}</div>`;
  layoutMap(dialog.querySelector('.layout-map-host')!,l,id=>dialog.querySelector(`[data-id="${id}"]`)?.scrollIntoView({block:'nearest'}),(id,x,width,floor)=>commit(l=>Object.assign(l.rooms.find(r=>r.id===id)!,{x,width,floor})));
  dialog.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-field]').forEach(input=>input.onchange=()=>{const group=input.closest<HTMLElement>('[data-id]'),field=input.dataset.field!,value=input instanceof HTMLInputElement&&input.type==='checkbox'?input.checked:input instanceof HTMLInputElement&&input.type==='number'?Number(input.value):input.value;commit(l=>{if(group){const list=l[group.dataset.type as 'rooms'] as any[];const item=list.find(i=>i.id===group.dataset.id);item[field]=value;}else if(field.startsWith('spawn.'))(l.spawn as any)[field.slice(6)]=value;else (l as any)[field]=value;});});
  dialog.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>commit(l=>{for(const type of ['rooms','doors','stairs','openings'] as const)(l as any)[type]=l[type].filter(i=>i.id!==b.dataset.remove);}));
 }
 dialog.querySelector<HTMLButtonElement>('[data-add-room]')!.onclick=()=>commit(l=>{const last=l.rooms.at(-1);l.rooms.push({id:crypto.randomUUID(),name:'Комната '+(l.rooms.length+1),x:last?last.x+last.width:0,width:4,floor:0,depth:4,color:'#858880'});});
 dialog.querySelector<HTMLButtonElement>('[data-add-door]')!.onclick=()=>commit(l=>l.doors.push({id:crypto.randomUUID(),name:'Дверь '+(l.doors.length+1),x:(l.rooms[0]?.x||0)+(l.rooms[0]?.width||4),floor:0,open:false}));
 dialog.querySelector<HTMLButtonElement>('[data-add-stair]')!.onclick=()=>commit(l=>l.stairs.push({id:crypto.randomUUID(),name:'Лестница '+(l.stairs.length+1),a:0,b:2,from:0,to:1}));
 dialog.querySelector<HTMLButtonElement>('[data-add-opening]')!.onclick=()=>commit(l=>{const r=l.rooms[0];if(r)l.openings.push({id:crypto.randomUUID(),name:'Окно '+(l.openings.length+1),room:r.id,x:r.x+r.width/2,bottom:1,width:1,height:1.2,kind:'window'});});
 dialog.querySelector<HTMLButtonElement>('[data-export]')!.onclick=()=>download(new Blob([JSON.stringify(layout(),null,2)],{type:'application/json'}),'layout.shelter.json');dialog.querySelector<HTMLButtonElement>('[data-import]')!.onclick=()=>dialog.querySelector<HTMLInputElement>('[data-file]')!.click();dialog.querySelector<HTMLInputElement>('[data-file]')!.onchange=async event=>{try{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const value=JSON.parse(await file.text());if(file.size>1000000||layoutIssues(value).some(i=>i.id==='layout'))throw new Error('Неподдерживаемая планировка.');editor.mutate(d=>{d.moduleData||={};d.moduleData.layout=value;});render();}catch(e){errorIn(dialog,e);}};
 dialog.querySelector<HTMLButtonElement>('[data-undo]')!.onclick=()=>{editor.action('undo');if(!editor.document.moduleData?.layout)dialog.close();else render();};render();
}
