import type {AssetRecord,ProjectSession} from '../engine/project.ts';
import {GLTF_EXTENSIONS,inspectGLTF} from '../engine/asset-format.ts';
import {api,modal,escape,errorIn,fileData,download} from './ui.ts';
import {materialDialog} from './materials.ts';
import {previewAsset} from './preview.ts';
export async function openLibrary(session:()=>ProjectSession|undefined,onAdded:(s:ProjectSession,a:AssetRecord)=>Promise<void>,save:()=>Promise<boolean>){
 const dialog=modal('Shelter Library',`<div class="library-toolbar"><input type="search" aria-label="Поиск в библиотеке" placeholder="Название, описание или тег…"><select aria-label="Тип ресурса"><option value="">Все типы</option><option value="model">Модели</option><option value="texture">Текстуры</option><option value="material">Материалы</option></select><select aria-label="Категория библиотеки"><option value="">Все категории</option><option>Строительство</option><option>Мебель и реквизит</option><option>Материалы</option><option>Модели</option><option>Текстуры</option></select><select aria-label="Размер ресурса"><option value="">Любой размер</option><option value="1048576">До 1 МБ</option><option value="10485760">До 10 МБ</option></select><select aria-label="Сложность модели"><option value="">Любая сложность</option><option value="1000">До 1 тыс. треуг.</option><option value="10000">До 10 тыс. треуг.</option></select><select aria-label="Формат ресурса"><option value="">Все форматы</option><option value="glb">GLB</option><option value="gltf">glTF</option><option value="png">PNG</option><option value="json">Материал</option></select><input aria-label="Стиль или коллекция" placeholder="Стиль / коллекция (тег)…"><label><input type="checkbox" data-favorites>Избранное</label><button data-material>Создать материал</button><button data-import>Импорт ресурса</button><button data-package>Импорт пакета</button><button data-export>Экспорт библиотеки</button></div><div class="library-grid"></div>`,false);dialog.classList.add('library-dialog');
 let entries:AssetRecord[]=(await api('library')).entries;const favorites=new Set<string>(JSON.parse(localStorage.getItem('shelter:library:favorites')||'[]')),thumbs=new Map<string,string>();
 const field=(label:string)=>dialog.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!;
 const key=(a:AssetRecord)=>a.id+'@'+a.version,find=(value:string)=>entries.find(a=>key(a)===value)!;
 let generation=0;
 function render(){generation++;const gen=generation,query=field('Поиск в библиотеке').value.toLowerCase(),type=field('Тип ресурса').value,category=field('Категория библиотеки').value,only=dialog.querySelector<HTMLInputElement>('[data-favorites]')!.checked;
  const size=Number(field('Размер ресурса').value)||Infinity,triangles=Number(field('Сложность модели').value)||Infinity,format=field('Формат ресурса').value,tag=field('Стиль или коллекция').value.toLowerCase();const list=entries.filter(a=>a.bytes<=size&&(a.triangles||0)<=triangles&&(!format||a.path.endsWith('.'+format))&&(!tag||a.tags.some(t=>t.toLowerCase().includes(tag)))&&(!type||a.type===type)&&(!category||a.category===category)&&(!only||favorites.has(key(a)))&&`${a.name} ${a.description} ${a.tags.join(' ')}`.toLowerCase().includes(query));const grid=dialog.querySelector('.library-grid')!;grid.innerHTML=list.map(a=>`<article class="library-card" data-id="${key(a)}" draggable="true" title="Перетащите в сцену или добавьте в проект"><button class="asset-picture" data-preview="${key(a)}" aria-label="Посмотреть: ${escape(a.name)}">${thumbs.has(key(a))?`<img src="${thumbs.get(key(a))}" alt="${escape(a.name)}">`:`<canvas width="180" height="126" aria-label="Превью ${escape(a.name)}"></canvas>`}</button><div><strong>${escape(a.name)}</strong><button data-favorite="${key(a)}" aria-label="Избранное: ${escape(a.name)}">${favorites.has(key(a))?'★':'☆'}</button></div><small>${escape(a.category)} · ${a.type==='model'?(a.triangles||0).toLocaleString()+' треуг.':'Текстура'} · ${(a.bytes/1024).toFixed(0)} КБ</small><footer><span>${session()?.manifest.assets.some(x=>x.source?.id===a.id&&x.source.version===a.version)?'В проекте':session()?.manifest.assets.some(x=>x.source?.id===a.id)?'Есть другая версия в проекте':'В библиотеке'} · ${a.version}</span><button data-add="${key(a)}" ${session()?'':'disabled title="Сначала откройте проект"'}>Добавить в проект</button></footer></article>`).join('')||'<p>По запросу ничего не найдено.</p>';
  grid.querySelectorAll<HTMLElement>('.library-card').forEach(card=>{card.ondragstart=event=>{event.dataTransfer!.setData('shelter-library',card.dataset.id!);dialog.style.opacity='.3';};card.ondragend=()=>dialog.style.opacity='1';});
  grid.querySelectorAll<HTMLButtonElement>('[data-favorite]').forEach(b=>b.onclick=()=>{const id=b.dataset.favorite!;favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('shelter:library:favorites',JSON.stringify([...favorites]));render();});
  grid.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{if(!await save())return;const s=await api('library-add',{token:session()!.token,revision:session()!.revision,id:b.dataset.add});await onAdded(s,find(b.dataset.add!));render();}catch(e){errorIn(dialog,e);}finally{b.disabled=false;}});
  grid.querySelectorAll<HTMLButtonElement>('[data-preview]').forEach(b=>b.onclick=()=>detail(find(b.dataset.preview!)));
  void (async()=>{for(const a of list){if(!dialog.isConnected||gen!==generation)return;if(thumbs.has(key(a)))continue;const canvas=grid.querySelector<HTMLCanvasElement>(`[data-id="${key(a)}"] canvas`);if(!canvas)continue;try{const preview=await previewAsset(canvas,a,p=>'/api/library-file/'+p,false);thumbs.set(key(a),preview.image);const img=document.createElement('img');img.src=preview.image;img.alt=a.name;preview.dispose();canvas.replaceWith(img);}catch{canvas.replaceWith(document.createTextNode('Превью недоступно'));}}})();
 }
 async function detail(a:AssetRecord){const d=modal(a.name,`<canvas class="asset-preview" width="640" height="360"></canvas><label>Свет<input type="range" min="0" max="8" value="3" step=".1" data-light></label><p>${escape(a.description)}</p><p>${a.dimensions?.map(v=>v.toFixed(2)).join(' × ')||'256 × 256'} ${a.type==='model'?'м':''} · ${a.triangles||0} треугольников · ${(a.bytes/1024).toFixed(0)} КБ</p><p>${escape(a.author)} · ${escape(a.license)} · версия ${a.version}</p><label>Название<input data-name value="${escape(a.name)}"></label><label>Категория<input data-category value="${escape(a.category)}"></label><label>Теги и коллекции (через запятую)<input data-tags value="${escape(a.tags.join(', '))}"></label><label>Описание<textarea data-description>${escape(a.description)}</textarea></label><label>Автор<input data-author value="${escape(a.author)}"></label><label>Лицензия<input data-license value="${escape(a.license)}"></label><footer><button data-save>Сохранить описание</button><button data-pack>Экспорт пакета</button></footer>`);try{const p=await previewAsset(d.querySelector('canvas')!,a,x=>'/api/library-file/'+x);d.addEventListener('close',()=>p.dispose());d.querySelector<HTMLInputElement>('[data-light]')!.oninput=e=>p.setLight(Number((e.target as HTMLInputElement).value));}catch(e){errorIn(d,e);}
  d.querySelector<HTMLButtonElement>('[data-save]')!.onclick=async()=>{try{entries=(await api('library-meta',{id:key(a),description:d.querySelector<HTMLTextAreaElement>('[data-description]')!.value,author:d.querySelector<HTMLInputElement>('[data-author]')!.value,license:d.querySelector<HTMLInputElement>('[data-license]')!.value,name:d.querySelector<HTMLInputElement>('[data-name]')!.value,category:d.querySelector<HTMLInputElement>('[data-category]')!.value,tags:d.querySelector<HTMLInputElement>('[data-tags]')!.value.split(',').map(s=>s.trim())})).entries;d.close();render();}catch(e){errorIn(d,e);}};
  d.querySelector<HTMLButtonElement>('[data-pack]')!.onclick=()=>exportPackage(key(a));
 }
 async function exportPackage(id?:string){const r=await fetch('/api/library-export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)download(await r.blob(),(id||'Shelter-Library')+'.zip');else errorIn(dialog,await r.text());}
 for(const el of dialog.querySelectorAll('input,select'))el.addEventListener('input',render);
 dialog.querySelector<HTMLButtonElement>('[data-material]')!.onclick=()=>materialDialog(async()=>{entries=(await api('library')).entries;render();});
 dialog.querySelector<HTMLButtonElement>('[data-import]')!.onclick=()=>importResource(undefined,async()=>{entries=(await api('library')).entries;render();});
 dialog.querySelector<HTMLButtonElement>('[data-export]')!.onclick=()=>exportPackage();
 dialog.querySelector<HTMLButtonElement>('[data-package]')!.onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='.zip';input.onchange=async()=>{try{const files=await fileData([...input.files||[]]);entries=(await api('library-import',{archive:files[0]?.data})).entries;render();}catch(e){errorIn(dialog,e);}};input.click();};render();
}
export function importResource(session:ProjectSession|undefined,done:(result:any)=>Promise<void>){
 const dialog=modal(session?'Импорт в проект':'Импорт в Shelter Library',`<p>Статические GLB / glTF 2.0 и PNG / JPEG / WebP. Для glTF выберите модель вместе с .bin и изображениями. Максимум 64 МБ на файл, 128 МБ на комплект.</p><input type="file" multiple aria-label="Файлы ресурса" accept=".glb,.gltf,.bin,.png,.jpg,.jpeg,.webp"><button data-select-folder>Выбрать папку glTF с зависимостями</button><input type="file" webkitdirectory multiple data-folder-input aria-label="Папка glTF" hidden><label>Название<input data-name placeholder="Имя файла"></label><label>Единицы исходной модели<select data-units><option value="1">Метры</option><option value=".01">Сантиметры</option><option value=".001">Миллиметры</option></select></label><p>Поддерживаемые расширения: ${GLTF_EXTENSIONS.join(', ')}.</p><canvas class="asset-preview" width="560" height="280" hidden></canvas><footer><button class="primary" data-import disabled>Импортировать</button><button data-cancel>Отмена</button></footer><progress max="100" value="0" hidden></progress>`);let prepared:Awaited<ReturnType<typeof fileData>>=[],main='',dimensions:number[]|undefined,preview:{dispose:()=>void}|undefined;const urls:string[]=[];let generation=0;
 const cleanup=()=>{generation++;preview?.dispose();for(const u of urls)URL.revokeObjectURL(u);};dialog.addEventListener('close',cleanup);dialog.querySelector<HTMLButtonElement>('[data-cancel]')!.onclick=()=>dialog.close();
 dialog.querySelector<HTMLInputElement>('input[type=file]')!.onchange=async e=>{cleanup();const gen=generation;dialog.querySelector<HTMLButtonElement>('[data-import]')!.disabled=true;const files=[...(e.target as HTMLInputElement).files||[]].map(f=>f.webkitRelativePath?new File([f],f.webkitRelativePath.split('/').slice(1).join('/'),{type:f.type}):f);try{main=files.find(f=>/\.(glb|gltf)$/i.test(f.name))?.name||files[0]?.name;if(!main)return;const file=files.find(f=>f.name===main)!,names=new Set(files.map(f=>f.name));if(file.size>64*1024*1024||files.reduce((n,f)=>n+f.size,0)>128*1024*1024)throw new Error('Превышен бюджет ресурса.');if(/\.(glb|gltf)$/i.test(main)){inspectGLTF(new Uint8Array(await file.arrayBuffer()),main,names);
 const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js'),T=await import('three');const map=new Map(files.map(f=>{const url=URL.createObjectURL(f);urls.push(url);return [f.name,url];})),manager=new T.LoadingManager();manager.setURLModifier(url=>map.get(decodeURIComponent(url))||map.get((main.includes('/')?main.slice(0,main.lastIndexOf('/')+1):'')+decodeURIComponent(url))||url);const gltf=await new GLTFLoader(manager).parseAsync(await file.arrayBuffer(),'');const box=new T.Box3().setFromObject(gltf.scene);dimensions=box.getSize(new T.Vector3()).toArray();if(!dimensions.every(Number.isFinite)||dimensions.every(v=>v===0))throw new Error('Модель не содержит измеримой геометрии.');let oversized=false;gltf.scene.traverse(o=>{if(o instanceof T.Mesh)for(const m of Array.isArray(o.material)?o.material:[o.material])for(const value of Object.values(m))if(value instanceof T.Texture&&(value.image?.width>4096||value.image?.height>4096))oversized=true;});const {disposeTree}=await import('../engine/renderer.ts');disposeTree(gltf.scene);if(oversized)throw new Error('Текстура модели превышает 4096 × 4096.');
 // Convert referenced files to data URIs only for the temporary preview, keeping the original package on disk.
 let previewUrl=map.get(main)!;if(main.endsWith('.gltf')){const json=JSON.parse(await file.text()),encoded=await fileData(files);for(const x of [...json.buffers||[],...json.images||[]])if(x.uri&&!x.uri.startsWith('data:')){const dep=encoded.find(f=>f.name===(main.includes('/')?main.slice(0,main.lastIndexOf('/')+1):'')+decodeURIComponent(x.uri));if(dep)x.uri='data:application/octet-stream;base64,'+dep.data;}previewUrl=URL.createObjectURL(new Blob([JSON.stringify(json)]));urls.push(previewUrl);}
 const canvas=dialog.querySelector('canvas')!;canvas.hidden=false;preview=await previewAsset(canvas,{type:'model',path:main} as AssetRecord,()=>previewUrl);
 }else{const bitmap=await createImageBitmap(file);if(bitmap.width>4096||bitmap.height>4096){bitmap.close();throw new Error('Текстура больше 4096 × 4096.');}bitmap.close();}
 prepared=await fileData(files);if(gen!==generation||!dialog.isConnected)return;dialog.querySelector<HTMLButtonElement>('[data-import]')!.disabled=false;dialog.querySelector('.dialog-error')!.textContent=dimensions?'Размеры: '+dimensions.map(v=>v.toFixed(3)).join(' × ')+' исходных единиц':'';
 }catch(error){errorIn(dialog,error);}};
 dialog.querySelector<HTMLButtonElement>('[data-select-folder]')!.onclick=()=>dialog.querySelector<HTMLInputElement>('[data-folder-input]')!.click();dialog.querySelector<HTMLInputElement>('[data-folder-input]')!.onchange=dialog.querySelector<HTMLInputElement>('input[type=file]')!.onchange;
 dialog.querySelector<HTMLButtonElement>('[data-import]')!.onclick=async()=>{const button=dialog.querySelector<HTMLButtonElement>('[data-import]')!,progress=dialog.querySelector('progress')!;button.disabled=true;progress.hidden=false;progress.removeAttribute('value');try{const result=await api('import',{token:session?.token,revision:session?.revision,library:!session,files:prepared,main,dimensions,name:dialog.querySelector<HTMLInputElement>('[data-name]')!.value||main,unitScale:Number(dialog.querySelector<HTMLSelectElement>('[data-units]')!.value)});await done(result);dialog.close();}catch(e){errorIn(dialog,e);button.disabled=false;progress.hidden=true;}};
}
