import * as T from 'three';
import type {SceneEditor} from './scene-editor.ts';
import {modal} from './ui.ts';

/** Workspace-only camera controls; never write to the authored scene. */
export function navigation(editor:SceneEditor) {
 const canvas=editor.canvas,signal=editor.abort.signal,keys=new Set<string>();
 let orbiting=false;let held=false,moved=false,startX=0,startY=0,previous=performance.now(),frame=0;
 const finish=()=>{if(editor.navigating){const camera=editor.renderer.camera;editor.orbit.target.copy(camera.position).add(camera.getWorldDirection(new T.Vector3()).multiplyScalar(5));editor.orbit.enabled=true;}editor.navigating=false;held=false;keys.clear();};
 canvas.addEventListener('pointerdown',event=>{if(event.button===0&&event.altKey&&!editor.gamePreview&&!editor.suspended){orbiting=true;editor.orbit.mouseButtons.LEFT=T.MOUSE.ROTATE;editor.transform.enabled=false;}if(event.button!==2||editor.suspended||editor.gamePreview)return;held=true;moved=false;startX=event.clientX;startY=event.clientY;if(editor.renderer.camera instanceof T.PerspectiveCamera){editor.navigating=true;editor.orbit.enabled=false;canvas.setPointerCapture(event.pointerId);}}, {signal,capture:true});
 canvas.addEventListener('pointermove',event=>{if(!held)return;moved ||= Math.hypot(event.clientX-startX,event.clientY-startY)>5;if(!editor.navigating||!moved)return;const camera=editor.renderer.camera,angles=new T.Euler().setFromQuaternion(camera.quaternion,'YXZ');angles.y-=event.movementX*.003;angles.x=T.MathUtils.clamp(angles.x-event.movementY*.003,-1.5,1.5);camera.quaternion.setFromEuler(angles);}, {signal});
 canvas.addEventListener('pointerup',event=>{if(orbiting){orbiting=false;delete editor.orbit.mouseButtons.LEFT;editor.transform.enabled=true;}if(event.button!==2||!held)return;const open=!moved;finish();if(open){const dialog=modal('Действия со сценой','<div class="menu-commands"></div>');for(const [title,action] of [['Фокус на выделении','focus'],['Копировать выделение','duplicate'],['На поверхность','surface'],['Скрыть в редакторе','hide-editor'],['Удалить выделение','delete']]){const button=document.createElement('button');button.textContent=title;button.disabled=!editor.selectedNodes.length;button.onclick=()=>{dialog.close();action==='surface'?surfaceSnap(editor):editor.action(action);};dialog.querySelector('.menu-commands')!.append(button);}}},{signal});
 window.addEventListener('keydown',event=>{if(editor.navigating&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(event.code)){event.preventDefault();event.stopImmediatePropagation();keys.add(event.code);moved=true;}}, {signal,capture:true});
 window.addEventListener('keyup',event=>keys.delete(event.code),{signal});window.addEventListener('blur',finish,{signal});
 const tick=(now:number)=>{const dt=Math.min(.05,(now-previous)/1000);previous=now;if(editor.navigating){const camera=editor.renderer.camera,speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?12:4)*dt,forward=camera.getWorldDirection(new T.Vector3()),right=new T.Vector3(1,0,0).applyQuaternion(camera.quaternion);camera.position.addScaledVector(forward,(Number(keys.has('KeyW'))-Number(keys.has('KeyS')))*speed).addScaledVector(right,(Number(keys.has('KeyD'))-Number(keys.has('KeyA')))*speed);camera.position.y+=(Number(keys.has('KeyE'))-Number(keys.has('KeyQ')))*speed;camera.updateMatrixWorld();}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);signal.addEventListener('abort',()=>cancelAnimationFrame(frame));
}

export function surfaceSnap(editor:SceneEditor){
 if(!editor.selectedNodes.length)return;
 const dialog=modal('Привязать к поверхности','<label>Отступ, м<input aria-label="Отступ от поверхности" type="number" step=".01" value="0"></label><label><input data-align type="checkbox">Выровнять по нормали поверхности</label><footer><button class="primary" data-apply>Применить</button></footer>');
 dialog.querySelector<HTMLButtonElement>('[data-apply]')!.onclick=()=>{const offset=Number(dialog.querySelector('input')!.value),align=dialog.querySelector<HTMLInputElement>('[data-align]')!.checked,roots=editor.selectedNodes.map(n=>editor.runtime.instances.get(n.id)!.root);if(editor.selectedNodes.some(n=>n.locked)){editor.status('Разблокируйте всё выделение.',true);dialog.close();return;}
 const box=new T.Box3();for(const root of roots)box.union(new T.Box3().setFromObject(root));const center=box.getCenter(new T.Vector3()),ray=new T.Raycaster(new T.Vector3(center.x,box.max.y+.1,center.z),new T.Vector3(0,-1,0),0,2000);
 editor.renderer.scene.updateMatrixWorld(true);const hit=ray.intersectObject(editor.renderer.scene,true).find(hit=>{let o:T.Object3D|null=hit.object;while(o){if(!o.visible||o.userData.editorOnly||roots.some(root=>root===o)||o===editor.grid)return false;o=o.parent;}return !!hit.face;});
 if(!hit){editor.status('Под выделением нет поверхности.',true);dialog.close();return;}const delta=hit.point.y-box.min.y+offset;editor.mutate(doc=>{for(const node of doc.nodes.filter(n=>editor.selectedIds.has(n.id))){node.transform.position[1]+=delta;if(align&&hit.face){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld),q=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),normal),e=new T.Euler().setFromQuaternion(q);node.transform.rotation=[e.x,e.y,e.z].map(T.MathUtils.radToDeg) as [number,number,number];}}});dialog.close();};
}
