import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {disposeTree,createRenderer} from '../engine/renderer.ts';
import type {AssetRecord} from '../engine/project.ts';
export async function previewAsset(canvas:HTMLCanvasElement,asset:AssetRecord,url:(p:string)=>string,interactive=true){
 const gl=createRenderer(canvas);gl.setPixelRatio(1);const scene=new T.Scene();scene.background=new T.Color('#242d36');scene.add(new T.HemisphereLight(0xe0f1ff,0x333025,2.5));const key=new T.DirectionalLight(0xffe3bf,3);key.position.set(3,5,4);scene.add(key);const camera=new T.PerspectiveCamera(40,1,.01,1000);let object:T.Object3D;
 try{if(asset.type==='model'){object=(await new GLTFLoader().loadAsync(url(asset.path))).scene;}else{const texture=await new T.TextureLoader().loadAsync(url(asset.maps?.baseColor||asset.path));texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(3,3);const material=new T.MeshStandardMaterial({map:texture,roughness:asset.surface?.roughness??.8,metalness:asset.surface?.metalness??0});for(const [channel,field] of [['normal','normalMap'],['roughness','roughnessMap'],['metalness','metalnessMap'],['ao','aoMap']] as const)if(asset.maps?.[channel]){const map=await new T.TextureLoader().loadAsync(url(asset.maps[channel]!));map.colorSpace=T.NoColorSpace;map.wrapS=map.wrapT=T.RepeatWrapping;map.repeat.set(3,3);material[field]=map;}object=new T.Group();object.add(new T.Mesh(new T.SphereGeometry(.8,48,32),material));const plane=new T.Mesh(new T.BoxGeometry(2.6,.06,2.6),material);plane.position.y=-.84;object.add(plane);}
 scene.add(object);const box=new T.Box3().setFromObject(object),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()).length();object.position.sub(center);camera.position.set(size*.9,size*.6,size*.95);camera.lookAt(0,0,0);const orbit=interactive?new OrbitControls(camera,canvas):undefined;let id=0,closed=false;const draw=()=>{if(closed)return;const w=canvas.clientWidth||160,h=canvas.clientHeight||120;gl.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();orbit?.update();gl.render(scene,camera);if(interactive)id=requestAnimationFrame(draw);};draw();return {image:canvas.toDataURL(),setLight:(value:number)=>key.intensity=value,dispose:()=>{closed=true;cancelAnimationFrame(id);orbit?.dispose();disposeTree(scene);gl.dispose();gl.forceContextLoss();}};
 }catch(error){disposeTree(scene);gl.dispose();gl.forceContextLoss();throw error;}
}
