export class AudioEngine{
 context:AudioContext|null=null;master:GainNode|null=null;muted=false;next=0;beat=0;lastHit=0;
 async unlock(){try{if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=this.muted?0:.28;this.master.connect(this.context.destination);}await this.context.resume();}catch{}}
 setMuted(v:boolean){this.muted=v;if(this.context&&this.master)this.master.gain.setTargetAtTime(v?0:.28,this.context.currentTime,.04);}
 tone(f:number,end:number,duration:number,volume:number,type:OscillatorType='sine',delay=0){const c=this.context;if(!c||!this.master||this.muted)return;const t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(volume,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.05);o.onended=()=>{o.disconnect();g.disconnect();};}
 play(s:string){if(!this.context||this.muted)return;if(s==='hit'){if(this.context.currentTime-this.lastHit<.07)return;this.lastHit=this.context.currentTime;this.tone(470,180,.06,.1,'triangle');}else if(s==='sword'){this.tone(420,60,.18,.12,'triangle');this.tone(1600,500,.06,.035,'sawtooth');}else if(s==='bow')this.tone(310,95,.13,.09,'triangle');else if(s==='fire'||s==='nova'||s==='blast'){this.tone(s==='nova'?130:250,35,.38,.16,'triangle');this.tone(570,140,.2,.05,'sawtooth');}else if(s==='hurt')this.tone(100,38,.22,.22,'sawtooth');else if(s==='dash')this.tone(120,500,.12,.06,'triangle');else if(s==='kill')this.tone(85,30,.14,.1);else if(s==='boss'||s==='dead')this.tone(85,31,1.2,.18,'sawtooth');else if(s==='bell'){[220,440,660].forEach(f=>this.tone(f,f*.995,2.8,.12));}else if(s==='pickup'||s==='upgrade'){[0,3,7].forEach((n,i)=>this.tone(330*2**(n/12),330*2**(n/12),.5,.07,'sine',i*.1));}}
 update(active:boolean){const c=this.context;if(!c||!active||this.muted){this.next=0;return;}if(c.currentTime<this.next)return;const step=this.beat++%16,root=[73.416,65.406,55,65.406][Math.floor(step/4)];if(step%4===0){this.tone(root,root,1.8,.04,'triangle');this.tone(root*1.5,root*1.5,1.7,.018);}if(step%2===0)this.tone(125,43,.2,.055);if(step%4===1)this.tone(root*4,root*4,.8,.022,'triangle');this.next=c.currentTime+.4;}
 dispose(){void this.context?.close();this.context=null;}
}
