import type {EngineModule,RuntimeSession,SessionOptions} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {World,readLevel,WEAPONS,UPGRADES,STATIONS,difficulty,type Controls,type Upgrade} from './world.ts';
import {Renderer} from './renderer.ts';
import {AudioEngine} from './audio.ts';
const time=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const crest='<svg viewBox="0 0 44 52" fill="none"><path d="M3 3h38v25c0 10-19 21-19 21S3 38 3 28V3Z" stroke="currentColor" stroke-width="2"/><path d="M22 10v28M12 20h20M17 12l5-5 5 5" stroke="currentColor" stroke-width="2"/></svg>';
export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');const root=options.container,oldTitle=document.title;document.title=options.snapshot.manifest.name;root.classList.add('bastion');
 const world=new World(readLevel(options.snapshot.scenes[options.sceneId]));
 root.innerHTML=`<canvas tabindex="0" aria-label="Последний бастион: WASD движение, мышь прицел, ЛКМ атака, 1 2 3 оружие, Shift рывок, пробел магическое кольцо, E взаимодействие."></canvas>
 <header class="b-hud" hidden><div class="b-brand">${crest}<div><small>КРЕПОСТЬ СЕРОГО ОРДЕНА</small><strong data-zone>Двор клятвы</strong></div></div><div class="b-time"><small>ВРЕМЯ ВЫЖИВАНИЯ</small><b data-time>00:00</b><span data-threat>НАТИСК I</span></div><div class="b-tools"><span class="b-kills"><b data-kills>0</b><small>ПОВЕРЖЕНО</small></span><button data-map aria-label="Карта крепости">◇</button><button data-sound aria-label="Выключить звук">♫</button><button data-pause aria-label="Пауза">Ⅱ</button></div></header>
 <div class="b-boss" hidden><span>ПОЛКОВОДЕЦ ПРАХА</span><i><b></b></i></div><div class="b-banner" role="status"></div>
 <div class="b-tip" hidden><b>ТВОЯ КЛЯТВА — ВЫЖИТЬ</b><span>WASD · движение &nbsp; ЛКМ · атака &nbsp; 1 / 2 / 3 · оружие</span><small>Shift · рывок &nbsp; Пробел · кольцо льда &nbsp; Tab · карта</small></div>
 <div class="b-interact" hidden><kbd>E</kbd><div><b></b><span></span></div></div>
 <footer class="b-bottom" hidden><div class="b-vitals"><div class="b-bar-label"><span>СТРАЖ <b data-rank>01</b></span><strong data-health>120 / 120</strong></div><div class="b-track hp"><i></i></div><div class="b-resource"><span>МАНА</span><div class="b-track mana"><i></i></div><b data-mana>100</b></div><div class="b-resource"><span>СИЛЫ</span><div class="b-track stamina"><i></i></div><b data-stamina>100</b></div></div><div class="b-abilities"><button data-dash><kbd>SHIFT</kbd><span>РЫВОК</span><b data-dash-value>ГОТОВ</b></button><button data-nova><kbd>ПРОБЕЛ</kbd><span>КОЛЬЦО ЛЬДА</span><b data-nova-value>28 МАНЫ</b></button></div><div class="b-weapons">${WEAPONS.map((w,i)=>`<button data-weapon="${i}"><kbd>${i+1}</kbd><span>${w.type}</span><small>${w.name}</small></button>`).join('')}<div class="b-ammo"><b data-ammo>∞</b><span data-ammo-label>ТРИ УДАРА В СЕРИИ</span></div></div></footer><div class="b-xp" hidden><i></i></div>
 <section class="b-title"><nav><span>SHELTER <i>/</i> ARCADE</span><small>ОДИН СТРАЖ. БЕСКОНЕЧНАЯ НОЧЬ.</small><button data-sound aria-label="Выключить звук">♫</button></nav><div class="b-title-main"><div class="b-eyebrow"><i></i> НОЧЬ БЕЗ РАССВЕТА</div><h1>Последний<br><em>бастион</em></h1><p>За стенами больше нет живых.<br>В твоих руках — сталь, огонь и старая клятва.<br><b>Пусть эта ночь запомнит твоё имя.</b></p><button class="b-primary" data-start>Принять клятву <span>→</span></button><button class="b-help" data-help>Управление и крепость <span>↗</span></button><div class="b-record"><span>ТВОЙ ЛУЧШИЙ ДОЗОР</span><b data-record>—</b></div></div><div class="b-title-seal">${crest}<span>СЕРЫЙ ОРДЕН</span><small>ДО ПОСЛЕДНЕГО</small></div><div class="b-title-bottom"><div><b>01</b><span>КРЕПОСТЬ СЕРОГО ОРДЕНА</span></div><div><b>03</b><span>ПУТИ СРАЖЕНИЯ</span></div><div><b>∞</b><span>ВРАГОВ ДО РАССВЕТА</span></div><small>ВИД СВЕРХУ · ВЫЖИВАНИЕ</small></div></section>
 <section class="b-modal" hidden role="dialog" aria-modal="true" aria-labelledby="b-modal-title"><div class="b-panel"></div></section>
 <div class="b-touch" hidden><div class="b-stick" data-stick="move"><i></i><span>ДВИЖЕНИЕ</span></div><button data-interact>E</button><div class="b-stick" data-stick="aim"><i></i><span>ПРИЦЕЛ / АТАКА</span></div></div>`;
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const canvas=$<HTMLCanvasElement>('canvas'),renderer=new Renderer(canvas,world),audio=new AudioEngine(),abort=new AbortController();const keys=new Set<string>();let disposed=false,frame=0,previous=performance.now(),acc=0,ui=0,lastPhase='',modal='',fire=false,dash=false,nova=false,interact=false,weapon=-1,aimed=false,pointer={x:0,y:0},move={x:0,y:0},aim={x:0,y:0},aiming=false,record=0,recordKills=0,savedDeath=false;
 const touch=matchMedia('(pointer: coarse), (max-width: 600px)').matches;root.classList.toggle('b-mobile',touch);const key=storageKey(options.snapshot.manifest.projectId,'progress','records');
 if(options.savePolicy==='persistent')try{const value=JSON.parse(localStorage.getItem(key)||'null');if(value){if(Number.isFinite(value.seconds)&&value.seconds>=0)record=value.seconds;if(Number.isFinite(value.kills)&&value.kills>=0)recordKills=value.kills;audio.setMuted(!!value.muted);}}catch{}
 function persist(){if(options.savePolicy==='persistent')try{localStorage.setItem(key,JSON.stringify({version:1,seconds:record,kills:recordKills,muted:audio.muted}));}catch{}}
 const listen=(el:EventTarget,type:string,cb:EventListener)=>el.addEventListener(type,cb,{signal:abort.signal});
 function clear(){keys.clear();fire=dash=nova=interact=aiming=false;weapon=-1;move={x:0,y:0};aim={x:0,y:0};root.querySelectorAll<HTMLElement>('.b-stick i').forEach(n=>n.style.transform='translate(-50%,-50%)');}
 function focus(){canvas.focus({preventScroll:true});}
 function close(){modal='';$('.b-modal').hidden=true;clear();focus();}
 function start(){void audio.unlock();world.reset();savedDeath=false;renderer.map=false;renderer.snap();aimed=false;close();update();}
 function pause(){if(world.phase!=='playing')return;world.pause(true);clear();show('pause');}
 function resume(){renderer.map=false;world.pause(false);close();update();}
 function map(){if(renderer.map){resume();return;}if(world.phase!=='playing')return;world.pause(true);clear();renderer.map=true;close();update();}
 const button=(action:string,text:string,primary=false)=>`<button data-action="${action}" class="${primary?'b-primary':'b-secondary'}">${text}${primary?' <span>→</span>':''}</button>`;
 function show(kind:string){modal=kind;clear();$('.b-modal').hidden=false;const panel=$('.b-panel');panel.classList.toggle('b-wide',kind==='help'||kind==='upgrade');
  if(kind==='pause')panel.innerHTML=`<div class="b-eyebrow">ДОЗОР ПРИОСТАНОВЛЕН</div><h2 id="b-modal-title">Тишина перед боем.</h2><p>${time(world.seconds)} · ${world.kills} повержено · страж ${world.rank} уровня</p><div class="b-actions">${button('resume','Продолжить дозор',true)}${button('help','Управление и крепость')}${button('restart','Начать новый дозор')}${button('title','Главное меню')}</div><small>Рекорд сохраняется. Текущий бой действует до закрытия страницы.</small>`;
  if(kind==='help')panel.innerHTML=`<div class="b-eyebrow">НАСТАВЛЕНИЯ СЕРОГО ОРДЕНА</div><h2 id="b-modal-title">Знай свою крепость.</h2><div class="b-help-grid"><div><h3>Три пути сражения</h3><p><b>1 · Меч.</b> Бей веером. Третий удар сильнее и пробивает щит. Попадания возвращают ману.</p><p><b>2 · Лук.</b> Стрелы пробивают несколько целей. Обходи щитоносцев с фланга.</p><p><b>3 · Посох.</b> Огненные снаряды взрываются при попадании. Мана восстанавливается сама.</p><h3>Управление</h3><p>WASD / стрелки — идти<br>Мышь + ЛКМ — прицел и атака<br>Shift / ПКМ — рывок с неуязвимостью<br>Пробел — кольцо льда: оттолкнуть и замедлить<br>E — использовать место силы<br>Tab — карта с паузой · Esc / P — пауза</p></div><div><h3>Одна карта. Много решений.</h3><p><b>Двор.</b> Колодец лечит раз в 55 секунд. Четыре прохода позволяют менять маршрут.</p><p><b>Юго-запад.</b> У кузницы пополняются стрелы. <b>Север.</b> Алтарь восстанавливает ману.</p><p><b>Южные врата.</b> Звони в колокол и уходи: орда отвлечётся на 9 секунд.</p><p>Красные линии и круги предупреждают об атаках. Укрытия останавливают стрелы и огонь.</p><p>Выбирай улучшения за убийства. Каждые две минуты приходит полководец. Последней волны нет: твой результат — время жизни.</p></div></div>${button('back','Я готов',true)}`;
  if(kind==='upgrade')panel.innerHTML=`<div class="b-eyebrow">СТРАЖ ${world.rank+1} УРОВНЯ · ВРЕМЯ ОСТАНОВЛЕНО</div><h2 id="b-modal-title">Сделай клятву сильнее.</h2><p>Одно благословение до конца этого дозора.</p><div class="b-upgrades">${world.choices.map((id,i)=>`<button data-upgrade="${id}"><div><b>${UPGRADES[id].icon}</b><small>0${i+1}</small></div><h3>${UPGRADES[id].name}</h3><p>${UPGRADES[id].detail}</p><span>Принять благословение →</span></button>`).join('')}</div>`;
  if(kind==='dead')panel.innerHTML=`<div class="b-eyebrow">ПОСЛЕДНЯЯ КЛЯТВА ИСПОЛНЕНА</div><h2 id="b-modal-title">Ночь запомнит тебя.</h2><div class="b-result"><div><b>${time(world.seconds)}</b><span>ВРЕМЯ ДОЗОРА</span></div><div><b>${world.kills}</b><span>ПОВЕРЖЕНО</span></div><div><b>${world.bosses}</b><span>ПОЛКОВОДЦЕВ</span></div></div><p>${world.seconds>=record?'Твой лучший дозор.':'Лучший дозор: '+time(record)}<br>Меняй оружие, уходи от окружения и используй места силы.</p><div class="b-actions">${button('restart','Встать на новый дозор',true)}${button('title','Главное меню')}</div>`;
  queueMicrotask(()=>panel.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true}));
 }
 function update(){const title=world.phase==='title',p=world.player;$('.b-title').hidden=!title;$('.b-hud').hidden=title;$('.b-bottom').hidden=title||renderer.map;$('.b-xp').hidden=title||renderer.map;$('.b-touch').hidden=!touch||world.phase!=='playing';root.classList.toggle('b-playing',world.phase==='playing');root.classList.toggle('b-map',renderer.map);
  $('[data-time]').textContent=time(world.seconds);$('[data-kills]').textContent=String(world.kills);$('[data-threat]').textContent=`НАТИСК ${difficulty(world.seconds).tier} · ${world.enemies.length} ВРАГОВ`;
  const zone=[...world.level.zones].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];$('[data-zone]').textContent=zone?.name.toLocaleLowerCase('ru-RU')||'Крепость';
  $('[data-health]').textContent=`${Math.ceil(p.hp)} / ${world.maxHP}`;$('[data-rank]').textContent=String(world.rank).padStart(2,'0');$('.hp i').style.width=p.hp/world.maxHP*100+'%';$('.mana i').style.width=p.mana/world.maxMana*100+'%';$('.stamina i').style.width=p.stamina/world.maxStamina*100+'%';$('[data-mana]').textContent=String(Math.floor(p.mana));$('[data-stamina]').textContent=String(Math.floor(p.stamina));$('.b-xp i').style.width=Math.min(100,world.xp/world.nextXP*100)+'%';$('.b-vitals').classList.toggle('low',p.hp<world.maxHP*.3);
  $('[data-dash-value]').textContent=p.dashCD>0?p.dashCD.toFixed(1)+' С':p.stamina<Math.max(14,30-world.count('stride')*3)?'МАЛО СИЛ':'ГОТОВ';$('[data-nova-value]').textContent=p.novaCD>0?Math.ceil(p.novaCD)+' С':p.mana<28?'МАЛО МАНЫ':'28 МАНЫ';$('[data-ammo]').textContent=p.weapon===0?'∞':p.weapon===1?String(p.arrows):String(Math.floor(p.mana));$('[data-ammo-label]').textContent=p.weapon===0?'ТРЕТИЙ УДАР СИЛЬНЕЕ':p.weapon===1?'СТРЕЛЫ · КУЗНИЦА ↙':'МАНА · АЛТАРЬ ↑';root.querySelectorAll<HTMLElement>('[data-weapon]').forEach(n=>n.classList.toggle('active',Number(n.dataset.weapon)===p.weapon));
  $('.b-banner').textContent=world.banner;$('.b-banner').classList.toggle('visible',world.bannerTime>0&&world.phase==='playing');$('.b-tip').hidden=touch||world.seconds>14||world.seconds<3||world.phase!=='playing';const s=world.nearStation;$('.b-interact').hidden=!s||world.phase!=='playing';if(s){$('.b-interact b').textContent=STATIONS[s.kind].name;$('.b-interact span').textContent=s.cooldown>0?'Восстановится через '+Math.ceil(s.cooldown)+' с':STATIONS[s.kind].effect;}
  const boss=world.boss;$('.b-boss').hidden=!boss||title||renderer.map;if(boss)$('.b-boss i b').style.width=Math.max(0,boss.hp/boss.maxHP)*100+'%';
  $('[data-record]').textContent=record>0?`${time(record)} · ${recordKills} повержено`:'Твоя история ещё не написана';root.querySelectorAll<HTMLElement>('[data-sound]').forEach(n=>{n.textContent=audio.muted?'♩':'♫';n.setAttribute('aria-label',audio.muted?'Включить звук':'Выключить звук');});
  if(world.phase==='dead'&&!savedDeath){savedDeath=true;if(world.seconds>=record){record=world.seconds;recordKills=world.kills;}persist();}
  if(world.phase==='upgrade'&&modal!=='upgrade')show('upgrade');if(world.phase==='dead'&&modal!=='dead')show('dead');
 }
 listen(root,'click',((event:MouseEvent)=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;if(b.hasAttribute('data-sound')){void audio.unlock();audio.setMuted(!audio.muted);persist();update();return;}if(b.hasAttribute('data-start'))start();if(b.hasAttribute('data-help'))show('help');if(b.hasAttribute('data-pause'))renderer.map?resume():world.phase==='paused'?resume():pause();if(b.hasAttribute('data-map'))map();if(b.hasAttribute('data-weapon')&&world.phase==='playing'){weapon=Number(b.dataset.weapon);focus();}if(b.hasAttribute('data-dash'))dash=true;if(b.hasAttribute('data-nova'))nova=true;if(b.hasAttribute('data-interact'))interact=true;if(b.dataset.upgrade){world.choose(b.dataset.upgrade as Upgrade);close();update();}switch(b.dataset.action){case'resume':resume();break;case'restart':start();break;case'help':show('help');break;case'back':if(world.phase==='paused')show('pause');else close();break;case'title':world.phase='title';renderer.map=false;close();update();break;}}) as EventListener);
 listen(window,'keydown',((e:KeyboardEvent)=>{if(!root.isConnected)return;const code=e.code;if(code==='Escape'||code==='KeyP'){e.preventDefault();if(renderer.map)resume();else if(modal==='help'){if(world.phase==='paused')show('pause');else close();}else if(world.phase==='paused')resume();else pause();return;}if(code==='Tab'&&$('.b-modal').hidden&&!e.repeat&&world.phase!=='title'){e.preventDefault();map();return;}if(world.phase==='upgrade'&&/^Digit[123]$/.test(code)&&!e.repeat){world.choose(world.choices[Number(code.slice(-1))-1]);close();update();return;}if(world.phase!=='playing')return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(code))e.preventDefault();keys.add(code);if(!e.repeat){if(code.startsWith('Shift'))dash=true;if(code==='Space')nova=true;if(code==='KeyE')interact=true;if(/^Digit[123]$/.test(code))weapon=Number(code.slice(-1))-1;}}) as EventListener);
 listen(window,'keyup',((e:KeyboardEvent)=>{keys.delete(e.code);}) as EventListener);
 listen(canvas,'pointermove',((e:PointerEvent)=>{if(e.pointerType==='touch')return;const r=canvas.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top};renderer.pointer={...pointer,visible:true};aimed=true;}) as EventListener);
 listen(canvas,'pointerdown',((e:PointerEvent)=>{if(e.pointerType==='touch'||world.phase!=='playing')return;e.preventDefault();focus();void audio.unlock();const r=canvas.getBoundingClientRect();pointer={x:e.clientX-r.left,y:e.clientY-r.top};aimed=true;if(e.button===0)fire=true;if(e.button===2)dash=true;}) as EventListener);
 listen(window,'pointerup',()=>{fire=false;});listen(canvas,'contextmenu',e=>e.preventDefault());listen(canvas,'pointercancel',()=>{fire=false;});listen(window,'blur',()=>{clear();pause();});listen(document,'visibilitychange',()=>{if(document.hidden){clear();pause();}});
 for(const stick of root.querySelectorAll<HTMLElement>('.b-stick')){let pid=-1;const set=(e:PointerEvent)=>{const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(32,Math.hypot(dx,dy)),v={x:dx/len,y:dy/len};stick.querySelector<HTMLElement>('i')!.style.transform=`translate(calc(-50% + ${v.x*28}px),calc(-50% + ${v.y*28}px))`;if(stick.dataset.stick==='move')move=v;else{aim=v;aiming=true;}};listen(stick,'pointerdown',((e:PointerEvent)=>{e.preventDefault();pid=e.pointerId;stick.setPointerCapture(pid);void audio.unlock();set(e);}) as EventListener);listen(stick,'pointermove',((e:PointerEvent)=>{if(e.pointerId===pid)set(e);}) as EventListener);const end=(e:Event)=>{if((e as PointerEvent).pointerId!==pid)return;pid=-1;if(stick.dataset.stick==='move')move={x:0,y:0};else{aim={x:0,y:0};aiming=false;}stick.querySelector<HTMLElement>('i')!.style.transform='translate(-50%,-50%)';};for(const t of ['pointerup','pointercancel','lostpointercapture'])listen(stick,t,end);}
 listen(root,'keydown',((e:KeyboardEvent)=>{if(e.key!=='Tab'||$('.b-modal').hidden)return;const buttons=[...$('.b-panel').querySelectorAll<HTMLButtonElement>('button')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}) as EventListener);
 const observer=new ResizeObserver(()=>renderer.resize());observer.observe(canvas);world.onSound=s=>audio.play(s);
 function controls():Controls{let angle=world.player.angle;if(aiming&&Math.hypot(aim.x,aim.y)>.1)angle=Math.atan2(aim.y,aim.x);else if(aimed){const p=renderer.screenToWorld(pointer.x,pointer.y);angle=Math.atan2(p.y-world.player.y,p.x-world.player.x);}return {x:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+move.x,y:Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'))+move.y,angle,fire:fire||aiming,dash,nova,interact,weapon};}
 function tick(now:number){if(disposed)return;const dt=Math.min(.05,(now-previous)/1000);previous=now;acc+=dt;while(acc>=1/120){world.step(1/120,controls());dash=nova=interact=false;weapon=-1;acc-=1/120;}renderer.draw(dt);audio.update(world.phase==='playing');ui+=dt;if(ui>.08||lastPhase!==world.phase){lastPhase=world.phase;ui=0;update();}frame=requestAnimationFrame(tick);}
 if(import.meta.env.DEV)Object.defineProperty(window,'__BASTION__',{configurable:true,value:{world,renderer}});update();frame=requestAnimationFrame(tick);
 return {pause(value){if(value)pause();else if(world.phase==='paused')resume();},dispose(){disposed=true;cancelAnimationFrame(frame);abort.abort();observer.disconnect();audio.dispose();renderer.dispose();root.replaceChildren();root.classList.remove('bastion','b-playing','b-mobile','b-map');document.title=oldTitle;if(import.meta.env.DEV)delete (window as any).__BASTION__;},diagnostics:()=>({game:'bastion',phase:world.phase,seconds:world.seconds,kills:world.kills,enemies:world.enemies.length})};
}
const module:EngineModule={id:'bastion',sdk:1,components:[{id:'bastion.cover',name:'Препятствие крепости',fields:[{name:'style',label:'Облик',type:'select',default:'wall',options:['wall','tower','tree','fountain','chapel','forge','grave','ruin'].map(value=>({value,label:value}))}]},{id:'bastion.spawn',name:'Последний страж',fields:[]},{id:'bastion.gate',name:'Врата орды',fields:[]},{id:'bastion.station',name:'Место силы',fields:[{name:'kind',label:'Назначение',type:'select',default:'well',options:Object.entries(STATIONS).map(([value,s])=>({value,label:s.name}))}]}],validateScene(scene){readLevel(scene);},createSession:startGame};
export default module;
