import type {SceneDocument} from '@shelter/scene.ts';
export type Vec={x:number;y:number};
export type Rect=Vec&{w:number;h:number;style:string};
export type Station=Vec&{kind:'well'|'arrows'|'mana'|'bell';cooldown:number};
export type Level={width:number;height:number;cover:Rect[];spawn:Vec;gates:Vec[];stations:Station[];zones:(Vec&{name:string})[]};
export type Kind='skeleton'|'wolf'|'archer'|'guard'|'witch'|'ogre'|'lord';
export type Enemy=Vec&{id:number;kind:Kind;hp:number;maxHP:number;r:number;speed:number;angle:number;attack:number;windup:number;locked:number;birth:number;flash:number;slow:number;stride:number};
export type Bullet=Vec&{id:number;vx:number;vy:number;life:number;damage:number;enemy:boolean;kind:'arrow'|'fire'|'curse';pierce:number;hit:Set<number>};
export type Hazard=Vec&{r:number;time:number;max:number;damage:number};
export type FX=Vec&{vx:number;vy:number;life:number;max:number;color:string;size:number;kind:'spark'|'ring'|'text'|'slash';text?:string;angle?:number};
export type Pickup=Vec&{kind:'health'|'arrows'|'mana';life:number};
export type Controls={x:number;y:number;angle:number;fire:boolean;dash:boolean;nova:boolean;interact:boolean;weapon:number};
export type Upgrade=keyof typeof UPGRADES;
export const UPGRADES={
 steel:{name:'Закалённая сталь',icon:'⚔',detail:'Меч: +25% урона и +10 к дальности удара.'},
 fletching:{name:'Королевский лучник',icon:'➶',detail:'Лук: +25% урона. +20 стрел. Ещё одна цель навылет.'},
 ember:{name:'Живое пламя',icon:'✧',detail:'Посох и кольцо: +25% урона, взрыв посоха шире.'},
 vitality:{name:'Несломленная клятва',icon:'✚',detail:'+25 к здоровью. Восстановить 45 здоровья.'},
 flow:{name:'Исток',icon:'◈',detail:'+20 к мане, +1.5 маны в секунду. Восполнить ману.'},
 stride:{name:'Лёгкий шаг',icon:'»',detail:'+7% к скорости, рывок тратит меньше выносливости.'},
 leech:{name:'Цена крови',icon:'♥',detail:'Каждое убийство возвращает 1.5 здоровья.'},
 haste:{name:'Боевая память',icon:'⌁',detail:'+12% к скорости всех атак. +20 выносливости.'}
};
export const WEAPONS=[{name:'КЛЯТВА',type:'Меч',hint:'Размашистые удары · третий сильнее',color:'#e6c582'},{name:'ТИС',type:'Длинный лук',hint:'Стрелы пробивают врагов',color:'#b7d49a'},{name:'УГОЛЬ',type:'Огненный посох',hint:'Взрыв по площади · расход маны',color:'#9ddcda'}];
export const STATIONS={well:{name:'Колодец клятвы',effect:'+50 здоровья',cooldown:55,color:'#bde0aa'},arrows:{name:'Кузница',effect:'+32 стрелы',cooldown:28,color:'#e9ba7b'},mana:{name:'Алтарь истока',effect:'Восполнить ману',cooldown:38,color:'#96d9dc'},bell:{name:'Колокол',effect:'Отвлечь врагов на 9 секунд',cooldown:42,color:'#e2c789'}};
export const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
export const distance=(a:Vec,b:Vec)=>Math.hypot(a.x-b.x,a.y-b.y);
export const angleDelta=(a:number,b:number)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
export function readLevel(scene:SceneDocument):Level{
 const d=scene.moduleData?.bastion as {version:number;width:number;height:number;zones:Level['zones']}|undefined;
 if(!d||d.version!==1||!Number.isFinite(d.width)||d.width<800||!Number.isFinite(d.height)||d.height<800)throw new Error('Бастион: некорректная карта');
 const find=(type:string)=>scene.nodes.filter(n=>n.components?.some(c=>c.type==='bastion.'+type));
 const pos=(n:SceneDocument['nodes'][number])=>({x:n.transform.position[0]*64,y:-n.transform.position[1]*64});
 const cover=find('cover').map(n=>({...pos(n),w:n.transform.scale[0]*64,h:n.transform.scale[1]*64,style:String(n.components!.find(c=>c.type==='bastion.cover')!.values.style)}));
 const sp=find('spawn')[0],gates=find('gate').map(pos),stations=find('station').map(n=>({...pos(n),kind:n.components!.find(c=>c.type==='bastion.station')!.values.kind as Station['kind'],cooldown:0}));
 if(!sp||gates.length<4||stations.some(s=>!(s.kind in STATIONS))||cover.some(c=>c.w<=0||c.h<=0))throw new Error('Бастион: проверьте укрытия, врата и места силы');
 return {width:d.width,height:d.height,cover,spawn:pos(sp),gates,stations,zones:d.zones||[]};
}
// Segment entry parameter: 0..1, or Infinity. Shared by projectiles and navigation.
export function segmentRect(a:Vec,b:Vec,r:Rect,pad=0){let lo=0,hi=1;for(const [p,v,min,max] of [[a.x,b.x-a.x,r.x-r.w/2-pad,r.x+r.w/2+pad],[a.y,b.y-a.y,r.y-r.h/2-pad,r.y+r.h/2+pad]]){if(Math.abs(v)<1e-8){if(p<min||p>max)return Infinity;}else{const t=(min-p)/v,u=(max-p)/v;lo=Math.max(lo,Math.min(t,u));hi=Math.min(hi,Math.max(t,u));if(lo>hi)return Infinity;}}return lo;}
export function difficulty(t:number){t=Math.max(0,t);return {tier:1+Math.floor(t/45),interval:Math.max(.28,2.5/(1+t/70)),cap:Math.min(76,10+Math.floor(t/5)),health:1+t/330,damage:1+t/420,speed:1+Math.min(.45,t/900)};}
const STATS:Record<Kind,[number,number,number,number]>={skeleton:[65,77,18,6],wolf:[46,135,15,7],archer:[65,68,18,9],guard:[155,61,23,13],witch:[95,60,19,14],ogre:[420,54,32,26],lord:[1500,58,37,80]};
export class World{
 level:Level;phase:'title'|'playing'|'paused'|'upgrade'|'dead'='title';seed=247;uid=1;seconds=0;kills=0;bosses=0;xp=0;nextXP=24;rank=1;nextBoss=120;spawnClock=2;navClock=0;nav=new Map<string,number>();navTarget:Vec={x:0,y:0};
 player={x:0,y:0,angle:-Math.PI/2,hp:120,mana:100,stamina:100,arrows:48,weapon:0,cooldown:0,dash:0,dashCD:0,invincible:0,novaCD:0,combo:0,comboTime:0,swing:0,stride:0,dx:0,dy:0};
 enemies:Enemy[]=[];bullets:Bullet[]=[];hazards:Hazard[]=[];particles:FX[]=[];pickups:Pickup[]=[];upgrades:Upgrade[]=[];choices:Upgrade[]=[];
 stations:Station[]=[];lure:Vec&{time:number}={x:0,y:0,time:0};banner='';bannerTime=0;damageFlash=0;shake=0;hitFlash=0;onSound:(name:string)=>void=()=>{};
 constructor(level:Level){this.level=level;this.reset();this.phase='title';}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 count(id:Upgrade){return this.upgrades.filter(u=>u===id).length;}
 get maxHP(){return 120+25*this.count('vitality');}get maxMana(){return 100+20*this.count('flow');}get maxStamina(){return 100+20*this.count('haste');}get maxArrows(){return 72+10*this.count('fletching');}
 get speed(){return 230*(1+Math.min(.7,this.count('stride')*.07));}get rate(){return 1+this.count('haste')*.12;}get boss(){return this.enemies.find(e=>e.kind==='lord'&&e.hp>0);}
 reset(){this.phase='playing';this.seed=247;this.uid=1;this.seconds=this.kills=this.bosses=this.xp=0;this.rank=1;this.nextXP=24;this.nextBoss=120;this.spawnClock=2;this.navClock=0;this.nav.clear();this.enemies=[];this.bullets=[];this.hazards=[];this.particles=[];this.pickups=[];this.upgrades=[];this.choices=[];this.lure.time=0;this.damageFlash=this.shake=this.hitFlash=0;this.stations=this.level.stations.map(s=>({...s,cooldown:0}));Object.assign(this.player,{...this.level.spawn,angle:-Math.PI/2,hp:120,mana:100,stamina:100,arrows:48,weapon:0,cooldown:0,dash:0,dashCD:0,invincible:1.5,novaCD:0,combo:0,comboTime:0,swing:0,stride:0,dx:0,dy:0});this.announce('ДЕРЖИСЬ ДО ПОСЛЕДНЕГО');for(const i of [0,2,5])this.spawn('skeleton',this.level.gates[i]);}
 announce(text:string){this.banner=text;this.bannerTime=3.2;}
 pause(value:boolean){if(value&&this.phase==='playing')this.phase='paused';else if(!value&&this.phase==='paused')this.phase='playing';}
 blocked(x:number,y:number,r=18){return x<80+r||y<80+r||x>this.level.width-80-r||y>this.level.height-80-r||this.level.cover.some(c=>Math.hypot(x-clamp(x,c.x-c.w/2,c.x+c.w/2),y-clamp(y,c.y-c.h/2,c.y+c.h/2))<r);}
 move(p:Vec,dx:number,dy:number,r:number){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/9));for(let i=0;i<steps;i++){if(!this.blocked(p.x+dx/steps,p.y,r))p.x+=dx/steps;if(!this.blocked(p.x,p.y+dy/steps,r))p.y+=dy/steps;}}
 sight(a:Vec,b:Vec,pad=0){return !this.level.cover.some(r=>segmentRect(a,b,r,pad)!==Infinity);}
 buildNav(){const cell=40,target=this.lure.time>0?this.lure:this.player;this.navTarget={x:target.x,y:target.y};const sx=Math.floor(target.x/cell),sy=Math.floor(target.y/cell),queue:[[number,number]]|[number,number][]=[[sx,sy]];this.nav.clear();this.nav.set(`${sx},${sy}`,0);for(let i=0;i<queue.length;i++){const [x,y]=queue[i],v=this.nav.get(`${x},${y}`)!;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=`${nx},${ny}`;if(this.nav.has(k)||this.blocked(nx*cell+20,ny*cell+20,40)||this.level.cover.some(r=>Math.abs(nx*cell+20-r.x)<r.w/2+40&&Math.abs(ny*cell+20-r.y)<r.h/2+40))continue;this.nav.set(k,v+1);queue.push([nx,ny]);}}}
 direction(e:Enemy){let t=this.lure.time>0?this.lure:this.player;if(!this.sight(e,t,e.r+3)){const cx=Math.floor(e.x/40),cy=Math.floor(e.y/40);let best=Infinity;for(const [dx,dy] of [[0,0],[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[1,-1],[-1,1],[1,1]]){const p={x:(cx+dx)*40+20,y:(cy+dy)*40+20},cost=this.nav.get(`${cx+dx},${cy+dy}`);if(cost!==undefined&&cost<best&&this.sight(e,p,e.r+2)){best=cost;t=p as typeof t;}}}const d=distance(e,t)||1;return {x:(t.x-e.x)/d,y:(t.y-e.y)/d};}
 spawn(kind?:Kind,at?:Vec){const d=difficulty(this.seconds),r=this.random();kind??=this.seconds>180&&r<.12?'ogre':this.seconds>75&&r<.24?'witch':this.seconds>45&&r<.42?'guard':this.seconds>20&&r<.59?'archer':this.seconds>10&&r<.77?'wolf':'skeleton';const pool=this.level.gates.filter(g=>distance(g,this.player)>500);const gates=pool.length?pool:this.level.gates;const p=at||gates[Math.floor(this.random()*gates.length)],stats=STATS[kind];const e:Enemy={...p,id:this.uid++,kind,hp:stats[0]*d.health,maxHP:stats[0]*d.health,r:stats[2],speed:stats[1]*d.speed,angle:0,attack:1.4,windup:0,locked:0,birth:1.2,flash:0,slow:0,stride:0};if(this.enemies.length>=80){const far=this.enemies.filter(v=>v.kind!=='lord').sort((a,b)=>distance(b,this.player)-distance(a,this.player))[0];if(far)this.enemies=this.enemies.filter(v=>v!==far);else return undefined;}this.enemies.push(e);return e;}
 ring(p:Vec,color:string,size:number){this.particles.push({...p,vx:0,vy:0,life:.5,max:.5,color,size,kind:'ring'});}
 text(p:Vec,text:string,color='#e8d6a6'){this.particles.push({...p,vx:0,vy:-30,life:.9,max:.9,color,size:15,kind:'text',text});}
 burst(p:Vec,color:string,n=10){for(let i=0;i<n;i++){const a=this.random()*Math.PI*2,v=25+this.random()*170;this.particles.push({...p,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.2+this.random()*.4,max:.6,color,size:2+this.random()*3,kind:'spark'});}if(this.particles.length>400)this.particles.splice(0,this.particles.length-400);}
 hit(e:Enemy,damage:number,magic=false,cleave=false){if(e.hp<=0||e.birth>0)return;const a=Math.atan2(this.player.y-e.y,this.player.x-e.x);if(e.kind==='guard'&&!magic&&!cleave&&Math.abs(angleDelta(a,e.angle))<1.05){damage*=.35;this.text(e,'БЛОК','#c4c9c6');}e.hp-=damage;e.flash=.12;this.hitFlash=.09;this.burst(e,magic?'#98dcd7':'#e4bb82',5);this.onSound('hit');if(e.hp<=0){this.kills++;this.xp+=STATS[e.kind][3];this.player.hp=Math.min(this.maxHP,this.player.hp+1.5*this.count('leech'));this.burst(e,e.kind==='witch'?'#bc9ad0':'#b59e7b',13);this.onSound('kill');if(e.kind==='lord'){this.bosses++;this.xp+=45;this.pickups.push({...e,kind:'health',life:50},{x:e.x+28,y:e.y,kind:'arrows',life:50},{x:e.x-28,y:e.y,kind:'mana',life:50});this.announce('ПОЛКОВОДЕЦ ПАЛ. НОЧЬ ПРОДОЛЖАЕТСЯ.');}else if(this.kills%3===0){const roll=this.random();this.pickups.push({...e,kind:roll<.3?'health':roll<.67?'arrows':'mana',life:30});}}}
 hurt(damage:number){const p=this.player;if(this.phase!=='playing'||p.invincible>0||p.dash>0)return;p.hp=Math.max(0,p.hp-damage);p.invincible=.42;this.damageFlash=.4;this.shake=7;this.onSound('hurt');if(p.hp<=0){this.phase='dead';this.announce('КЛЯТВА ИСПОЛНЕНА');this.onSound('dead');}}
 attack(){const p=this.player;if(p.cooldown>0)return;const weapon=p.weapon;if(weapon===1&&p.arrows<=0){p.cooldown=.3;this.text(p,'НУЖНЫ СТРЕЛЫ');return;}if(weapon===2&&p.mana<16){p.cooldown=.3;this.text(p,'НУЖНА МАНА');return;}
  if(weapon===0){p.combo=p.comboTime>0?(p.combo+1)%3:0;p.comboTime=1.3;const heavy=p.combo===2,range=(heavy?140:115)+Math.min(70,this.count('steel')*10);p.cooldown=(heavy?.57:.36)/this.rate;p.swing=.23;this.particles.push({...p,vx:0,vy:0,life:.22,max:.22,color:heavy?'#fff1be':'#d8e1cc',size:range,kind:'slash',angle:p.angle});for(const e of this.enemies){if(distance(p,e)<range+e.r&&Math.abs(angleDelta(Math.atan2(e.y-p.y,e.x-p.x),p.angle))<(heavy?1.45:1.12)&&this.sight(p,e)){this.hit(e,(heavy?66:42)*(1+.25*this.count('steel')),false,heavy);if(e.birth<=0){this.move(e,Math.cos(p.angle)*24,Math.sin(p.angle)*24,e.r);p.mana=Math.min(this.maxMana,p.mana+3);}}}this.onSound('sword');}
  else {const magic=weapon===2;if(magic)p.mana-=16;else p.arrows--;p.cooldown=(magic?.72:.43)/this.rate;const speed=magic?540:890;this.bullets.push({id:this.uid++,x:p.x+Math.cos(p.angle)*25,y:p.y+Math.sin(p.angle)*25,vx:Math.cos(p.angle)*speed,vy:Math.sin(p.angle)*speed,life:magic?1.5:1.25,damage:(magic?58:55)*(1+.25*this.count(magic?'ember':'fletching')),enemy:false,kind:magic?'fire':'arrow',pierce:magic?1:2+Math.min(4,this.count('fletching')),hit:new Set()});this.onSound(magic?'fire':'bow');}
 }
 explode(p:Vec,damage:number){const radius=100+Math.min(85,this.count('ember')*14);this.ring(p,'#efac70',radius);this.burst(p,'#ffc68a',22);for(const e of this.enemies)if(distance(p,e)<radius+e.r&&this.sight(p,e))this.hit(e,damage,true);this.onSound('blast');}
 nova(){const p=this.player;if(p.novaCD>0||p.mana<28)return;p.mana-=28;p.novaCD=12;p.invincible=Math.max(p.invincible,.35);this.ring(p,'#9debe0',230);this.burst(p,'#a3dfda',30);for(const e of this.enemies)if(distance(p,e)<230&&this.sight(p,e)){this.hit(e,58*(1+.25*this.count('ember')),true);e.slow=3;const a=Math.atan2(e.y-p.y,e.x-p.x);this.move(e,Math.cos(a)*60,Math.sin(a)*60,e.r);}this.bullets=this.bullets.filter(b=>!b.enemy||distance(b,p)>240);this.onSound('nova');}
 get nearStation(){return this.stations.find(s=>distance(s,this.player)<110);}
 interact(){const s=this.nearStation,p=this.player;if(!s)return;if(s.cooldown>0){this.text(p,`${Math.ceil(s.cooldown)} СЕК`);return;}if(s.kind==='well'&&p.hp>=this.maxHP||s.kind==='mana'&&p.mana>=this.maxMana||s.kind==='arrows'&&p.arrows>=this.maxArrows){this.text(p,'ЗАПАС ПОЛОН');return;}s.cooldown=STATIONS[s.kind].cooldown;if(s.kind==='well')p.hp=Math.min(this.maxHP,p.hp+50);if(s.kind==='mana')p.mana=this.maxMana;if(s.kind==='arrows')p.arrows=Math.min(this.maxArrows,p.arrows+32);if(s.kind==='bell'){this.lure={x:s.x,y:s.y,time:9};this.navClock=0;this.announce('КОЛОКОЛ ОТВЛЕКАЕТ ОРДУ');}this.ring(s,STATIONS[s.kind].color,130);this.onSound(s.kind==='bell'?'bell':'pickup');}
 choose(id:Upgrade){if(this.phase!=='upgrade'||!this.choices.includes(id))return false;this.upgrades.push(id);if(id==='vitality')this.player.hp=Math.min(this.maxHP,this.player.hp+45);if(id==='flow')this.player.mana=this.maxMana;if(id==='fletching')this.player.arrows=Math.min(this.maxArrows,this.player.arrows+20);if(id==='haste')this.player.stamina=this.maxStamina;this.rank++;this.xp-=this.nextXP;this.nextXP=Math.round(24+this.rank*12+this.rank*this.rank*1.6);this.choices=[];this.phase='playing';this.player.invincible=Math.max(.7,this.player.invincible);this.onSound('upgrade');return true;}
 enemyAttack(e:Enemy){const p=this.player,d=difficulty(this.seconds);if(e.kind==='archer'){this.bullets.push({id:this.uid++,x:e.x,y:e.y,vx:Math.cos(e.locked)*365,vy:Math.sin(e.locked)*365,life:2.5,damage:15*d.damage,enemy:true,kind:'arrow',pierce:1,hit:new Set()});this.onSound('bow');}else if(e.kind==='witch'){this.hazards.push({x:p.x,y:p.y,r:83,time:1.1,max:1.1,damage:22*d.damage});}else if(e.kind==='ogre'||e.kind==='lord'){const lord=e.kind==='lord';this.ring(e,'#e2a06f',lord?155:115);if(distance(p,e)<(lord?155:115)&&this.sight(e,p))this.hurt((lord?30:24)*d.damage);if(lord)for(let i=0;i<8;i++){const a=i*Math.PI/4+e.locked;this.bullets.push({id:this.uid++,x:e.x,y:e.y,vx:Math.cos(a)*210,vy:Math.sin(a)*210,life:3.5,damage:17*d.damage,enemy:true,kind:'curse',pierce:1,hit:new Set()});}}else if(distance(e,p)<e.r+48&&this.sight(e,p))this.hurt((e.kind==='guard'?18:11)*d.damage);e.attack=e.kind==='archer'?2.25:e.kind==='witch'?3.3:e.kind==='lord'?2.3:1.15;}
 step(dt:number,c:Controls){if(this.phase!=='playing')return;dt=clamp(dt,0,.04);this.seconds+=dt;const p=this.player,d=difficulty(this.seconds);for(const key of ['cooldown','dash','dashCD','invincible','novaCD','comboTime','swing'] as const)p[key]=Math.max(0,p[key]-dt);p.mana=Math.min(this.maxMana,p.mana+(4.5+this.count('flow')*1.5)*dt);p.stamina=Math.min(this.maxStamina,p.stamina+22*dt);this.bannerTime=Math.max(0,this.bannerTime-dt);this.damageFlash=Math.max(0,this.damageFlash-dt);this.hitFlash=Math.max(0,this.hitFlash-dt);this.shake=Math.max(0,this.shake-dt*24);this.lure.time=Math.max(0,this.lure.time-dt);for(const s of this.stations)s.cooldown=Math.max(0,s.cooldown-dt);
  if(Number.isFinite(c.angle))p.angle=c.angle;if(c.weapon>=0&&c.weapon<3)p.weapon=c.weapon;const len=Math.max(1,Math.hypot(c.x,c.y)),dx=c.x/len,dy=c.y/len;const cost=Math.max(14,30-this.count('stride')*3);
  if(c.dash&&p.dashCD<=0&&p.stamina>=cost){p.stamina-=cost;p.dash=.18;p.dashCD=.7;p.dx=dx||dy?dx:Math.cos(p.angle);p.dy=dx||dy?dy:Math.sin(p.angle);this.onSound('dash');}
  const vx=p.dash>0?p.dx*790:dx*this.speed,vy=p.dash>0?p.dy*790:dy*this.speed;this.move(p,vx*dt,vy*dt,18);p.stride+=Math.hypot(vx,vy)*dt*.04;
  if(c.fire)this.attack();if(c.nova)this.nova();if(c.interact)this.interact();
  this.spawnClock-=dt;if(this.spawnClock<=0){this.spawnClock=d.interval;if(this.enemies.length<d.cap)this.spawn();}if(this.seconds>=this.nextBoss){this.nextBoss+=120;this.spawn('lord');this.announce('ПОЛКОВОДЕЦ ПРАХА ВСТУПАЕТ В БОЙ');this.onSound('boss');}
  this.navClock-=dt;if(this.navClock<=0){this.navClock=.4;this.buildNav();}
  for(const e of this.enemies){if(e.hp<=0)continue;e.birth=Math.max(0,e.birth-dt);e.flash=Math.max(0,e.flash-dt);e.slow=Math.max(0,e.slow-dt);if(e.birth>0)continue;e.attack-=dt;const target=this.lure.time>0?this.lure:p,dist=distance(e,target);e.angle=Math.atan2(target.y-e.y,target.x-e.x);if(e.windup>0){e.windup-=dt;if(e.windup<=0)this.enemyAttack(e);continue;}
   const ranged=e.kind==='archer'||e.kind==='witch',range=ranged?470:e.kind==='lord'?130:e.kind==='ogre'?95:48;
   if(dist>range||!this.sight(e,target)){const dir=this.direction(e);let ax=dir.x,ay=dir.y;for(const o of this.enemies){if(o===e||o.hp<=0)continue;const dd=distance(e,o),sep=e.r+o.r+5;if(dd>0&&dd<sep){ax+=(e.x-o.x)/dd*(1-dd/sep)*1.8;ay+=(e.y-o.y)/dd*(1-dd/sep)*1.8;}}const norm=Math.max(1,Math.hypot(ax,ay)),speed=e.speed*(e.slow>0?.45:1);this.move(e,ax/norm*speed*dt,ay/norm*speed*dt,e.r);e.stride+=speed*dt*.04;}
   if(e.attack<=0&&dist<range+15&&this.sight(e,target)){if(this.lure.time>0){e.attack=1;continue;}e.windup=e.kind==='archer'?.8:e.kind==='witch'?.85:e.kind==='lord'?.95:e.kind==='ogre'?.9:.42;e.locked=e.angle;}
  }
  this.enemies=this.enemies.filter(e=>e.hp>0);
  for(const b of this.bullets){const from={x:b.x,y:b.y},to={x:b.x+b.vx*dt,y:b.y+b.vy*dt};b.life-=dt;let wall=1;for(const r of this.level.cover)wall=Math.min(wall,segmentRect(from,to,r,2));const end={x:from.x+(to.x-from.x)*wall,y:from.y+(to.y-from.y)*wall};const hits:{t:number;e:Enemy}[]=[];
   const near=(v:Vec,r:number)=>{const dx=end.x-from.x,dy=end.y-from.y,t=clamp(((v.x-from.x)*dx+(v.y-from.y)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(from.x+dx*t-v.x,from.y+dy*t-v.y)<r?t:Infinity;};
   if(b.enemy){if(near(p,22)<Infinity){this.hurt(b.damage);b.life=0;}}else for(const e of this.enemies)if(e.hp>0&&e.birth<=0&&!b.hit.has(e.id)){const t=near(e,e.r+6);if(t<Infinity)hits.push({t,e});}
   hits.sort((a,b)=>a.t-b.t);for(const hit of hits){if(b.pierce<=0)break;b.hit.add(hit.e.id);b.pierce--;if(b.kind==='fire'){b.x=from.x+(end.x-from.x)*hit.t;b.y=from.y+(end.y-from.y)*hit.t;this.explode(b,b.damage);b.life=0;}else this.hit(hit.e,b.damage);if(b.pierce<=0)b.life=0;}
   if(b.life>0&&wall<1){if(!b.enemy&&b.kind==='fire')this.explode(end,b.damage);else this.burst(end,b.enemy?'#d9a188':'#cbd1b3',3);b.life=0;}b.x=end.x;b.y=end.y;if(b.x<80||b.y<80||b.x>this.level.width-80||b.y>this.level.height-80)b.life=0;
  }this.bullets=this.bullets.filter(b=>b.life>0).slice(-260);
  for(const h of this.hazards){h.time-=dt;if(h.time<=0){this.ring(h,'#cda1d1',h.r);this.burst(h,'#c7a2d6',12);if(distance(h,p)<h.r+16&&this.sight(h,p))this.hurt(h.damage);}}this.hazards=this.hazards.filter(h=>h.time>0);
  for(const item of this.pickups){item.life-=dt;if(distance(p,item)<43&&this.sight(p,item)){if(item.kind==='health'){if(p.hp>=this.maxHP)continue;p.hp=Math.min(this.maxHP,p.hp+22);}else if(item.kind==='arrows'){if(p.arrows>=this.maxArrows)continue;p.arrows=Math.min(this.maxArrows,p.arrows+9);}else{if(p.mana>=this.maxMana)continue;p.mana=Math.min(this.maxMana,p.mana+26);}this.text(item,item.kind==='health'?'+22':item.kind==='arrows'?'+9':'+26',STATIONS[item.kind==='health'?'well':item.kind].color);item.life=0;this.onSound('pickup');}}this.pickups=this.pickups.filter(i=>i.life>0).slice(-80);
  for(const f of this.particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}this.particles=this.particles.filter(f=>f.life>0);
  if(this.phase==='playing'&&this.xp>=this.nextXP){const all=Object.keys(UPGRADES) as Upgrade[];for(let i=all.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[all[i],all[j]]=[all[j],all[i]];}this.choices=all.slice(0,3);this.phase='upgrade';this.onSound('upgrade');}
 }
}
