import * as fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {randomUUID,createHash} from 'node:crypto';
import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import type {ViteDevServer,Plugin} from 'vite';
import {validateSnapshot,portablePath,type AssetRecord,type ProjectSession,type ProjectSnapshot} from '../../src/engine/project.ts';
import {inspectGLTF} from '../../src/engine/asset-format.ts';
import {template} from './templates.ts';
import {atomic,inside,readProject,writeProject,revision,filesUnder,json,locked} from './files.ts';
import {pack,unpack} from './zip.ts';
import {startBuild,builds} from './build.ts';
import {Publisher} from './publish.ts';
import {syncUsage} from './usage.ts';
const mime:Record<string,string>={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.glb':'model/gltf-binary','.gltf':'model/gltf+json','.svg':'image/svg+xml','.zip':'application/zip'};
async function body(req:IncomingMessage){const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>180*1024*1024)throw new Error('Загрузка превышает 180 МБ.');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString()||'{}');}
async function exists(file:string){try{await fs.access(file);return true;}catch{return false;}}
export function enginePlugin():Plugin {return {name:'shelter-engine-service',configureServer(server){const service=new EngineService(server.config.root,server);server.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/api/'))void service.handle(req,res).catch(e=>{res.statusCode=400;res.setHeader('Content-Type','application/json');res.end(json({error:e instanceof Error?e.message:String(e)}));});else next();});server.httpServer?.on('close',()=>service.close());}};}
export class EngineService {
 sessions=new Map<string,{path:string}>();previews=new Map<string,ReturnType<typeof createServer>>();root:string;library:string;
 publisher:Publisher;
 constructor(root:string,private vite?:ViteDevServer){this.root=root;this.library=path.join(root,'library');this.publisher=new Publisher(root);}
 close(){for(const s of this.previews.values())s.close();}
 async session(root:string):Promise<ProjectSession>{const canonical=await fs.realpath(root),snapshot=await readProject(canonical);let token=[...this.sessions].find(([,s])=>s.path===canonical)?.[0];if(!token){token=randomUUID();this.sessions.set(token,{path:canonical});}if(this.vite&&!this.vite.config.server.fs.allow.includes(canonical))this.vite.config.server.fs.allow.push(canonical);
  const recentFile=path.join(this.root,'.shelter-cache/recent.json');let recent:{path:string;name:string}[]=[];try{recent=JSON.parse(await fs.readFile(recentFile,'utf8'));}catch{}recent=[{path:canonical,name:snapshot.manifest.name},...recent.filter(r=>r.path!==canonical)].slice(0,20);await atomic(recentFile,json(recent));
  return {...snapshot,token,path:canonical,revision:revision(snapshot),moduleUrls:snapshot.manifest.modules.map(m=>({runtime:m.runtime==='builtin:basic'?m.runtime:`/@fs/${canonical}/${m.runtime}`,editor:m.editor?`/@fs/${canonical}/${m.editor}`:undefined}))};
 }
 project(token:string){const s=this.sessions.get(token);if(!s)throw new Error('Проект не открыт. Откройте его через менеджер.');return s.path;}
 async sendFile(res:ServerResponse,file:string){const data=await fs.readFile(file);res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.end(data);}
 async handle(req:IncomingMessage,res:ServerResponse){
  const host=req.headers.host||'',origin=req.headers.origin;if(!/^(127\.0\.0\.1|localhost|\[::1\])(?::\d+)?$/.test(host)||origin&&origin!==`http://${host}`||req.headers['sec-fetch-site']==='cross-site')throw new Error('Доступ разрешён только локальному редактору.');
  const url=new URL(req.url!,'http://'+host),route=url.pathname,method=req.method;
  if(method==='GET'&&route.startsWith('/api/file/')){const [, , ,token,...parts]=route.split('/');return this.sendFile(res,await inside(this.project(token),decodeURIComponent(parts.join('/'))));}
  if(method==='GET'&&route.startsWith('/api/library-file/'))return this.sendFile(res,await inside(this.library,decodeURIComponent(route.slice('/api/library-file/'.length))));
  if(method==='POST'&&!req.headers['content-type']?.startsWith('application/json'))throw new Error('Запрос должен быть JSON.');
  const data=method==='POST'?await body(req):{};let result:unknown;
  if(route==='/api/info'){let recent=[];try{recent=JSON.parse(await fs.readFile(path.join(this.root,'.shelter-cache/recent.json'),'utf8'));}catch{}result={recent,defaultDirectory:path.join(this.root,'projects'),example:path.join(this.root,'games/while-the-light-is-on'),version:'0.4'};}
  else if(route==='/api/browse'){const dir=path.resolve(data.path||url.searchParams.get('path')||path.join(os.homedir(),'Documents'));const entries=await fs.readdir(dir,{withFileTypes:true});result={path:dir,parent:path.dirname(dir),folders:entries.filter(e=>e.isDirectory()&&!e.name.startsWith('.')).map(e=>e.name),project:await exists(path.join(dir,'project.shelter.json'))};}
  else if(route==='/api/open'&&method==='POST'){result=await this.session(data.path.endsWith('project.shelter.json')?path.dirname(data.path):data.path);}
  else if(route==='/api/create'&&method==='POST'){
   if(!['empty-3d','neutral-25d','while-light'].includes(data.template)||typeof data.name!=='string'||!data.name.trim())throw new Error('Укажите название и шаблон проекта.');
   const parent=path.resolve(data.directory||path.join(this.root,'projects')),folder=data.name.trim().replace(/[<>:"/\\|?*\x00-\x1f]/g,'-');if(!folder||folder==='.'||folder==='..')throw new Error('Некорректное имя папки.');const dest=path.join(parent,folder);if(await exists(dest))throw new Error('Папка уже существует. Выберите другое название или расположение.');
   const staging=path.join(parent,'.shelter-create-'+randomUUID());await fs.mkdir(staging,{recursive:true});for(const dir of ['scenes','assets','prefabs','scripts','settings'])await fs.mkdir(path.join(staging,dir),{recursive:true});
   const snapshot=template(data.name.trim(),data.template);if(data.template==='while-light'){await fs.cp(path.join(this.root,'games/while-the-light-is-on/scripts'),path.join(staging,'scripts'),{recursive:true});await fs.cp(path.join(this.root,'games/while-the-light-is-on/assets'),path.join(staging,'assets'),{recursive:true});}
   await writeProject(staging,snapshot);await fs.rename(staging,dest);result=await this.session(dest);
  }
  else if(route==='/api/project-copy'&&method==='POST'){const root=this.project(data.token),snapshot=await readProject(root);const name=String(data.name||'').trim();if(!name||name.length>100)throw new Error('Укажите имя копии.');const destination=path.join(path.resolve(data.directory),name.replace(/[^\p{L}\p{N} _-]/gu,'-'));if(await exists(destination))throw new Error('Папка уже существует.');const files=await this.projectFiles(root,snapshot),stage=destination+'.copy-'+randomUUID();await fs.mkdir(stage,{recursive:true});snapshot.manifest.projectId=randomUUID();snapshot.manifest.name=name;snapshot.manifest.build.appId=snapshot.manifest.projectId;snapshot.manifest.build.output='';files.set('project.shelter.json',Buffer.from(json(snapshot.manifest)));for(const [file,bytes] of files)await atomic(await inside(stage,file),bytes);await readProject(stage);await fs.rename(stage,destination);result=await this.session(destination);}
  else if(route==='/api/save'&&method==='POST'){const root=this.project(data.token);await writeProject(root,data.snapshot,data.revision);result=await this.session(root);}
  else if(route==='/api/library'){const entries=await this.libraryEntries();result={entries};}
  else if(route==='/api/library-add'&&method==='POST'){const root=this.project(data.token);result=await locked('assets:'+root,async()=>{const snapshot=await readProject(root);if(revision(snapshot)!==data.revision)throw new Error('Проект изменён. Сначала сохраните или перечитайте его.');const entries=await this.libraryEntries(),asset=entries.find(a=>a.id===String(data.id).split('@')[0]&&(!String(data.id).includes('@')||a.version===String(data.id).split('@')[1]));if(!asset)throw new Error('Ресурс библиотеки отсутствует.');const existing=snapshot.manifest.assets.find(a=>a.source?.id===asset.id&&a.source.version===asset.version);if(existing)return this.session(root);const copy=structuredClone(asset);copy.source={id:asset.id,version:asset.version};if(snapshot.manifest.assets.some(a=>a.id===copy.id))copy.id=asset.id+'-v-'+asset.version.replace(/[^a-zA-Z0-9_-]/g,'-');const remap=(file:string)=>'assets/'+copy.id+'/'+file.slice(7);for(const file of [copy.path,...copy.dependencies])await atomic(await inside(root,remap(file)),await fs.readFile(await inside(this.library,file)));copy.path=remap(copy.path);copy.dependencies=copy.dependencies.map(remap);if(copy.maps)copy.maps=Object.fromEntries(Object.entries(copy.maps).map(([k,v])=>[k,remap(v)]));snapshot.manifest.assets.push(copy);await writeProject(root,snapshot,data.revision);return this.session(root);});}
  else if(route==='/api/composition'&&method==='POST'){const root=this.project(data.token),snapshot=await readProject(root),id='composition-'+randomUUID();if(revision(snapshot)!==data.revision)throw new Error('Проект изменился.');if(!Array.isArray(data.nodes)||!data.nodes.length)throw new Error('Выделение пусто.');const file='assets/'+id+'.json',text=json({version:1,nodes:data.nodes,groups:data.groups||[]});await atomic(await inside(root,file),text);snapshot.manifest.assets.push({id,name:data.name,type:'composition',path:file,dependencies:snapshot.manifest.assets.filter(a=>data.nodes.some((n:any)=>n.asset===a.id||n.surface?.texture==='asset:'+a.id)).flatMap(a=>[a.path,...a.dependencies]),bytes:Buffer.byteLength(text),version:'1.0.0',author:'Пользователь',license:'Проект',category:'Композиции',tags:[],description:'Независимые копии выбранных объектов'});await writeProject(root,snapshot,data.revision);result=await this.session(root);}
  else if(route==='/api/import'&&method==='POST'){const isLibrary=data.library===true,root=isLibrary?this.library:this.project(data.token);result=await this.importAsset(root,data,isLibrary);}
  else if(route==='/api/material'&&method==='POST'){if(!data.maps?.baseColor||![data.roughness,data.metalness].every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new Error('Проверьте карты и значения материала.');const files=new Map<string,Buffer>();let bytes=0;for(const file of data.files||[]){if(!portablePath(file.name)||!/\.(png|jpe?g|webp)$/i.test(file.name))throw new Error('Неподдерживаемая карта материала.');const b=Buffer.from(file.data,'base64');bytes+=b.length;if(b.length>64*1024*1024||bytes>128*1024*1024)throw new Error('Материал превышает бюджет 128 МБ.');files.set(file.name,b);}for(const [key,file] of Object.entries(data.maps))if(!['baseColor','normal','roughness','metalness','ao'].includes(key)||!files.has(String(file)))throw new Error('Карта материала отсутствует.');const id='material-'+randomUUID(),prefix='assets/'+id+'/',maps=Object.fromEntries(Object.entries(data.maps).map(([k,v])=>[k,prefix+v]));const a:AssetRecord={id,type:'material',name:String(data.name||'Материал').slice(0,100),path:prefix+'material.json',dependencies:[...files.keys()].map(f=>prefix+f),maps,bytes,version:'1.0.0',author:String(data.author||'Пользователь'),license:String(data.license||'Указана автором'),category:'Материалы',tags:[],description:'PBR-материал; отсутствующие каналы используют числовые значения.',surface:{texture:'asset:'+id,color:'#ffffff',roughness:data.roughness,metalness:data.metalness,repeat:1}};for(const [name,b] of files)await atomic(await inside(this.library,prefix+name),b);await atomic(await inside(this.library,a.path),json({maps,surface:a.surface}));const entries=await this.libraryEntries();entries.push(a);await atomic(path.join(this.library,'index.json'),json(entries));result={entries};}
  else if(route==='/api/library-meta'&&method==='POST'){const entries=await this.libraryEntries(),asset=entries.find(a=>a.id===String(data.id).split('@')[0]&&(!String(data.id).includes('@')||a.version===String(data.id).split('@')[1]));if(!asset)throw new Error('Ресурс не найден.');for(const field of ['name','description','category','author','license'])if(typeof data[field]==='string')(asset as any)[field]=data[field].slice(0,1000);if(Array.isArray(data.tags))asset.tags=data.tags.map(String).slice(0,30);await atomic(path.join(this.library,'index.json'),json(entries));result={entries};}
  else if(route==='/api/project-export'&&method==='POST'){const root=this.project(data.token),snapshot=await readProject(root),files=await this.projectFiles(root,snapshot),zip=pack(files);res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition','attachment; filename="project.shelter.zip"');res.end(zip);return;}
  else if(route==='/api/project-import'&&method==='POST'){const files=unpack(Buffer.from(data.archive,'base64')),manifest=files.get('project.shelter.json');if(!manifest)throw new Error('В архиве нет project.shelter.json.');const m=JSON.parse(manifest.toString()),scenes:Record<string,any>={};for(const s of m.scenes||[])scenes[s.id]=JSON.parse(files.get(s.path)?.toString()||'null');const snapshot=validateSnapshot({manifest:m,scenes});const folder=path.join(path.resolve(data.directory),snapshot.manifest.name.replace(/[^\p{L}\p{N} _-]/gu,'-'));if(await exists(folder))throw new Error('Папка уже существует.');const stage=folder+'.import-'+randomUUID();await fs.mkdir(stage,{recursive:true});for(const [name,b] of files){if(!portablePath(name)||!['project.shelter.json','scenes','assets','scripts','prefabs','settings'].some(p=>name===p||name.startsWith(p+'/')))throw new Error('Неизвестный путь в архиве.');await atomic(await inside(stage,name),b);}await readProject(stage);await fs.rename(stage,folder);result=await this.session(folder);}
  else if(route==='/api/library-export'&&method==='POST'){const entries=(await this.libraryEntries()).filter(e=>!data.id||e.id===String(data.id).split('@')[0]&&(!String(data.id).includes('@')||e.version===String(data.id).split('@')[1])),files=new Map<string,Buffer>([['library.json',Buffer.from(json(entries))]]);for(const a of entries)for(const file of [a.path,...a.dependencies])files.set(file,await fs.readFile(await inside(this.library,file)));res.setHeader('Content-Type','application/zip');res.end(pack(files));return;}
  else if(route==='/api/library-import'&&method==='POST'){const files=unpack(Buffer.from(data.archive,'base64')),entries=JSON.parse(files.get('library.json')?.toString()||'null') as AssetRecord[];if(!Array.isArray(entries))throw new Error('Нет каталога библиотеки.');const current=await this.libraryEntries();for(const a of entries){if(!portablePath(a.path)||!a.path.startsWith('assets/')||!Array.isArray(a.dependencies)||[a.path,...a.dependencies].some(p=>!portablePath(p)||!p.startsWith('assets/')||!files.has(p)))throw new Error('Неполный пакет библиотеки.');if(current.some(c=>c.id===a.id&&c.version===a.version))continue;for(const file of [a.path,...a.dependencies]){const dest=await inside(this.library,file);if(await exists(dest)&&!(await fs.readFile(dest)).equals(files.get(file)!))throw new Error('Конфликт версии ресурса. Импортируйте с новым ID.');await atomic(dest,files.get(file)!);}current.push(a);}await atomic(path.join(this.library,'index.json'),json(current));result={entries:current};}
  else if(route==='/api/usage'&&method==='POST'){result=await syncUsage(this.root,this.project(data.token));}
  else if(route==='/api/publish-info'&&method==='POST'){result=await this.publisher.info(this.project(data.token));}
  else if(route==='/api/publish'&&method==='POST'){const root=this.project(data.token),snapshot=await readProject(root);if(revision(snapshot)!==data.revision)throw new Error('Проект изменился. Сохраните актуальную сцену перед публикацией.');result=await this.publisher.start(root,snapshot,data.repository,data.githubToken);}
  else if(route==='/api/publish-status'&&method==='POST'){result=this.publisher.status(data.id,this.project(data.token));}
  else if(route==='/api/build'&&method==='POST'){const root=this.project(data.token),snapshot=await readProject(root);if(revision(snapshot)!==data.revision)throw new Error('Сохранение проекта изменилось. Сначала сохраните актуальную сцену.');result=await startBuild(this.root,root,snapshot);}
  else if(route==='/api/build-status'){const id=url.searchParams.get('id')!,b=builds.get(id);if(!b)throw new Error('Сборка не найдена.');result=b;}
  else if(route==='/api/build-cancel'&&method==='POST'){const b=builds.get(data.id);if(b?.status==='running'){b.status='cancelled';b.stage='Отменено';}result=b;}
  else if(route==='/api/build-preview'&&method==='POST'){const b=builds.get(data.id);if(b?.status!=='success'||!b.output)throw new Error('Готовой сборки ещё нет.');if(b.preview){result=b;}else{const root=b.output,report=JSON.parse(await fs.readFile(path.join(root,'build-report.json'),'utf8')),base=report.base==='./'?'/':report.base;const server=createServer((r,s)=>{const pathname=new URL(r.url!,'http://localhost').pathname;if(!pathname.startsWith(base)){s.writeHead(404);s.end();return;}const relative=decodeURIComponent(pathname.slice(base.length))||'index.html';void inside(root,relative).then(p=>this.sendFile(s,p)).catch(()=>{s.writeHead(404);s.end('Not found');});});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as {port:number};b.preview=`http://127.0.0.1:${address.port}${base}`;this.previews.set(data.id,server);result=b;}}
  else if(route==='/api/build-download'){const b=builds.get(url.searchParams.get('id')!);if(b?.status!=='success'||!b.archive)throw new Error('Архив ещё не готов.');res.setHeader('Content-Disposition','attachment; filename="game-web.zip"');return this.sendFile(res,b.archive);}
  else if(route==='/api/build-folder'&&method==='POST'){const b=builds.get(data.id);if(b?.status!=='success'||!b.output)throw new Error('Результат не найден.');const {spawn}=await import('node:child_process');spawn(process.platform==='darwin'?'open':process.platform==='win32'?'explorer':'xdg-open',[b.output],{stdio:'ignore'}).unref();result={ok:true};}
  else throw new Error('Неизвестная команда службы.');
  res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(json(result));
 }
 async libraryEntries():Promise<AssetRecord[]>{try{return JSON.parse(await fs.readFile(path.join(this.library,'index.json'),'utf8'));}catch{return [];}}
 async importAsset(root:string,data:any,isLibrary:boolean){
  return locked('assets:'+root,async()=>{await fs.mkdir(root,{recursive:true});const snapshot=isLibrary?undefined:await readProject(root);if(snapshot&&revision(snapshot)!==data.revision)throw new Error('Проект изменился: сохраните его перед импортом.');
  if(!Array.isArray(data.files)||!data.files.length||data.files.length>100)throw new Error('Выберите модель и связанные файлы.');const files=new Map<string,Buffer>();let bytes=0;for(const f of data.files){if(!portablePath(f.name))throw new Error('Недопустимое имя файла.');const content=Buffer.from(f.data,'base64');bytes+=content.length;if(content.length>64*1024*1024||bytes>128*1024*1024)throw new Error('Лимит импорта: 64 МБ на файл, 128 МБ на комплект.');files.set(f.name,content);}
  const main=data.main||data.files.find((f:any)=>/\.(glb|gltf|png|jpe?g|webp)$/i.test(f.name))?.name;if(!main||!files.has(main))throw new Error('Выберите GLB, glTF, PNG, JPEG или WebP.');
  const model=/\.(glb|gltf)$/i.test(main),metadata=model?inspectGLTF(files.get(main)!,main,new Set(files.keys())):{dependencies:[],triangles:0};if(!model&&!/\.(png|jpe?g|webp)$/i.test(main))throw new Error('Неизвестный формат.');
  if(typeof data.unitScale!=='number'||!Number.isFinite(data.unitScale)||data.unitScale<=0||data.unitScale>1000)throw new Error('Некорректный масштаб единиц.');
  const hash=createHash('sha256');for(const [name,b] of [...files].sort())hash.update(name).update(b);hash.update(String(data.unitScale));const id='asset-'+hash.digest('hex').slice(0,20),prefix='assets/'+id+'/';
  const list=isLibrary?await this.libraryEntries():snapshot!.manifest.assets;const existing=list.find(a=>a.id===id);if(existing)return isLibrary?{entries:list}:this.session(root);
  const asset:AssetRecord={id,name:data.name||path.basename(main),type:model?'model':'texture',path:prefix+main,dependencies:metadata.dependencies.map(p=>prefix+p),bytes,version:'1.0.0',author:data.author||'Пользователь',license:data.license||'Указана автором ресурса',category:model?'Модели':'Текстуры',tags:[],description:'Импортированный локальный ресурс',unitScale:data.unitScale,triangles:metadata.triangles,dimensions:Array.isArray(data.dimensions)?data.dimensions.map((n:number)=>n*data.unitScale):undefined};
  // Validate all input before committing any registry entry; abandoned originals are harmless.
  for(const [name,b] of files)await atomic(await inside(root,prefix+name),b);list.push(asset);
  if(isLibrary){await atomic(path.join(root,'index.json'),json(list));return {entries:list};}
  await writeProject(root,snapshot!,data.revision);return this.session(root);
 });}
 async projectFiles(root:string,snapshot:ProjectSnapshot){const files=new Map<string,Buffer>([['project.shelter.json',Buffer.from(json(snapshot.manifest))]]);for(const s of snapshot.manifest.scenes)files.set(s.path,Buffer.from(json(snapshot.scenes[s.id])));for(const a of snapshot.manifest.assets)for(const file of [a.path,...a.dependencies])files.set(file,await fs.readFile(await inside(root,file)));for(const dir of ['scripts','prefabs'])if(await exists(path.join(root,dir)))for(const [file,b] of await filesUnder(root,dir))files.set(file,b);for(const mod of snapshot.manifest.modules)for(const dir of mod.assets||[])for(const [file,b] of await filesUnder(await inside(root,dir)))files.set(dir+'/'+file,b);return files;}
}
