import type {EngineModule,SessionOptions,RuntimeSession} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {World,readMap,TOWERS,ENEMIES,wavePlan,type TowerKind} from './world.ts';
import {Renderer} from './renderer.ts';
import {Sound} from './audio.ts';
const kinds=Object.keys(TOWERS) as TowerKind[];
const icon=(s:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${s}</svg>`;
const icons={sun:icon('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>'),arrow:icon('<path d="M4 12h16m-6-6 6 6-6 6"/>'),shield:icon('<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/>'),coin:icon('<circle cx="12" cy="12" r="8"/><path d="m12 7 4 5-4 5-4-5Z"/>'),flag:icon('<path d="M5 22V3m0 1c5-5 9 5 14 0v11c-5 5-9-5-14 0"/>'),pause:icon('<path d="M8 5v14m8-14v14"/>'),sound:icon('<path d="M4 9h4l5-5v16l-5-5H4Zm13-1c3 2 3 6 0 8m3-11c5 4 5 10 0 14"/>'),map:icon('<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16"/>')};
const stars=(n:number)=>'★'.repeat(n)+'☆'.repeat(3-n);
export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');const root=options.container,oldTitle=document.title;document.title='Караван · Пески рассвета';root.classList.add('caravan-root');
 const favicon=document.createElement('link');favicon.rel='icon';favicon.href='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="%23367f79"/><circle cx="32" cy="32" r="12" fill="%23f3d49b"/><path d="M32 8v7m0 34v7M8 32h7m34 0h7M15 15l5 5m24 24 5 5M15 49l5-5m24-24 5-5" stroke="%23f3d49b" stroke-width="3"/></svg>'.replaceAll('%23','#'));document.head.append(favicon);
 const maps=options.snapshot.manifest.scenes.map(s=>readMap(options.snapshot.scenes[s.id]));const saveKey=storageKey(options.snapshot.manifest.projectId,'progress',options.snapshot.manifest.build.appId);const sound=new Sound();const completed=maps.map(()=>0);
 let mapIndex=0,active=false,paused=false,externalPaused=false,disposed=false,speed=1,selected=-1,buildKind:TowerKind|null='arrow',resultShown=false,saveOK=true;
 if(options.savePolicy==='persistent')try{const data=JSON.parse(localStorage.getItem(saveKey)||'null');if(data?.version===1&&Array.isArray(data.stars)&&data.stars.length===maps.length&&data.stars.every((n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<=3)){completed.splice(0,completed.length,...data.stars);mapIndex=Math.min(Math.max(0,Number.isInteger(data.map)?data.map:0),Math.max(0,completed.findIndex(n=>!n)<0?maps.length-1:completed.findIndex(n=>!n)));sound.muted=!!data.muted;}}catch{}
 let world=new World(maps[mapIndex]);
 root.innerHTML=`<header class="cv-header"><button class="cv-brand" data-action="home" aria-label="Караван — главное меню">${icons.sun}<span>КАРАВАН<small>ПЕСКИ РАССВЕТА</small></span></button><span class="cv-header-note">КАЖДОМУ ПУТИ НУЖЕН ЗАЩИТНИК</span><nav aria-label="Настройки"><button class="cv-icon" data-action="sound" aria-label="Звук">${icons.sound}</button><button class="cv-icon" data-action="help" aria-label="Как играть">?</button><button class="cv-icon" data-action="pause" aria-label="Пауза">${icons.pause}</button></nav></header>
 <div class="cv-main"><section class="cv-intro"><div class="cv-kicker"><span></span> СТРАТЕГИЯ ЗАЩИТЫ ПУТИ</div><h1>Пока караван<br>идёт <em>вперёд.</em></h1><p>Среди песков просыпаются древние стражи.<br>Постройте башни. Удержите путь.<br>Встретьте рассвет у ворот оазиса.</p><button class="cv-primary" data-action="start">Начать путешествие ${icons.arrow}</button><button class="cv-text-button" data-action="maps">${icons.map} Карта путешествия</button><div class="cv-intro-facts"><div><b>03</b><span>КАРТЫ</span></div><div><b>04</b><span>ТИПА БАШЕН</span></div><div><b>30</b><span>ВОЛН</span></div></div></section>
 <section class="cv-battle" aria-label="Поле боя"><div class="cv-map-heading"><div><span class="cv-kicker" data-map-number>01 / ПЕРВАЯ СТОЯНКА</span><h2 data-map-name>Лазурный оазис</h2></div><div class="cv-map-badge">${icons.flag}<span data-phase>ПУТЬ ЧЕРЕЗ ПУСТЫНЮ</span></div></div>
 <div class="cv-hud" hidden><div>${icons.shield}<strong data-health>20</strong><span>ВОРОТА</span></div><div>${icons.coin}<strong data-coins>260</strong><span>МОНЕТЫ</span></div><div>${icons.flag}<strong data-wave>0 / 10</strong><span>ВОЛНА</span></div><button class="cv-speed" data-action="speed" aria-label="Скорость игры">1×</button></div>
 <div class="cv-field"><canvas aria-label="Караванный путь в пустыне. Площадки для башен доступны кнопками поверх поля."></canvas><div class="cv-slots" role="group" aria-label="Площадки для башен"></div><div class="cv-corner cv-corner-tl"></div><div class="cv-corner cv-corner-br"></div><div class="cv-preview-label"><span class="cv-live-dot"></span> ЛАЗУРНЫЙ ОАЗИС <span>01 / 03</span></div><div class="cv-paused" hidden><span>Ⅱ</span>ПУТЬ ПОДОЖДЁТ<button data-action="resume">Продолжить</button></div></div>
 <div class="cv-under"><span><i></i> <span data-hint>Маленькие башни. Большое путешествие.</span></span><span>ЭКСПЕДИЦИЯ № 01</span></div>
 <div class="cv-context" hidden></div></section>
 <aside class="cv-sidebar" hidden><div class="cv-sidebar-heading"><span class="cv-kicker">ВАШ РУБЕЖ</span><h2>Постройте защиту</h2><p>Выберите башню, затем площадку <b>+</b></p></div><div class="cv-shop">${kinds.map((kind,i)=>{const t=TOWERS[kind];return `<button class="cv-tower-card" data-kind="${kind}" aria-pressed="false"><span class="cv-tower-icon" style="--tower-color:${t.color}">${t.icon}</span><span class="cv-tower-copy"><small>${t.caption}</small><b>${t.name}</b><span><i>${i+1}</i> ${t.cost} монет</span></span></button>`;}).join('')}</div><button class="cv-pulse" data-action="pulse">${icons.sun}<span><b>Солнечный импульс</b><small data-pulse>Вся сила рассвета · E</small></span></button><div class="cv-wave-preview"><span class="cv-kicker" data-next-label>СЛЕДУЮЩАЯ ВОЛНА</span><p data-next-enemies></p></div><button class="cv-primary cv-send" data-action="wave">Отправить волну ${icons.arrow}</button><p class="cv-key-note">Пробел — волна · P — пауза · 1–4 — башни</p></aside></div>
 <footer class="cv-footer"><span>SHELTER ENGINE <i>/</i> CARAVAN</span><span data-save>ПРОЙДЕННЫЕ КАРТЫ СОХРАНЯЮТСЯ</span><span>ПО ПЕСЧАНОМУ МОРЮ — К РАССВЕТУ</span></footer><div class="cv-toast" role="status" aria-live="polite"></div><dialog class="cv-dialog" aria-labelledby="cv-dialog-title"><div class="cv-dialog-inner"></div></dialog>`;
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const canvas=$<HTMLCanvasElement>('canvas'),renderer=new Renderer(canvas,world),modal=$<HTMLDialogElement>('dialog'),abort=new AbortController();renderer.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
 const save=()=>{if(options.savePolicy!=='persistent')return;try{localStorage.setItem(saveKey,JSON.stringify({version:1,map:mapIndex,stars:completed,muted:sound.muted}));}catch{saveOK=false;$('[data-save]').textContent='БРАУЗЕР НЕ РАЗРЕШИЛ СОХРАНЕНИЕ';}};
 let toastTimer:ReturnType<typeof setTimeout>|undefined,lastFocus:HTMLElement|null=null;
 const toast=(message:string)=>{$('.cv-toast').textContent=message;$('.cv-toast').classList.add('shown');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.cv-toast').classList.remove('shown'),3500);};
 const close=()=>{if(modal.open)modal.close();lastFocus?.focus({preventScroll:true});};
 const show=(html:string)=>{if(!modal.open)lastFocus=document.activeElement as HTMLElement;$('.cv-dialog-inner').innerHTML=html;if(!modal.open)modal.showModal();};
 const isPaused=()=>paused||externalPaused||modal.open;
 const unlocked=()=>{const i=completed.findIndex(s=>!s);return i<0?maps.length-1:i;};
 const mapHeading=()=>{$('[data-map-name]').textContent=maps[mapIndex].name;$('[data-map-number]').textContent=`0${mapIndex+1} / ${maps[mapIndex].subtitle.toUpperCase()}`;$('.cv-under > span:last-child').textContent=`ЭКСПЕДИЦИЯ № 0${mapIndex+1}`;};
 const soundUI=()=>{const b=$('[data-action="sound"]');b.classList.toggle('muted',sound.muted);b.setAttribute('aria-label',sound.muted?'Включить звук':'Выключить звук');b.setAttribute('aria-pressed',String(!sound.muted));};soundUI();
 const slotsUI=()=>{$('.cv-slots').innerHTML=world.map.slots.map(([x,y],i)=>`<button class="cv-slot" data-slot="${i}" style="left:${x/11}%;top:${y/6.8}%" aria-label="Площадка ${i+1}"><span>${i+1}</span></button>`).join('');};
 const updateContext=()=>{const t=world.tower(selected);renderer.selected=selected;renderer.ghost=buildKind;root.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(b=>{b.classList.toggle('selected',b.dataset.kind===buildKind);b.setAttribute('aria-pressed',String(b.dataset.kind===buildKind));});
 if(t){const s=world.stats(t);$('.cv-context').innerHTML=`<span class="cv-selected-icon" style="color:${TOWERS[t.kind].color}">${TOWERS[t.kind].icon}</span><div class="cv-context-copy"><small>ПЛОЩАДКА ${selected+1} · УРОВЕНЬ ${t.level} / 3</small><b>${TOWERS[t.kind].name}</b><span>Урон ${Math.round(s.damage)} · Радиус ${s.range} · Уничтожено ${t.kills}</span></div><div class="cv-context-actions"><button class="cv-upgrade" data-action="upgrade" ${t.level>=3?'disabled':''}>${t.level>=3?'Макс. уровень':`Улучшить · ${world.upgradeCost(t)} ◇`}</button><button class="cv-sell" data-action="sell">Продать · ${Math.floor(t.spent*.7)} ◇</button></div>`;}
 else{const s=buildKind?TOWERS[buildKind]:null;$('.cv-context').innerHTML=`<span class="cv-selected-icon">${s?.icon||'+'}</span><div class="cv-context-copy"><small>${s?s.caption:'МЕСТО ДЛЯ НОВОЙ БАШНИ'}</small><b>${s?s.name:'Постройте рубеж'}</b><span>${s?s.description:'Выберите башню справа, затем нажмите на свободную площадку.'}</span></div>`;}
 world.map.slots.forEach((_,i)=>{const t=world.tower(i),b=$<HTMLButtonElement>(`[data-slot="${i}"]`);b.classList.toggle('occupied',!!t);b.setAttribute('aria-label',t?`Площадка ${i+1}: ${TOWERS[t.kind].name}, уровень ${t.level}`:`Площадка ${i+1}: построить ${buildKind?TOWERS[buildKind].name:'башню'}`);});};
 const hud=()=>{if(!active)return;$('[data-health]').textContent=String(world.health);$('[data-coins]').textContent=String(world.coins);$('[data-wave]').textContent=`${world.wave} / ${world.map.waves}`;$('[data-phase]').textContent=world.active?'КАРАВАН ПОД ЗАЩИТОЙ':'ВРЕМЯ ПОДГОТОВИТЬСЯ';
 const button=$<HTMLButtonElement>('[data-action="wave"]');button.disabled=world.active||world.status!=='playing';button.innerHTML=world.active?`В пути: ${world.enemies.length+world.queue.length}`:`Волна ${world.wave+1} ${icons.arrow}`;
 const pulse=$<HTMLButtonElement>('[data-action="pulse"]');pulse.disabled=!world.active||world.pulseCooldown>0;$('[data-pulse]').textContent=world.pulseCooldown>0?`Зарядится через ${Math.ceil(world.pulseCooldown)} с`:'Урон и замедление всем врагам · E';
 const upgrade=root.querySelector<HTMLButtonElement>('[data-action="upgrade"]'),t=world.tower(selected);if(upgrade&&t)upgrade.disabled=t.level>=3||world.coins<world.upgradeCost(t);
 root.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(b=>b.classList.toggle('unaffordable',world.coins<TOWERS[b.dataset.kind as TowerKind].cost));
 $('[data-hint]').textContent=world.active?'Стройте и улучшайте башни прямо во время боя.':world.wave===0?'Постройте башни на площадках +, затем отправьте волну.':`Волна ${world.wave} пройдена. Усильте защиту перед следующей.`;
 const n=Math.min(world.wave+(world.active?0:1),world.map.waves),counts=new Map<string,number>();for(const e of wavePlan(n)){const name=ENEMIES[e.kind].name;counts.set(name,(counts.get(name)||0)+1);}$('[data-next-label]').textContent=world.active?'ЭТА ВОЛНА':`СЛЕДУЮЩАЯ ВОЛНА · ${n}`;$('[data-next-enemies]').textContent=[...counts].map(([name,count])=>`${name} ×${count}`).join(' · ');
 };
 const demo=()=>{world=new World(maps[0]);world.coins=3000;for(const [slot,kind] of [[0,'arrow'],[2,'mortar'],[3,'frost'],[5,'sun'],[7,'arrow']] as [number,TowerKind][]){world.build(slot,kind);world.upgrade(slot);}world.wave=3;world.startWave();for(let i=0;i<100;i++)world.tick(.1);world.events=[];renderer.setWorld(world);mapIndex=0;mapHeading();slotsUI();};
 const begin=(index:number)=>{close();mapIndex=index;world=new World(maps[index]);renderer.setWorld(world);renderer.selected=-1;active=true;paused=false;speed=1;selected=-1;buildKind='arrow';resultShown=false;root.classList.add('is-playing');$('.cv-intro').hidden=true;$('.cv-sidebar').hidden=false;$('.cv-hud').hidden=false;$('.cv-context').hidden=false;$('.cv-preview-label').hidden=true;$('.cv-slots').hidden=false;$('.cv-paused').hidden=true;$('[data-action="speed"]').textContent='1×';mapHeading();slotsUI();updateContext();hud();save();};
 const menu=()=>{close();active=false;paused=false;root.classList.remove('is-playing');$('.cv-intro').hidden=false;$('.cv-sidebar').hidden=true;$('.cv-hud').hidden=true;$('.cv-context').hidden=true;$('.cv-preview-label').hidden=false;$('.cv-slots').hidden=true;$('.cv-paused').hidden=true;renderer.selected=-1;demo();};
 const chooseMaps=()=>show(`<div class="cv-kicker">ПУТЕШЕСТВИЕ ЧЕРЕЗ ПЕСКИ</div><h2 id="cv-dialog-title">От оазиса к рассвету.</h2><p class="cv-dialog-lead">Завершите карту, чтобы открыть следующую. Три звезды — если все 20 очков ворот сохранены.</p><div class="cv-map-list">${maps.map((m,i)=>`<button data-map="${i}" ${i>unlocked()?'disabled':''}><span>0${i+1}</span><div><small>${m.subtitle.toUpperCase()}</small><b>${m.name}</b><p>${m.description}</p></div><em>${i>unlocked()?'ЗАКРЫТО':stars(completed[i])}</em></button>`).join('')}</div>${active&&world.status==='playing'?'<p class="cv-dialog-note">Выбор карты начнёт новый бой. Пройденные карты сохранятся.</p>':''}<button class="cv-primary" data-action="close">${active?'Вернуться к бою':'Закрыть карту'}</button>`);
 const help=()=>show(`<div class="cv-kicker">ПОЛЕВОЙ СПРАВОЧНИК</div><h2 id="cv-dialog-title">Удержите путь.</h2><div class="cv-help"><p><b>01. Постройте</b>Выберите одну из четырёх башен и нажмите на площадку +. Круг показывает дальность. Башни стреляют сами по ближайшему к воротам врагу.</p><p><b>02. Удержите</b>Нажмите «Волна». Скарабеи идут к воротам. За уничтоженных врагов вы получаете монеты. После каждой волны — награда и время на подготовку.</p><p><b>03. Усильте</b>Нажмите на построенную башню, чтобы улучшить её до третьего уровня или продать за 70% вложений. Мортиры бьют по группе, кристаллы замедляют, обелиски игнорируют броню.</p><p><b>04. Призовите рассвет</b>Солнечный импульс наносит урон всем врагам и замедляет их. Перезарядка — 32 игровые секунды. На десятой волне приходит страж дюн.</p></div><p class="cv-dialog-note">Не пропустите врагов через ворота: скарабей и бегун забирают 1 очко, панцирник — 2, страж — 8. Победа — после 10 волн. ★★★ за 20 очков, ★★ за 12–19, ★ за 1–11.</p><p class="cv-dialog-note">1–4 — башни · Пробел — следующая волна · E — импульс<br>P — пауза · F — скорость · M — звук · Esc — меню<br>На телефоне все действия доступны касанием.</p><button class="cv-primary" data-action="close">Путь понятен ${icons.arrow}</button>`);
 const pauseMenu=()=>{if(!active){chooseMaps();return;}show(`<div class="cv-kicker">ОСТАНОВКА В ПУТИ</div><h2 id="cv-dialog-title">Пески подождут.</h2><p class="cv-dialog-lead">${maps[mapIndex].name} · Волна ${world.wave} из ${world.map.waves}</p><div class="cv-menu-actions"><button class="cv-primary" data-action="close">Продолжить ${icons.arrow}</button><button class="cv-secondary" data-action="maps">Карта путешествия</button><button class="cv-secondary" data-action="retry-confirm">Начать карту сначала</button><button class="cv-text-button" data-action="exit-confirm">Главное меню</button></div>`);};
 const confirmExit=(action:string)=>show(`<div class="cv-kicker">НОВЫЙ МАРШРУТ</div><h2 id="cv-dialog-title">Завершить этот бой?</h2><p class="cv-dialog-lead">Текущие башни и волны будут сброшены. Звёзды за пройденные карты останутся.</p><div class="cv-menu-actions"><button class="cv-primary" data-action="${action}">${action==='retry'?'Начать сначала':'В главное меню'}</button><button class="cv-secondary" data-action="close">Вернуться к бою</button></div>`);
 const result=()=>{if(resultShown)return;resultShown=true;const won=world.status==='won';if(won){completed[mapIndex]=Math.max(completed[mapIndex],world.stars());save();}show(`<div class="cv-kicker">${won?'КАРАВАН ДОБРАЛСЯ ДО ВОРОТ':'ПЕСКИ ОКАЗАЛИСЬ СИЛЬНЕЕ'}</div><h2 id="cv-dialog-title">${won?(mapIndex===2?'Рассвет встречен.':'Путь сохранён.'):'Новый план. Новый шанс.'}</h2>${won?`<div class="cv-result-stars" aria-label="Звёзд: ${world.stars()}">${stars(world.stars())}</div>`:''}<p class="cv-dialog-lead">${won?'Путники в безопасности. '+(mapIndex<2?'Впереди следующий переход.':'Все три перехода пройдены. Можно вернуться за девятью звёздами.'): 'Сочетайте замедление с мортирами, улучшайте башни на поворотах и используйте солнечный импульс.'}</p><div class="cv-result-stats"><div><b>${world.health}/20</b><span>ВОРОТА</span></div><div><b>${world.kills}</b><span>ПОБЕЖДЕНО</span></div><div><b>${world.waveCleared}/10</b><span>ВОЛН ПРОЙДЕНО</span></div></div><div class="cv-menu-actions"><button class="cv-primary" data-action="${won&&mapIndex<2?'next':'retry'}">${won&&mapIndex<2?'Следующий переход':'Пройти ещё раз'} ${icons.arrow}</button><button class="cv-secondary" data-action="maps">Карта путешествия</button></div>`);};
 const selectSlot=(slot:number)=>{if(!active||isPaused()||world.status!=='playing')return;selected=slot;const t=world.tower(slot);if(t){buildKind=null;sound.play('click');}else if(buildKind){if(!world.build(slot,buildKind))toast('Не хватает монет. Побеждайте врагов и проходите волны.');else buildKind=null;}updateContext();hud();};
 root.addEventListener('click',async event=>{const target=(event.target as HTMLElement).closest<HTMLElement>('button');if(!target||target.hasAttribute('disabled'))return;await sound.unlock();const action=target.dataset.action;if(target.dataset.slot!==undefined){selectSlot(Number(target.dataset.slot));return;}if(target.dataset.kind){if(isPaused())return;buildKind=target.dataset.kind as TowerKind;selected=-1;updateContext();sound.play('click');return;}if(target.dataset.map!==undefined){const i=Number(target.dataset.map);if(i<=unlocked())begin(i);return;}
 if(action==='start')begin(unlocked());else if(action==='sound'){sound.muted=!sound.muted;soundUI();save();}else if(action==='help')help();else if(action==='maps')chooseMaps();else if(action==='close')close();else if(action==='pause')pauseMenu();else if(action==='home')active?pauseMenu():menu();else if(action==='menu')menu();else if(action==='exit-confirm')confirmExit('menu');else if(action==='retry-confirm')confirmExit('retry');else if(action==='retry')begin(mapIndex);else if(action==='next')begin(Math.min(mapIndex+1,maps.length-1));else if(action==='resume'){paused=false;$('.cv-paused').hidden=true;}else if(active&&!isPaused()){
 if(action==='wave'){if(world.towers.length===0){toast('Сначала постройте хотя бы одну башню на площадке +.');return;}world.startWave();}else if(action==='speed'){speed=speed===1?2:1;target.textContent=speed+'×';}else if(action==='pulse')world.pulse();else if(action==='upgrade'){world.upgrade(selected);updateContext();}else if(action==='sell'){world.sell(selected);buildKind='arrow';updateContext();}hud();}
 },{signal:abort.signal});
 canvas.addEventListener('pointermove',e=>{canvas.style.cursor=active&&renderer.hit(e.clientX,e.clientY)>=0?'pointer':'default';},{signal:abort.signal});
 canvas.addEventListener('click',e=>{const slot=renderer.hit(e.clientX,e.clientY);if(slot>=0)selectSlot(slot);},{signal:abort.signal});
 const togglePause=()=>{if(!active||modal.open||world.status!=='playing')return;paused=!paused;$('.cv-paused').hidden=!paused;};
 window.addEventListener('keydown',event=>{if(event.repeat||event.ctrlKey||event.metaKey||event.altKey)return;const k=event.key.toLowerCase();if(modal.open)return;if(event.code==='Space'&&((event.target as HTMLElement).tagName==='BUTTON'))return;const action=k==='m'?'sound':k==='e'?'pulse':k==='f'?'speed':event.code==='Space'?'wave':k==='escape'?'pause':null;if(k==='p'){event.preventDefault();togglePause();return;}if(action){event.preventDefault();$<HTMLButtonElement>(`[data-action="${action}"]`).click();return;}if(active&&!isPaused()&&/^[1-4]$/.test(k)){$<HTMLButtonElement>(`[data-kind="${kinds[Number(k)-1]}"]`).click();}},{signal:abort.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&world.status==='playing'){paused=true;$('.cv-paused').hidden=false;}},{signal:abort.signal});
 modal.addEventListener('cancel',event=>{if(world.status!=='playing'&&active){event.preventDefault();return;}},{signal:abort.signal});
 menu();let frame=0,last=performance.now(),uiTime=0,demoClock=0;const loop=(now:number)=>{if(disposed)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(!active){demoClock+=dt;if(renderer.motion)world.tick(dt*.6);if(demoClock>65||world.status!=='playing'){demoClock=0;demo();}world.events=[];}else if(!isPaused()){for(let i=0;i<speed;i++)world.tick(dt);for(const event of world.events){sound.play(event);if(event==='clear')toast(`Волна ${world.wave} пройдена · +${40+world.wave*6} монет`);}world.events=[];if(world.status!=='playing')result();uiTime+=dt;if(uiTime>.12){uiTime=0;hud();}}renderer.draw(world.time);frame=requestAnimationFrame(loop);};frame=requestAnimationFrame(loop);
 return {pause(value){externalPaused=value;},dispose(){disposed=true;cancelAnimationFrame(frame);abort.abort();if(toastTimer)clearTimeout(toastTimer);if(modal.open)modal.close();sound.dispose();favicon.remove();root.replaceChildren();root.classList.remove('caravan-root','is-playing');document.title=oldTitle;},diagnostics(){return {game:'caravan',map:maps[mapIndex].id,active,paused:isPaused(),wave:world.wave,health:world.health,coins:world.coins,towers:world.towers.length,enemies:world.enemies.length,status:world.status,stars:completed,saveOK};}};
}
const module:EngineModule={id:'caravan',sdk:1,validateScene(scene){readMap(scene);},createSession:startGame};export default module;
