import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validateScene} from '../../src/engine/scene.ts';
import {World,readLevel,difficulty,distance,segmentRect,type Controls,type Kind} from '../../games/bastion/scripts/world.ts';
const scene=validateScene(JSON.parse(readFileSync(new URL('../../games/bastion/scenes/castle.scene.json',import.meta.url),'utf8')));
const level=readLevel(scene);
const empty:Controls={x:0,y:0,angle:-Math.PI/2,fire:false,dash:false,nova:false,interact:false,weapon:-1};
const make=()=>{const w=new World(level);w.reset();w.enemies=[];w.spawnClock=999;return w;};
const step=(w:World,t:number,input:Partial<Controls>={})=>{for(let i=0;i<Math.ceil(t*120);i++)w.step(1/120,{...empty,...input});};
function enemy(w:World,x:number,y:number,kind:Kind='skeleton'){const e=w.spawn(kind,{x,y})!;e.birth=0;e.speed=0;e.attack=999;return e;}
test('native scene contains one fortress, eight invasion gates and four usable stations',()=>{assert.equal(level.gates.length,8);assert.equal(level.stations.length,4);assert.ok(level.cover.length>30);const w=make();for(const p of [level.spawn,...level.gates,...level.stations])assert.equal(w.blocked(p.x,p.y,38),false,JSON.stringify(p));});
test('all gates and resource stations are connected to the player with boss-sized clearance',()=>{const w=make();w.buildNav();for(const p of [...level.gates,...level.stations])assert.ok(w.nav.has(`${Math.floor(p.x/40)},${Math.floor(p.y/40)}`),JSON.stringify(p));});
test('enemies navigate around the chapel and cloister rather than getting trapped',()=>{for(const g of level.gates){const w=make();w.player.invincible=999;const e=w.spawn('skeleton',g)!;for(let i=0;i<45*60&&distance(e,w.player)>75;i++)w.step(1/60,empty);assert.ok(distance(e,w.player)<75,`Gate ${g.x},${g.y}: ${Math.round(distance(e,w.player))}`);}});
test('movement normalizes diagonal input and dash cannot tunnel through walls',()=>{const a=make(),b=make();step(a,.2,{x:1});step(b,.2,{x:1,y:1});assert.ok(Math.abs(distance(a.player,level.spawn)-distance(b.player,level.spawn))<.1);const r=level.cover[0];a.player.x=r.x;a.player.y=r.y+100;step(a,.2,{y:-1,dash:true});assert.ok(a.player.y>=r.y+r.h/2+18);});
test('sword has an aimed arc, third-hit cleave and restores mana on hits',()=>{const w=make();w.player.mana=0;const front=enemy(w,w.player.x,w.player.y-80,'guard'),behind=enemy(w,w.player.x,w.player.y+70);front.angle=Math.PI/2;w.attack();assert.ok(front.hp<front.maxHP);assert.equal(behind.hp,behind.maxHP);assert.equal(w.player.mana,3);w.player.cooldown=0;w.attack();w.player.cooldown=0;const hp=front.hp;w.attack();assert.ok(hp-front.hp>=66);assert.equal(w.player.combo,2);});
test('arrows pierce two enemies and spend ammunition',()=>{const w=make();w.player.weapon=1;const a=enemy(w,1200,1050),b=enemy(w,1200,990);step(w,.2,{fire:true});assert.equal(w.player.arrows,47);assert.ok(a.hp<a.maxHP);assert.ok(b.hp<b.maxHP);});
test('arrows and sword cannot hit through a solid wall',()=>{const w=make(),r=level.cover[0];w.player.x=r.x;w.player.y=r.y+75;const e=enemy(w,r.x,r.y-75);w.attack();assert.equal(e.hp,e.maxHP);w.player.cooldown=0;w.player.weapon=1;step(w,.5,{fire:true});assert.equal(e.hp,e.maxHP);assert.ok(segmentRect(w.player,e,r)<1);});
test('fire staff damages groups and costs mana; regenerating mana avoids a dead end',()=>{const w=make();w.player.weapon=2;const a=enemy(w,1200,1040),b=enemy(w,1250,1035);step(w,.23,{fire:true});assert.ok(a.hp<a.maxHP&&b.hp<b.maxHP);assert.ok(w.player.mana<86);w.player.mana=0;w.player.cooldown=0;w.attack();assert.equal(w.bullets.length,0);step(w,4);assert.ok(w.player.mana>=16);});
test('ice ring slows enemies, clears hostile missiles, and respects cooldown',()=>{const w=make(),e=enemy(w,1260,1130,'guard');w.bullets.push({id:999,x:1240,y:1130,vx:-1,vy:0,life:4,damage:20,enemy:true,kind:'arrow',pierce:1,hit:new Set()});w.nova();assert.equal(w.bullets.length,0);assert.equal(e.slow,3);assert.equal(w.player.mana,72);const hp=e.hp;w.nova();assert.equal(e.hp,hp);});
test('stations have independent cooldowns, full resources do not waste charges, bell redirects navigation',()=>{const w=make(),s=w.stations.find(s=>s.kind==='well')!;Object.assign(w.player,{x:s.x,y:s.y});w.interact();assert.equal(s.cooldown,0);w.player.hp=20;w.interact();assert.equal(w.player.hp,70);assert.equal(s.cooldown,55);w.interact();assert.equal(w.player.hp,70);const b=w.stations.find(s=>s.kind==='bell')!;Object.assign(w.player,{x:b.x,y:b.y});w.interact();assert.equal(w.lure.time,9);w.buildNav();assert.deepEqual(w.navTarget,{x:b.x,y:b.y});});
test('damage immunity, death, restart and frozen pause are reliable',()=>{const w=make();w.player.invincible=0;w.hurt(20);assert.equal(w.player.hp,100);w.hurt(20);assert.equal(w.player.hp,100);w.pause(true);const snap=JSON.stringify(w.player);step(w,3,{x:1,fire:true});assert.equal(JSON.stringify(w.player),snap);assert.equal(w.seconds,0);w.pause(false);w.player.invincible=0;w.hurt(1000);assert.equal(w.phase,'dead');w.reset();assert.equal(w.phase,'playing');assert.equal(w.player.hp,120);assert.equal(w.seconds,0);});
test('upgrades stop time, offer three unique choices and can only be selected once',()=>{const w=make();w.xp=w.nextXP;step(w,.01);assert.equal(w.phase,'upgrade');assert.equal(new Set(w.choices).size,3);const t=w.seconds;step(w,3);assert.equal(w.seconds,t);assert.equal(w.choose(w.choices[0]),true);assert.equal(w.rank,2);assert.equal(w.choose(w.upgrades[0]),false);});
test('invasion is endless, difficulty grows, bosses recur and budgets remain bounded',()=>{const w=make();w.spawnClock=0;w.player.invincible=1e7;for(let i=0;i<60*60*12;i++){w.step(1/60,empty);if(w.phase==='upgrade')w.choose(w.choices[0]);}assert.equal(w.phase,'playing');assert.ok(w.seconds>719);assert.equal(w.nextBoss,720);assert.ok(w.enemies.filter(e=>e.kind==='lord').length>=5);assert.ok(w.enemies.length<=80);assert.ok(w.bullets.length<=260);assert.ok(w.particles.length<=400);assert.ok(difficulty(720).health>difficulty(120).health);});

test('large warlords can leave every gate and reach the courtyard',()=>{for(const g of level.gates){const w=make();w.player.invincible=999;const e=w.spawn('lord',g)!;for(let i=0;i<65*60&&distance(e,w.player)>160;i++)w.step(1/60,empty);assert.ok(distance(e,w.player)<160,`Gate ${g.x},${g.y}: ${Math.round(distance(e,w.player))}`);}});

test('a six-minute survival run works through ordinary movement and combat without immunity',async()=>{const {runSurvival}=await import('./survival.ts');const {summary}=runSurvival();assert.equal(summary.phase,'playing');assert.ok(summary.seconds>=359);assert.ok(summary.bosses>=2);assert.ok(summary.lowestHP<120&&summary.lowestHP>0);assert.deepEqual(summary.weapons.sort(),[0,1,2]);});
