import * as T from 'three';
import {SceneRenderer} from './renderer.ts';
import {SceneRuntime} from './runtime.ts';
import {AssetStore} from './assets.ts';
import {storageKey} from './project.ts';
import type {EditorHost,RuntimeSession,SessionOptions,BehaviorContext} from './sdk.ts';
import {LayoutView,assertLayout,wallCrossing,visibleRooms,layoutIssues,type Layout} from '../modules/layout.ts';
export function createDefaultHost(canvas:HTMLCanvasElement,showLayout=true):EditorHost {
 const renderer=new SceneRenderer(canvas),runtime=new SceneRuntime(renderer);runtime.validators.push(doc=>{const layout=doc.moduleData?.layout as Layout|undefined;if(layout){const error=layoutIssues(layout).find(i=>i.id==='layout');if(error)throw new Error(error.message);}});renderer.scene.background=new T.Color('#29343c');renderer.scene.add(new T.HemisphereLight(0xcaddeb,0x343023,2));const sun=new T.DirectionalLight(0xffedce,3);sun.position.set(-4,10,6);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20});renderer.scene.add(sun);const layout=new LayoutView(renderer.scene);
 return {renderer,runtime,floorHeight:3,floorNames:[{value:-1,name:'Подвал'},{value:0,name:'1 этаж'},{value:1,name:'2 этаж'},{value:2,name:'3 этаж'}],prefabs:{},draw:dt=>{const l=runtime.document.moduleData?.layout as Layout|undefined;if(l&&showLayout)layout.apply(l);else if(layout.key){layout.dispose();layout.key='';}sun.intensity=.15+3*Math.max(0,Math.sin((runtime.document.environment.time-360)/1440*Math.PI*2));renderer.scene.fog=new T.FogExp2('#29343c',runtime.document.environment.haze);renderer.render(dt);},updateCamera:dt=>renderer.updateCamera(dt),dispose:()=>{layout.dispose();runtime.dispose();renderer.dispose();}};
}
export async function createRuntimeSession(options:SessionOptions):Promise<RuntimeSession>{
 const custom=[...options.registry.modules.values()].find(m=>m.createSession);if(custom)return custom.createSession!(options);
 const data=structuredClone(options.snapshot);let sceneId=options.sceneId,disposed=false,paused=false,frame=0,last=performance.now(),host:EditorHost|undefined,store:AssetStore|undefined,contexts:BehaviorContext[]=[],layoutView:LayoutView|undefined,player:T.Mesh|undefined,layout:Layout|undefined,open=new Set<string>(),floor=0,x=0,stair:{a:number;b:number;from:number;to:number;t:number;direction:number}|undefined;
 const keys=new Set<string>(),abort=new AbortController(),container=options.container;container.innerHTML='<canvas tabindex="0" aria-label="Игра" style="width:100%;height:100%;display:block"></canvas><div class="runtime-actions" style="position:absolute;bottom:14px;left:14px;display:flex;gap:8px;flex-wrap:wrap"></div>';
 let canvas=container.querySelector('canvas')!;const actions=container.querySelector<HTMLElement>('.runtime-actions')!;
 const saveKey=storageKey(data.manifest.projectId,'progress',data.manifest.build.appId);
 let saved:any;try{if(options.savePolicy==='persistent')saved=JSON.parse(localStorage.getItem(saveKey)||'null');}catch{}
 async function load(id:string){const scene=data.scenes[id];if(!scene)throw new Error('Сцена перехода не включена: '+id);options.registry.validate(scene,data.manifest);if(scene.moduleData?.layout)assertLayout(scene.moduleData.layout as Layout);
  const nextStore=new AssetStore();await nextStore.load(data.manifest.assets,options.assetUrl);if(disposed){nextStore.dispose();return;}for(const c of contexts)options.registry.components.get(c.component.type)?.dispose?.(c);layoutView?.dispose();host?.dispose();store?.dispose();const fresh=canvas.cloneNode(false) as HTMLCanvasElement;canvas.replaceWith(fresh);canvas=fresh;store=nextStore;host=createDefaultHost(canvas,false);store.bind(host.runtime);host.runtime.apply(scene);host.renderer.resize();sceneId=id;host.renderer.beforeRender=()=>{};
  layout=scene.moduleData?.layout as Layout|undefined;layoutView=undefined;player=undefined;stair=undefined;actions.innerHTML='';
  if(layout){layoutView=new LayoutView(host.renderer.scene);layoutView.apply(layout);layoutView.root.traverse(o=>{if(o.userData.editorOnly)o.visible=false;});open=new Set(layout.doors.filter(d=>d.open).map(d=>d.id));floor=layout.spawn.floor;x=layout.spawn.x;player=new T.Mesh(new T.CapsuleGeometry(.18,1.15,6,12),new T.MeshStandardMaterial({color:0xecc37d}));host.renderer.scene.add(player);const hint=document.createElement('span');hint.textContent='A/D — идти · W/S — лестница · E — дверь';hint.style.cssText='color:white;background:#111c;padding:8px';actions.append(hint);}
  contexts=scene.nodes.flatMap(node=>(node.components||[]).map(component=>({node,component,runtime:host!.runtime,scene,transition:go,keys})));
  for(const c of contexts){options.registry.components.get(c.component.type)?.load?.(c);if(c.component.type==='basic.portal'){const b=document.createElement('button');b.textContent=String(c.component.values.label);b.onclick=()=>go(String(c.component.values.scene));actions.append(b);}}
  host.renderer.updateCamera(100);canvas.focus();
 }
 let loading=false;function go(id:string){if(loading||paused||disposed)return;loading=true;load(id).catch(showError).finally(()=>loading=false);}
 function showError(e:unknown){const el=document.createElement('p');el.style.cssText='position:absolute;top:10px;background:#511;color:white;padding:12px';el.textContent=String(e);container.append(el);}
 const press=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select'))return;if(['KeyA','KeyD','KeyW','KeyS','KeyE','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyE'&&!e.repeat&&!paused&&layout){const door=layout.doors.find(d=>d.floor===floor&&Math.abs(d.x-x)<1);if(door){if(open.has(door.id))open.delete(door.id);else open.add(door.id);layoutView?.setDoors(open);}}};
 window.addEventListener('keydown',press,{signal:abort.signal});window.addEventListener('keyup',e=>keys.delete(e.code),{signal:abort.signal});window.addEventListener('blur',()=>keys.clear(),{signal:abort.signal});
 await load(saved?.sceneId&&data.scenes[saved.sceneId]?saved.sceneId:sceneId);
 const resize=new ResizeObserver(()=>{host?.renderer.resize();host?.renderer.updateCamera(100);});resize.observe(container);
 function tick(now:number){if(disposed)return;const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused&&!loading&&host){for(const c of contexts)options.registry.components.get(c.component.type)?.update?.(c,dt);
  if(layout&&player){const direction=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));if(!stair){let next=x+direction*2.5*dt;const hit=wallCrossing(layout,x,next,floor,open);if(hit!==null)next=hit-Math.sign(direction)*.025;if(layout.rooms.some(r=>r.floor===floor&&next>=r.x&&next<=r.x+r.width))x=next;const up=keys.has('KeyW')||keys.has('ArrowUp'),down=keys.has('KeyS')||keys.has('ArrowDown');const s=layout.stairs.find(s=>up&&s.from===floor&&Math.abs(s.a-x)<.7||down&&s.to===floor&&Math.abs(s.b-x)<.7);if(s)stair={...s,t:up?0:1,direction:up?1:-1};}if(stair){stair.t+=dt*.6*stair.direction;x=stair.a+(stair.b-stair.a)*Math.max(0,Math.min(1,stair.t));player.position.set(x,(stair.from+Math.max(0,Math.min(1,stair.t)))*layout.floorHeight+.75,-.75);if(stair.t>=1||stair.t<=0){floor=stair.direction>0?stair.to:stair.from;stair=undefined;}}else player.position.set(x,floor*layout.floorHeight+.75,0);}
 }if(host){if(layout){const seen=visibleRooms(layout,x,floor,open);for(const node of host.runtime.document.nodes){const room=layout.rooms.find(r=>r.floor===Math.floor((node.transform.position[1]+.05)/layout!.floorHeight)&&node.transform.position[0]>=r.x&&node.transform.position[0]<=r.x+r.width);const root=host.runtime.instances.get(node.id)?.root;if(root)root.visible=node.visible&&(!room||!!node.light||seen.has(room.id));}}const cameraNode=host.runtime.document.nodes.find(n=>n.id===host!.runtime.document.activeCamera);if(cameraNode){host.renderer.externalCamera=true;host.renderer.camera.position.fromArray(cameraNode.transform.position);host.renderer.camera.rotation.set(...cameraNode.transform.rotation.map(T.MathUtils.degToRad) as [number,number,number]);host.renderer.camera.updateMatrixWorld();}host.draw(dt);}frame=requestAnimationFrame(tick);}
 frame=requestAnimationFrame(tick);
 return {pause(value){paused=value;keys.clear();if(value)for(const c of contexts)options.registry.components.get(c.component.type)?.pause?.(c);},dispose(){disposed=true;cancelAnimationFrame(frame);abort.abort();resize.disconnect();for(const c of contexts)options.registry.components.get(c.component.type)?.dispose?.(c);if(options.savePolicy==='persistent')try{localStorage.setItem(saveKey,JSON.stringify({sceneId}));}catch{}layoutView?.dispose();host?.dispose();store?.dispose();container.replaceChildren();},diagnostics:()=>({sceneId,paused,x,floor,visibleRooms:layout?[...visibleRooms(layout,x,floor,open)]:[],openDoors:[...open],frames:1,memory:host?.renderer.gl.info.memory})};
}
