import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {World,readLevel,difficulty,type Controls} from '../../games/hellrift/scripts/world.ts';
const level=readLevel(JSON.parse(readFileSync(new URL('../../games/hellrift/scenes/arena.scene.json',import.meta.url),'utf8')));
const idle:Controls={forward:0,strafe:0,turn:0,fire:false,dash:false,weapon:-1};
function fresh(){let seed=72;const w=new World(level,()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;});w.start();w.enemies=[];w.spawnTimer=9999;return w;}
function step(w:World,seconds:number,c=idle){for(let i=0;i<Math.round(seconds*120);i++)w.step(1/120,c);}
test('The scene uses valid cover and four portals',()=>{assert.equal(level.portals.length,4);assert.equal(level.cover.length,10);assert.equal(level.size,46);});
test('Endless pressure keeps increasing after 20 minutes',()=>{const early=difficulty(30),later=difficulty(240),end=difficulty(2400);assert.ok(later.health>early.health);assert.ok(later.damage>early.damage);assert.ok(later.cap>early.cap);assert.ok(later.interval<early.interval);assert.ok(end.health>later.health&&end.damage>later.damage);assert.ok(end.cap<=78);});
test('Movement is normalized and cannot cross cover or perimeter',()=>{const straight=fresh(),diagonal=fresh();straight.player.x=diagonal.player.x=0;straight.player.z=diagonal.player.z=18;step(straight,.25,{...idle,forward:1});step(diagonal,.25,{...idle,forward:1,strafe:1});assert.ok(Math.abs(Math.hypot(diagonal.player.x,diagonal.player.z-18)-Math.abs(straight.player.z-18))<.001);const w=fresh();w.player.x=-4;w.player.z=-4;step(w,1,{...idle,forward:1});assert.ok(w.player.z>=-5.63);w.player.x=0;w.player.z=-21;step(w,1,{...idle,forward:1});assert.ok(w.player.z>=-21.63);});
test('Hitscan hits the first demon but never through cover',()=>{const w=fresh();Object.assign(w.player,{x:0,z:5,yaw:0,weapon:0});const e=w.spawn('imp',{x:0,z:0});e.x=0;e.z=0;e.age=1;const hp=e.hp;w.fire();assert.ok(e.hp<hp);Object.assign(w.player,{x:-4,z:-3,cooldown:0});e.x=-4;e.z=-10;e.hp=hp;w.fire();assert.equal(e.hp,hp);});
test('Shotgun kills close enemies and ammo exhaustion leaves unlimited pistol',()=>{const w=fresh();Object.assign(w.player,{x:0,z:5,yaw:0,weapon:1});const e=w.spawn('imp',{x:0,z:3});e.x=0;e.z=3;e.age=1;w.fire();assert.ok(e.hp<=0);assert.equal(w.kills,1);w.player.ammo[1]=0;w.player.cooldown=0;w.fire();assert.equal(w.player.weapon,0);assert.equal(w.player.ammo[0],Infinity);});
test('Pause and upgrades freeze the survival clock; choosing upgrade resumes',()=>{const w=fresh();step(w,1);w.pause(true);step(w,2);assert.ok(Math.abs(w.seconds-1)<.001);w.pause(false);w.seconds=44.99;w.step(.02,idle);assert.equal(w.phase,'upgrade');assert.equal(w.choices.length,3);const before=w.seconds;step(w,3);assert.equal(w.seconds,before);w.choose(w.choices[0]);assert.equal(w.phase,'playing');assert.equal(w.nextUpgrade,90);});
test('Minute unlock and 90-second titan spawn actually happen',()=>{const w=fresh();w.nextUpgrade=9999;w.seconds=59.99;w.step(.02,idle);assert.equal(w.unlocked,true);w.seconds=89.99;w.step(.02,idle);assert.equal(w.enemies.filter(e=>e.kind==='titan').length,1);assert.equal(w.nextBoss,180);});
test('Dash gives temporary immunity but normal damage uses armor',()=>{const w=fresh();w.step(.01,{...idle,dash:true});w.hurt(50);assert.equal(w.player.hp,100);step(w,.3);w.hurt(20);assert.ok(w.player.hp<100);assert.equal(w.player.armor,27);});
test('Projectiles are stopped by solid cover',()=>{const w=fresh();w.bullets.push({id:9000,x:-4,z:-5.8,vx:0,vz:-8,life:3,damage:15});step(w,.1);assert.equal(w.bullets.length,0);});
test('Death freezes time; restarting resets the full run',()=>{const w=fresh();w.hurt(1000);assert.equal(w.phase,'dead');step(w,1);assert.equal(w.seconds,0);w.power=4;w.kills=40;w.unlocked=true;w.start();assert.equal(w.phase,'playing');assert.equal(w.power,1);assert.equal(w.kills,0);assert.equal(w.unlocked,false);assert.equal(w.player.hp,100);assert.equal(w.player.ammo[1],28);});
test('Crowds eventually negotiate a frontal bunker',()=>{const w=fresh();w.nextUpgrade=9999;w.player.x=-4;w.player.z=-3;const e=w.spawn('imp',{x:-4,z:-10});e.x=-4;e.z=-10;e.age=1;step(w,13);assert.ok(Math.hypot(e.x-w.player.x,e.z-w.player.z)<2,`Demon stuck at ${e.x},${e.z}`);});
test('Long sessions with surviving titans stay within the render budget',()=>{const w=fresh();for(let i=0;i<100;i++)w.spawn('titan');assert.equal(w.enemies.length,80);assert.equal(w.kills,0);w.nextUpgrade=99999;w.nextSupply=99999;w.nextBoss=99999;step(w,2);assert.ok(w.enemies.every(e=>[e.x,e.z,e.hp].every(Number.isFinite)));});
