import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {template} from '../../scripts/engine/templates.ts';
import {readProject,writeProject,revision,inside} from '../../scripts/engine/files.ts';
import {pack,unpack} from '../../scripts/engine/zip.ts';
import {validateProject,validateSnapshot,portablePath,storageKey} from '../../src/engine/project.ts';
import {SceneHistory,identity} from '../../src/engine/scene.ts';
import {inspectGLTF} from '../../src/engine/asset-format.ts';
import {defaultLayout,layoutIssues,wallCrossing} from '../../src/modules/layout.ts';
import {ModuleRegistry} from '../../src/engine/sdk.ts';
import {basic} from '../../src/modules/basic.ts';

test('Project and scene identities are portable and independent; empty 3D has no house requirement',()=>{const a=template('A','empty-3d'),b=template('B','neutral-25d');validateSnapshot(a);validateSnapshot(b);assert.notEqual(a.manifest.projectId,b.manifest.projectId);assert.notEqual(storageKey(a.manifest.projectId,'draft','scene'),storageKey(b.manifest.projectId,'draft','scene'));assert.equal(a.scenes[a.manifest.startScene].moduleData,undefined);const future=structuredClone(a);(future.manifest as any).version=99;assert.throws(()=>validateSnapshot(future),/Несовместимая/);for(const bad of ['../x','/etc/x','x/../a','x\\y','http://site/a'])assert.equal(portablePath(bad),false);});

test('Atomic manifest switch prevents partial scene saves and external edits cannot be overwritten',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'shelter-storage-')),initial=template('Atomic','empty-3d');const first=await writeProject(root,initial),rev=revision(first),next=structuredClone(first);next.scenes[next.manifest.startScene].name='Updated';await writeProject(root,next,rev);await assert.rejects(()=>writeProject(root,first,rev),/другом окне/);const loaded=await readProject(root);assert.equal(loaded.scenes[loaded.manifest.startScene].name,'Updated');const failed=structuredClone(loaded);failed.scenes[failed.manifest.startScene].nodes[0].transform.scale[0]=0;await assert.rejects(()=>writeProject(root,failed,revision(loaded)));assert.deepEqual(await readProject(root),loaded);assert.ok((await fs.readdir(path.join(root,'settings/backups'))).length>0);});

test('ZIP includes binaries verbatim and rejects traversal, damaged payloads and symlinks',()=>{const files=new Map([['project.shelter.json',Buffer.from('{"hello":true}')],['assets/test.bin',Buffer.from([0,1,255,0,254])]]),zip=pack(files);assert.deepEqual(unpack(zip),files);assert.throws(()=>unpack(pack(new Map([['../escaped',Buffer.from('bad')]]))),/ZIP/);const broken=Buffer.from(zip);broken[60]^=255;assert.throws(()=>unpack(broken));});

test('File access rejects symlink escapes',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'shelter-path-'));await fs.symlink(os.tmpdir(),path.join(root,'external'));await assert.rejects(()=>inside(root,'external/private-file'),/Символическая/);await assert.rejects(()=>inside(root,'../file'),/Недопустимый/);});

test('Neutral layout shares boundaries for movement, validates stairs and is undoable as one scene command',()=>{const l=defaultLayout();l.rooms.push({id:'east',name:'Восточная',x:4,width:4,floor:0,depth:4,color:'#888888'},{id:'upper',name:'Верхняя',x:-4,width:8,floor:1,depth:4,color:'#888888'});l.doors.push({id:'door',name:'Дверь',x:4,floor:0,open:false});l.stairs.push({id:'stair',name:'Лестница',a:-2,b:1,from:0,to:1});assert.deepEqual(layoutIssues(l),[]);assert.equal(wallCrossing(l,3.9,4.1,0,new Set()),4);assert.equal(wallCrossing(l,3.9,4.1,0,new Set(['door'])),null);const p=template('Layout','neutral-25d'),scene=p.scenes[p.manifest.startScene];scene.moduleData!.layout=l;const history=new SceneHistory(scene),bad=structuredClone(scene);(bad.moduleData!.layout as typeof l).stairs[0].b=20;assert.ok(layoutIssues(bad.moduleData!.layout as typeof l).some(e=>e.id==='stair'));history.commit(bad);history.undo();assert.deepEqual(history.document,scene);history.redo();assert.deepEqual(history.document,bad);});

test('Component schemas reject unknown behaviors, broken links and numeric range errors',()=>{const r=new ModuleRegistry();r.register(basic);const p=template('Behavior','empty-3d'),s=p.scenes[p.manifest.startScene];s.nodes.push({id:'cube',name:'Куб',kind:'box',layer:'props',visible:true,locked:false,transform:identity(),components:[{type:'basic.rotate',values:{speed:30,axis:'y'}}]});r.validate(s,p.manifest);s.nodes[1].components![0].values.speed=400;assert.throws(()=>r.validate(s,p.manifest),/Скорость/);s.nodes[1].components=[{type:'basic.portal',values:{scene:'missing',label:'Go'}}];assert.throws(()=>r.validate(s,p.manifest),/связь/);s.nodes[1].components=[{type:'future.unknown',values:{}}];assert.throws(()=>r.validate(s,p.manifest),/Отсутствует/);});

test('Static glTF import catches missing dependencies, unsupported extensions and incomplete GLB',async()=>{const good=await fs.readFile('library/assets/starter/table.glb');assert.ok(inspectGLTF(good,'table.glb',new Set(['table.glb'])).triangles>100);assert.throws(()=>inspectGLTF(good.subarray(0,50),'bad.glb',new Set()),/GLB/);const encode=(v:any)=>new TextEncoder().encode(JSON.stringify(v));assert.throws(()=>inspectGLTF(encode({asset:{version:'2.0'},buffers:[{uri:'mesh.bin'}]}),'scene.gltf',new Set(['scene.gltf'])),/mesh.bin/);assert.throws(()=>inspectGLTF(encode({asset:{version:'2.0'},extensionsUsed:['KHR_draco_mesh_compression']}),'scene.gltf',new Set()),/расширения/);assert.throws(()=>inspectGLTF(encode({asset:{version:'2.0'},animations:[{}]}),'scene.gltf',new Set()),/статические/);});

test('Core, modules and editor imports have no direct or transitive game dependencies',async()=>{const seen=new Set<string>();async function scan(file:string){if(seen.has(file))return;seen.add(file);const source=await fs.readFile(file,'utf8');for(const match of source.matchAll(/(?:from\s*|import\s*\()\s*['"]([^'"]+)['"]/g)){const target=match[1];assert.ok(!target.includes('/base/')&&!target.includes('/games/')&&!target.includes('while-the-light'),`${file}: ${target}`);if(target.startsWith('.')){const resolved=path.resolve(path.dirname(file),target);if(resolved.endsWith('.ts'))await scan(resolved);}}}for(const dir of ['src/engine','src/editor','src/modules'])for(const file of await fs.readdir(dir))if(file.endsWith('.ts'))await scan(path.resolve(dir,file));assert.ok(seen.size>15);});
