import {test,expect,type Page} from '@playwright/test';
import {mkdir,readFile,writeFile,mkdtemp,cp} from 'node:fs/promises';
import path from 'node:path';
const snapshot=(p:Page)=>p.evaluate(()=>(window as any).__EDITOR__.snapshot());
const project=(p:Page)=>p.evaluate(()=>(window as any).__EDITOR__.project());
async function closeDialog(p:Page){await p.getByRole('button',{name:'Закрыть окно',exact:true}).last().click();}
async function number(p:Page,name:string,value:string){const input=p.getByRole('spinbutton',{name,exact:true});await input.fill(value);await input.press('Tab');}
async function addBasic(p:Page,name:string){await p.getByRole('button',{name:'＋ Объект / свет / камера',exact:true}).click();await p.getByRole('dialog').getByRole('button',{name,exact:true}).click();}
async function build(p:Page){await p.getByRole('button',{name:'Собрать игру',exact:true}).click();const dialog=p.getByRole('dialog');await dialog.getByRole('button',{name:'Собрать игру',exact:true}).click();await expect(dialog.getByRole('button',{name:'Проверить сборку',exact:true})).toBeVisible({timeout:120000});await p.screenshot({path:'artifacts/engine/build-'+Date.now()+'.png'});const output=await dialog.locator('.build-result p').innerText();await dialog.getByRole('button',{name:'Проверить сборку',exact:true}).click();const preview=p.frameLocator('iframe.build-preview');await expect(preview.locator('canvas').first()).toBeVisible();await expect(preview.locator('#app')).not.toContainText('Не удалось');await closeDialog(p);await closeDialog(p);return output;}

test('No-code workflow: neutral project, library, model import, behaviors, history, play and independent build',async({page})=>{
 const errors:string[]=[],requests:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.goto('/');await expect(page.getByRole('heading',{name:'Проекты',exact:true})).toBeVisible();expect(requests.some(u=>u.includes('while-the-light-is-on')||u.includes('developer-walk'))).toBe(false);
 await page.screenshot({path:'artifacts/engine/01-project-manager.png'});await page.getByRole('button',{name:'＋ Создать проект',exact:true}).click();await page.getByLabel('Название проекта',{exact:true}).fill('Acceptance B '+Date.now());await page.getByLabel('Шаблон проекта').selectOption('neutral-25d');await page.getByRole('button',{name:'Создать и открыть',exact:true}).click();await expect(page.locator('#editor-canvas')).toBeVisible();
 await page.getByRole('button',{name:'Shelter Library ↗',exact:true}).click();await page.getByLabel('Поиск в библиотеке').fill('Обеденный стол');await expect(page.getByRole('button',{name:'Посмотреть: Обеденный стол',exact:true})).toBeVisible();await page.getByRole('button',{name:'Добавить в проект',exact:true}).click();await expect(page.locator('.library-card footer')).toContainText('В проекте');await page.getByLabel('Поиск в библиотеке').fill('Дерево');await page.getByRole('button',{name:'Добавить в проект',exact:true}).click();await page.screenshot({path:'artifacts/engine/02-library.png'});await closeDialog(page);
 await page.locator('[data-asset="starter-table"]').click();await number(page,'Положение X','-1');await number(page,'Поворот Y','15');const first=(await snapshot(page)).nodes.find((n:any)=>n.asset==='starter-table');
 await page.locator('[data-asset="starter-table"]').click();await number(page,'Положение X','1');await page.locator('[data-asset="starter-wood"]').click();const second=(await snapshot(page)).nodes.filter((n:any)=>n.asset==='starter-table')[1];expect(second.surface.texture).toBe('asset:starter-wood');expect((await snapshot(page)).nodes.find((n:any)=>n.id===first.id).surface).toBeUndefined();
 await page.getByRole('button',{name:'Отменить',exact:true}).click();expect((await snapshot(page)).nodes.find((n:any)=>n.id===second.id).surface).toBeUndefined();await page.getByRole('button',{name:'Повторить',exact:true}).click();
 await page.getByLabel('Готовое поведение').selectOption('basic.rotate');await page.getByRole('button',{name:'Добавить поведение',exact:true}).click();await number(page,'Скорость','45');
 await page.getByRole('button',{name:'Импорт',exact:true}).click();await page.getByLabel('Файлы ресурса').setInputFiles(path.resolve('library/assets/starter/chair.glb'));await expect(page.getByRole('button',{name:'Импортировать',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Импортировать',exact:true}).click();await expect(page.getByRole('heading',{name:'Импорт в проект'})).toBeHidden();const asset=(await project(page)).manifest.assets.find((a:any)=>a.id.startsWith('asset-'));await page.locator(`[data-asset="${asset.id}"]`).click();await number(page,'Положение X','2');await page.screenshot({path:'artifacts/engine/03-inspector.png'});

 // Build a connected two-floor plan entirely through its controls, including a rejected route.
 await page.getByRole('button',{name:'Планировка',exact:true}).click();let plan=page.getByRole('dialog');
 await number(page,'Ширина комнаты, м','4');await number(page,'Появление X, м','-2');await plan.getByRole('button',{name:'＋ Комната',exact:true}).click();await expect(plan.locator('.layout-issues')).toContainText('нет маршрута');
 await plan.getByRole('button',{name:'＋ Дверь',exact:true}).click();await expect(plan.locator('.layout-issues')).toContainText('готова');
 await plan.getByRole('button',{name:'＋ Комната',exact:true}).click();const upper=plan.locator('[data-type="rooms"]').nth(2);await upper.getByLabel('Этаж комнаты',{exact:true}).fill('1');await upper.getByLabel('Этаж комнаты',{exact:true}).press('Tab');await upper.getByLabel('Левая граница, м',{exact:true}).fill('-4');await upper.getByLabel('Левая граница, м',{exact:true}).press('Tab');await upper.getByLabel('Ширина комнаты, м',{exact:true}).fill('8');await upper.getByLabel('Ширина комнаты, м',{exact:true}).press('Tab');
 await plan.getByRole('button',{name:'＋ Лестница',exact:true}).click();await number(page,'Начало лестницы, м','-2');await number(page,'Конец лестницы, м','1');await plan.getByRole('button',{name:'＋ Окно',exact:true}).click();await expect(plan.locator('.layout-issues')).toContainText('готова');await page.screenshot({path:'artifacts/engine/06-layout.png'});await closeDialog(page);
 const firstScene=(await project(page)).manifest.startScene;
 await page.getByRole('button',{name:'Файл',exact:true}).click();await page.getByRole('button',{name:'Создать сцену',exact:true}).click();await page.getByLabel('Название новой сцены').fill('Галерея');await page.getByRole('button',{name:'Создать сцену',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByLabel('Название новой сцены')).toBeHidden();
 await addBasic(page,'Сфера');await number(page,'Положение X','0');await addBasic(page,'Камера');await number(page,'Положение Y','2');await number(page,'Положение Z','14');await page.getByRole('button',{name:'Сделать игровой камерой',exact:true}).click();const secondScene=(await snapshot(page)).id;
 await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('status')).toContainText('на диск');await page.getByRole('button',{name:'Файл',exact:true}).click();await page.getByRole('button',{name:'Сцены проекта',exact:true}).click();await page.getByRole('dialog').locator('article').first().getByRole('button',{name:'Открыть',exact:true}).click();
 await page.getByRole('button',{name:'Выбрать: '+asset.name,exact:true}).click();await page.getByLabel('Готовое поведение').selectOption('basic.portal');await page.getByRole('button',{name:'Добавить поведение',exact:true}).click();await page.getByLabel('Куда перейти',{exact:true}).selectOption(secondScene);
 const before=await snapshot(page);await page.getByRole('button',{name:'▶ Играть',exact:true}).click();await expect(page.frameLocator('iframe.play-session').getByLabel('Игра',{exact:true})).toBeVisible();await expect(page.getByRole('status')).toContainText('Пробная игра');const game=page.frames().find(f=>f.url().includes('player.html'))!;const runtime=()=>game.evaluate(()=>(window as any).__RUNTIME__.diagnostics());await game.locator('canvas').press('KeyW');await game.locator('canvas').focus();await page.keyboard.down('KeyW');await expect.poll(async()=>(await runtime()).floor).toBe(1);await page.keyboard.up('KeyW');await page.keyboard.down('KeyS');await expect.poll(async()=>(await runtime()).floor).toBe(0);await page.keyboard.up('KeyS');await page.keyboard.down('KeyD');await expect.poll(async()=>(await runtime()).x).toBeGreaterThan(-.1);await page.keyboard.up('KeyD');expect((await runtime()).x).toBeLessThan(0);await page.keyboard.press('KeyE');await page.keyboard.down('KeyD');await expect.poll(async()=>(await runtime()).x).toBeGreaterThan(.3);await page.keyboard.up('KeyD');await page.screenshot({path:'artifacts/engine/07-neutral-play.png'});await game.getByRole('button',{name:'Следующая сцена',exact:true}).click();await expect.poll(async()=>(await runtime()).sceneId).toBe(secondScene);await expect(game.locator('canvas')).toBeVisible();await page.getByRole('button',{name:'Ⅱ Пауза',exact:true}).click();await expect(page.getByRole('button',{name:'▶ Продолжить',exact:true})).toBeVisible();await page.getByRole('button',{name:'■ Стоп',exact:true}).click();expect(await snapshot(page)).toEqual(before);
 for(let i=0;i<9;i++){await page.getByRole('button',{name:'▶ Играть',exact:true}).click();await expect(page.getByRole('status')).toContainText('Пробная игра');await page.getByRole('button',{name:'■ Стоп',exact:true}).click();}expect(await snapshot(page)).toEqual(before);
 await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('status')).toContainText('на диск');const savedProject=await project(page);await page.reload();await expect(page.locator('#editor-canvas')).toBeVisible();expect(await snapshot(page)).toEqual(before);
 for(const [width,height] of [[1440,900],[1280,720],[347,790]]){await page.setViewportSize({width,height});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(page.getByRole('button',{name:'Собрать игру',exact:true})).toBeVisible();await page.screenshot({path:`artifacts/engine/viewport-${width}.png`});}await page.setViewportSize({width:1440,height:900});
 const output=await build(page);const report=JSON.parse(await readFile(path.join(output,'build-report.json'),'utf8'));expect(report.modules.map((m:any)=>m.id)).toEqual(['shelter.basic']);expect(report.assets.some((p:string)=>p.includes('base/')||p.includes('developer-'))).toBe(false);
 await writeFile('artifacts/engine/project-b-result.json',JSON.stringify({projectPath:savedProject.path,output,projectId:savedProject.manifest.projectId},null,2));expect(errors).toEqual([]);
});

test('Example A retains its real game, camera, furniture and can be built separately',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:'Открыть пример',exact:true}).click();await expect(page.locator('#editor-canvas')).toBeVisible({timeout:120000});expect((await snapshot(page)).nodes.length).toBeGreaterThan(100);
 await page.getByLabel('Найти объект',{exact:true}).fill('Платяной шкаф');await page.getByRole('button',{name:'Выбрать: Платяной шкаф',exact:true}).click();await number(page,'Положение X','2.3');await page.getByRole('button',{name:'Отменить',exact:true}).click();await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('status')).toContainText('на диск');
 await page.screenshot({path:'artifacts/engine/04-example-a-editor.png'});await page.getByRole('button',{name:'▶ Играть',exact:true}).click();await expect(page.frameLocator('iframe.play-session').locator('#base-loading')).toBeHidden({timeout:120000});await expect(page.getByRole('status')).toContainText('Пробная игра');await page.screenshot({path:'artifacts/engine/05-example-a-play.png'});await page.getByRole('button',{name:'■ Стоп',exact:true}).click();
 const output=await build(page);await writeFile('artifacts/engine/project-a-result.json',JSON.stringify({output},null,2));expect(errors).toEqual([]);
});


test('Textured glTF, material channels, discard, project archive and copy survive a new location',async({page})=>{
 const previous=JSON.parse(await readFile('artifacts/engine/project-b-result.json','utf8')),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?project='+encodeURIComponent(previous.projectPath));await expect(page.locator('#editor-canvas')).toBeVisible();
 await page.getByRole('button',{name:'Импорт',exact:true}).click();await page.getByLabel('Папка glTF',{exact:true}).setInputFiles(path.resolve('tests/engine/fixtures/textured-crate'));await expect(page.getByRole('button',{name:'Импортировать',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Импортировать',exact:true}).click();await expect(page.getByRole('heading',{name:'Импорт в проект'})).toBeHidden();
 const a=(await project(page)).manifest.assets.find((a:any)=>a.path.endsWith('.gltf'));expect(a.dependencies.length).toBe(2);await page.locator(`[data-asset="${a.id}"]`).click();await number(page,'Положение X','-2.5');const first=(await snapshot(page)).nodes.find((n:any)=>n.asset===a.id);await page.locator(`[data-asset="${a.id}"]`).click();await number(page,'Положение X','2.5');
 await page.getByRole('button',{name:'Shelter Library ↗',exact:true}).click();await page.getByRole('button',{name:'Создать материал',exact:true}).click();const material=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Создать материал',exact:true})});await material.getByLabel('Название материала',{exact:true}).fill('Приёмка PBR '+Date.now());await material.locator('[data-channel=baseColor]').setInputFiles(path.resolve('library/assets/starter/metal.png'));await material.getByLabel('Металличность',{exact:true}).fill('.7');await material.getByLabel('Лицензия',{exact:true}).fill('CC0 — Shelter starter');const name=await material.getByLabel('Название материала',{exact:true}).inputValue();await material.getByRole('button',{name:'Сохранить в библиотеку',exact:true}).click();await expect(material).toBeHidden();await page.getByLabel('Поиск в библиотеке').fill(name);await page.getByRole('button',{name:'Добавить в проект',exact:true}).click();await expect(page.locator('.library-card footer')).toContainText('В проекте');await closeDialog(page);const mat=(await project(page)).manifest.assets.find((a:any)=>a.name===name);await page.locator(`[data-asset="${mat.id}"]`).click();expect((await snapshot(page)).nodes.find((n:any)=>n.id===first.id).surface).toBeUndefined();await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.getByRole('status')).toContainText('на диск');await page.getByRole('button',{name:'Проект',exact:true}).click();await page.getByRole('button',{name:'Настройки проекта',exact:true}).click();await page.getByRole('dialog').getByLabel('Название',{exact:true}).fill('Neutral Workshop');await page.getByRole('button',{name:'Сохранить настройки',exact:true}).click();const saved=await snapshot(page),id=(await project(page)).manifest.projectId;
 await number(page,'Положение X','9');await page.getByRole('button',{name:'Закрыть проект',exact:true}).click();await page.getByRole('button',{name:'Не сохранять',exact:true}).click();await page.getByRole('button',{name:/Neutral|Acceptance B/}).first().click();await expect(page.locator('#editor-canvas')).toBeVisible();expect(await snapshot(page)).toEqual(saved);
 await page.getByRole('button',{name:'Файл',exact:true}).click();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт проекта в ZIP',exact:true}).click();const download=await downloadEvent;await download.saveAs('artifacts/engine/neutral-project.shelter.zip');await page.getByRole('button',{name:'Закрыть проект',exact:true}).click();const chooserEvent=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Открыть архив',exact:true}).click();await (await chooserEvent).setFiles('artifacts/engine/neutral-project.shelter.zip');const directory=path.resolve('artifacts/engine/transferred-'+Date.now());await mkdir(directory,{recursive:true});await page.getByLabel('Путь к папке',{exact:true}).fill(directory);await page.getByRole('button',{name:'Перейти',exact:true}).click();await expect(page.locator('.folder-path')).toHaveText(directory);await page.getByRole('button',{name:'Выбрать эту папку',exact:true}).click();await expect(page.locator('#editor-canvas')).toBeVisible();expect((await project(page)).manifest.projectId).toBe(id);expect(await snapshot(page)).toEqual(saved);await page.screenshot({path:'artifacts/engine/08-restored-project.png'});
 const output=await build(page);await writeFile('artifacts/engine/project-b-result.json',JSON.stringify({projectPath:(await project(page)).path,output,projectId:id},null,2));
 await page.getByRole('button',{name:'Файл',exact:true}).click();await page.getByRole('button',{name:'Создать копию проекта',exact:true}).click();await page.getByRole('dialog').getByLabel('Название копии',{exact:true}).fill('Neutral Copy '+Date.now());await page.getByRole('button',{name:'Создать копию',exact:true}).click();await expect(page.getByRole('heading',{name:'Создать копию проекта',exact:true})).toBeHidden();expect((await project(page)).manifest.projectId).not.toBe(id);expect(await snapshot(page)).toEqual(saved);expect(errors).toEqual([]);
});


test('Workspace controls, group transforms, surface snapping and semantic house edits are undoable',async({page})=>{
 const result=JSON.parse(await readFile('artifacts/engine/project-b-result.json','utf8'));await page.goto('/?project='+encodeURIComponent(result.projectPath));await expect(page.locator('#editor-canvas')).toBeVisible();const original=await snapshot(page),cameraData=original.camera;
 const tables=page.getByRole('button',{name:'Выбрать: Обеденный стол',exact:true});await tables.first().click();await tables.nth(1).click({modifiers:['Shift']});await page.getByRole('button',{name:'Группировать',exact:true}).click();await expect(page.getByLabel('Имя группы',{exact:true})).toBeVisible();await number(page,'Центр X','-1');await page.getByRole('button',{name:'Копия',exact:true}).click();expect((await snapshot(page)).nodes.length).toBe(original.nodes.length+2);for(let i=0;i<3;i++)await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await snapshot(page)).toEqual(original);
 await tables.first().click();await page.getByLabel('Папка объекта',{exact:true}).fill('Мебель');await page.getByLabel('Папка объекта',{exact:true}).press('Tab');await expect(page.locator('.ed-tree')).toContainText('Мебель');await page.getByRole('button',{name:'Отменить',exact:true}).click();
 await page.getByLabel('Рабочий вид',{exact:true}).selectOption('perspective');const beforeCamera=await page.evaluate(()=>(window as any).__EDITOR__.camera());await number(page,'Положение Z','1');expect((await page.evaluate(()=>(window as any).__EDITOR__.camera())).type).toBe('PerspectiveCamera');expect((await snapshot(page)).camera).toEqual(cameraData);await page.getByRole('button',{name:'Отменить',exact:true}).click();
 const box=(await page.locator('#editor-canvas').boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down({button:'right'});await page.keyboard.down('KeyW');await page.waitForTimeout(250);await page.keyboard.up('KeyW');await page.mouse.up({button:'right'});expect((await page.evaluate(()=>(window as any).__EDITOR__.camera())).position).not.toEqual(beforeCamera.position);expect(await snapshot(page)).toEqual(original);
 await number(page,'Положение Y','2');await page.getByRole('button',{name:'На поверхность',exact:true}).click();await page.getByRole('button',{name:'Применить',exact:true}).click();expect((await snapshot(page)).nodes.find((n:any)=>n.id===original.nodes.find((n:any)=>n.asset==='starter-table').id).transform.position[1]).toBeLessThan(2);await page.getByRole('button',{name:'Отменить',exact:true}).click();await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await snapshot(page)).toEqual(original);
 await page.getByRole('button',{name:'Закрыть проект',exact:true}).click();await page.getByRole('button',{name:'Открыть пример',exact:true}).click();await expect(page.locator('#editor-canvas')).toBeVisible();const house=await snapshot(page);await page.getByRole('button',{name:'Планировка',exact:true}).click();await number(page,'Высота этажа, м','2.8');await expect(page.getByRole('dialog').locator('.layout-issues')).toContainText('готова');await closeDialog(page);expect((await snapshot(page)).moduleData.layout.floorHeight).toBe(2.8);await page.getByRole('button',{name:'▶ Играть',exact:true}).click();await expect(page.getByRole('status')).toContainText('Пробная игра');await page.getByRole('button',{name:'■ Стоп',exact:true}).click();await page.getByRole('button',{name:'Отменить',exact:true}).click();expect(await snapshot(page)).toEqual(house);
});


test('A project outside the engine folder uses the public SDK and both editor scenes have bounded frame samples',async({page,browser})=>{
 const external=await mkdtemp('/private/tmp/shelter-external-project-');
 await cp('games/while-the-light-is-on',external,{recursive:true,filter:source=>!source.includes('/settings/backups')});
 const b=JSON.parse(await readFile('artifacts/engine/project-b-result.json','utf8'));
 const errors:string[]=[],samples:any[]=[];page.on('pageerror',e=>errors.push(e.message));
 for(const [name,folder] of [['A',external],['B',b.projectPath]]){
  await page.goto('/?project='+encodeURIComponent(folder));await expect(page.locator('#editor-canvas')).toBeVisible();
  await page.waitForFunction(()=>!!(window as any).__EDITOR__);
  const sample=await page.evaluate(async()=>{const times:number[]=[];let previous=performance.now();for(let i=0;i<90;i++)await new Promise<void>(resolve=>requestAnimationFrame(now=>{times.push(now-previous);previous=now;resolve();}));const sorted=times.slice(1).sort((a,b)=>a-b);return {frames:sorted.length,meanFrameMs:sorted.reduce((a,b)=>a+b,0)/sorted.length,p95FrameMs:sorted[Math.floor(sorted.length*.95)],nodes:(window as any).__EDITOR__.snapshot().nodes.length,memory:(window as any).__EDITOR__.diagnostics()};});
  samples.push({project:name,...sample});
  await page.getByRole('button',{name:'▶ Играть',exact:true}).click();await expect(page.getByRole('status')).toContainText('Пробная игра');await expect(page.frameLocator('iframe.play-session').locator('canvas').first()).toBeVisible();await page.getByRole('button',{name:'■ Стоп',exact:true}).click();
 }
 expect(errors).toEqual([]);await writeFile('artifacts/engine/performance.json',JSON.stringify({browser:browser.version(),viewport:'1440x900',mode:'Chrome headless, samples are not an FPS guarantee',samples,externalProject:external},null,2));
});
