export class AudioEngine {
 context:AudioContext|undefined;master:GainNode|undefined;muted=false;beat=0;lastCast=0;
 async unlock(){try{if(!this.context){this.context=new AudioContext();this.master=this.context.createGain();this.master.gain.value=this.muted?0:.22;this.master.connect(this.context.destination);}if(this.context.state==='suspended')await this.context.resume();}catch{}}
 setMuted(value:boolean){this.muted=value;if(this.context&&this.master)this.master.gain.setTargetAtTime(value?0:.22,this.context.currentTime,.03);}
 tone(f:number,duration:number,type:OscillatorType='sawtooth',volume=.15,end=f){const c=this.context;if(!c||!this.master||c.state!=='running')return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(f,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(10,end),c.currentTime+duration);g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g);g.connect(this.master);o.start();o.stop(c.currentTime+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
 noise(duration:number,volume:number,low:number){const c=this.context;if(!c||!this.master||c.state!=='running')return;const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length)**2;const source=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=low;g.gain.value=volume;source.connect(filter);filter.connect(g);g.connect(this.master);source.start();source.onended=()=>{source.disconnect();filter.disconnect();g.disconnect();};}
 play(name:string){if(this.muted)return;if(name.startsWith('shot')){const shotgun=name==='shot1';this.noise(shotgun?.23:.09,shotgun?1.6:.7,shotgun?1600:3500);this.tone(shotgun?120:180,shotgun?.23:.1,'triangle',.6,30);}else if(name==='hurt'){this.noise(.16,.5,600);this.tone(80,.18,'sawtooth',.2,28);}else if(name==='kill')this.tone(100,.1,'triangle',.14,35);else if(name==='pickup'||name==='upgrade'){this.tone(440,.14,'sine',.25,880);if(name==='upgrade')this.tone(660,.4,'triangle',.14,1320);}else if(name==='dash'){this.noise(.25,.3,1800);this.tone(240,.2,'sine',.12,40);}else if(name==='boss'||name==='dead'){this.tone(60,1.5,'sawtooth',.3,26);this.tone(63,1.4,'sawtooth',.2,29);}else if(name==='cast'&&this.context&&this.context.currentTime-this.lastCast>.2){this.lastCast=this.context.currentTime;this.tone(260,.2,'sine',.08,90);}}
 update(dt:number,playing:boolean,seconds:number){if(!playing||this.muted)return;this.beat-=dt;if(this.beat>0)return;this.beat=.25;const step=Math.floor(seconds*4);if(step%2===0){const notes=[55,55,65.4,55,49,49,58.3,49];this.tone(notes[Math.floor(step/2)%notes.length],.22,'sawtooth',.09);this.tone(120,.12,'sine',.25,35);}if(step%4===2)this.noise(.075,.16,2400);this.noise(.03,.065,9000);}
 dispose(){void this.context?.close();this.context=undefined;}
}
