import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {World,type EnemyKind,type Pickup} from './world.ts';
const colors={iron:0x373944,trim:0x72727b,stone:0x46414b,red:0xe34124,orange:0xff9b48,bone:0xd2b599,green:0x95ef9b};
export class Renderer{
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(78,1,.08,130);gunScene=new T.Scene();gunCamera=new T.PerspectiveCamera(58,1,.01,10);gun=new T.Group();weapon=-1;gunCache=new Map<number,T.Object3D[]>();lootTemplates=new Map<string,T.Group>();bulletTemplate:T.Mesh|undefined;
 world:World;canvas:HTMLCanvasElement;time=0;bob=0;lastX=0;lastZ=0;width=0;height=0;objects=new Map<number,T.Group>();shots=new Map<number,T.Mesh>();loot=new Map<number,T.Group>();templates=new Map<EnemyKind,T.Group>();materials=new Set<T.Material>();geometries=new Set<T.BufferGeometry>();textures=new Set<T.Texture>();portals:T.Group[]=[];muzzle:T.Mesh;gunLight:T.PointLight;
 particleMesh:T.InstancedMesh;shadowMesh:T.InstancedMesh;dummy=new T.Object3D();
 constructor(canvas:HTMLCanvasElement,world:World){this.canvas=canvas;this.world=world;this.renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.35;this.renderer.autoClear=false;this.scene.background=new T.Color(0x180e19);this.scene.fog=new T.FogExp2(0x24131f,.021);
  this.scene.add(new T.HemisphereLight(0xc8b8e9,0x4b3131,2.3));const sun=new T.DirectionalLight(0xffb57c,2.7);sun.position.set(3,20,-10);this.scene.add(sun);const blue=new T.DirectionalLight(0x809aff,1.2);blue.position.set(-15,9,14);this.scene.add(blue);
  this.buildArena();for(const kind of ['imp','hound','caster','brute','titan'] as EnemyKind[])this.templates.set(kind,this.monster(kind));
  this.gunScene.add(new T.HemisphereLight(0xd7e4ff,0x35170b,3));const gl=new T.DirectionalLight(0xffd3a0,4);gl.position.set(-2,3,2);this.gunScene.add(gl);this.gun.scale.setScalar(.7);this.gunScene.add(this.gun);
  this.gunLight=new T.PointLight(0xff9e3e,0,4);this.gunLight.position.set(.23,-.3,-.6);this.gunScene.add(this.gunLight);
  this.muzzle=new T.Mesh(this.geo(new T.IcosahedronGeometry(.17,0)),this.basic(0xffdb89));this.muzzle.position.set(.22,-.23,-1.1);this.gunScene.add(this.muzzle);
  this.particleMesh=new T.InstancedMesh(this.geo(new T.BoxGeometry(.075,.075,.075)),this.basic(0xffffff),160);this.particleMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.particleMesh.frustumCulled=false;this.scene.add(this.particleMesh);
  this.shadowMesh=new T.InstancedMesh(this.geo(new T.CircleGeometry(1,12)),this.mat(0x0a0710,{transparent:true,opacity:.45,depthWrite:false}),82);this.shadowMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.shadowMesh.frustumCulled=false;this.scene.add(this.shadowMesh);this.resize();
 }
 geo<G extends T.BufferGeometry>(g:G){this.geometries.add(g);return g;}
 mat(color:number,extra:T.MeshStandardMaterialParameters={}){const m=new T.MeshStandardMaterial({color,roughness:.88,metalness:.12,...extra});this.materials.add(m);return m;}
 basic(color:number,extra:T.MeshBasicMaterialParameters={}){const m=new T.MeshBasicMaterial({color,...extra});this.materials.add(m);return m;}
 box(parent:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,material:T.Material){const m=new T.Mesh(this.geo(new T.BoxGeometry(w,h,d)),material);m.position.set(x,y,z);parent.add(m);return m;}
 cylinder(parent:T.Object3D,r1:number,r2:number,h:number,x:number,y:number,z:number,material:T.Material,sides=8){const m=new T.Mesh(this.geo(new T.CylinderGeometry(r1,r2,h,sides)),material);m.position.set(x,y,z);parent.add(m);return m;}
 texture(floor:boolean){const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d')!;g.fillStyle=floor?'#55515a':'#544851';g.fillRect(0,0,256,256);let seed=76;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<12000;i++){const v=60+Math.floor(rnd()*70);g.fillStyle=`rgba(${v},${v},${v},.18)`;g.fillRect(rnd()*256,rnd()*256,1+rnd()*3,1+rnd()*3);}g.lineWidth=3;g.strokeStyle='#24212b';if(floor){g.strokeRect(2,2,252,252);g.strokeRect(10,10,236,236);for(const x of [17,239])for(const y of [17,239]){g.fillStyle='#77717a';g.fillRect(x-2,y-2,4,4);}}else{for(let row=0;row<4;row++){const y=row*64;g.beginPath();g.moveTo(0,y);g.lineTo(256,y);g.stroke();for(let col=-1;col<3;col++){g.beginPath();const x=col*128+(row%2)*64;g.moveTo(x,y);g.lineTo(x,y+64);g.stroke();}}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.magFilter=T.NearestFilter;t.repeat.set(floor?23:3,floor?23:2);this.textures.add(t);return t;}
 buildArena(){const iron=this.mat(0x6d6472,{map:this.texture(false)}),stone=this.mat(0xb4a1a5,{map:this.texture(false)}),trim=this.mat(colors.trim),dark=this.mat(0x211f2a),orange=this.basic(colors.orange),red=this.basic(colors.red);
  this.box(this.scene,46,.4,46,0,-.2,0,this.mat(0xaaa0a0,{map:this.texture(true)}));
  for(const sign of [-1,1]){this.box(this.scene,47,10,1.3,0,5,sign*23,stone);this.box(this.scene,1.3,10,46,sign*23,5,0,stone);this.box(this.scene,46,.32,.5,0,.2,sign*22.2,trim);this.box(this.scene,.5,.32,46,sign*22.2,.2,0,trim);
   for(let v=-18;v<=18;v+=6){for(const axis of [0,1]){const g=new T.Group();g.position.set(axis?sign*22: v,0,axis?v:sign*22);g.rotation.y=axis?Math.PI/2:0;this.scene.add(g);this.box(g,1,11,1.7,0,5.5,0,iron);this.box(g,1.4,.45,2,0,1,0,trim);this.box(g,1.4,.45,2,0,7,0,trim);this.box(g,.14,4,.12,0,4,sign>0?-.91:.91,red);}}
  }
  for(const c of this.world.level.cover){const g=new T.Group();g.position.set(c.x,0,c.z);this.scene.add(g);this.box(g,c.w,c.h,c.d,0,c.h/2,0,c.style==='pillar'?stone:iron);this.box(g,c.w+.3,.35,c.d+.3,0,.3,0,trim);this.box(g,c.w+.25,.25,c.d+.25,0,c.h-.1,0,trim);
   if(c.style==='pillar'){this.box(g,c.w+.65,.65,c.d+.65,0,6.6,0,iron);for(const side of [-1,1]){this.box(g,.14,3,.06,0,3,side*(c.d/2+.03),orange);this.box(g,.06,3,.14,side*(c.w/2+.03),3,0,orange);}this.cylinder(g,.23,.55,1.4,0,c.h+.7,0,dark,4);}
   else{for(const x of [-c.w*.3,0,c.w*.3])for(const side of [-1,1])this.box(g,.15,.2,.08,x,1.8,side*(c.d/2+.05),orange);this.box(g,c.w*.75,.04,c.d*.7,0,c.h+.025,0,dark);}
  }
  // Industrial arches above the side aisles leave a clear, readable arena below.
  for(const x of [-11,11])for(const z of [-6,6]){this.box(this.scene,1,1,12,x,8,z,iron);for(const side of [-1,1]){const brace=this.box(this.scene,.7,4,.7,x,7.7,z+side*4.7,trim);brace.rotation.x=side*.7;}}
  const ritual=new T.Mesh(this.geo(new T.RingGeometry(4.7,4.78,64)),red);ritual.rotation.x=-Math.PI/2;ritual.position.y=.015;this.scene.add(ritual);const inner=ritual.clone();inner.scale.setScalar(.79);this.scene.add(inner);
  for(let i=0;i<12;i++){const a=i*Math.PI/6;const rune=this.box(this.scene,.13,.025,.7,Math.sin(a)*4.2,.025,Math.cos(a)*4.2,red);rune.rotation.y=a;}
  for(const [i,p] of this.world.level.portals.entries()){const g=new T.Group();g.position.set(p.x,0,p.z);g.rotation.y=i===1?Math.PI/2:i===2?-Math.PI/2:i===3?Math.PI:0;this.scene.add(g);this.box(g,6,.4,3,0,.1,0,iron);for(const side of [-1,1]){this.box(g,.9,6,1,side*2.8,3,0,stone);this.box(g,.19,5,.11,side*2.55,3,.56,orange);const spike=this.cylinder(g,0,.55,2,side*2.8,6.8,0,trim,4);spike.rotation.z=side*.2;}
   this.box(g,6.3,.7,1,0,5.8,0,stone);this.box(g,4.8,.12,.1,0,5.4,.55,red);
   const energy=new T.Mesh(this.geo(new T.PlaneGeometry(4.6,4.9)),this.basic(0xc71d23,{transparent:true,opacity:.48,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false}));energy.position.set(0,2.9,0);g.add(energy);
   const ring=new T.Mesh(this.geo(new T.TorusGeometry(1.85,.085,5,48)),orange);ring.position.set(0,3,.25);ring.scale.y=1.18;g.add(ring);
   for(let n=0;n<5;n++){const ray=this.box(g,.035,4.8,.03,(n-2)*.78,2.9,.1,red);ray.rotation.z=(n-2)*.06;}
   g.userData.energy=energy;g.userData.ring=ring;this.portals.push(g);const light=new T.PointLight(0xff4328,24,13,1.8);light.position.set(p.x,3,p.z);this.scene.add(light);
  }
  const moon=new T.Mesh(this.geo(new T.SphereGeometry(5,24,16)),this.basic(0x7e2936));moon.position.set(0,26,-55);this.scene.add(moon);const halo=new T.Mesh(this.geo(new T.TorusGeometry(6,.08,4,64)),this.basic(0xde5744));halo.position.copy(moon.position);this.scene.add(halo);
  // Ember field is static geometry: no allocation or network assets during play.
  const positions=new Float32Array(210*3);for(let i=0;i<210;i++){positions[i*3]=Math.sin(i*127.1)*23;positions[i*3+1]=1+(i*.713)%13;positions[i*3+2]=Math.cos(i*311.7)*23;}const embers=this.geo(new T.BufferGeometry());embers.setAttribute('position',new T.BufferAttribute(positions,3));const emb=new T.PointsMaterial({color:0xff7745,size:.055,transparent:true,opacity:.7});this.materials.add(emb);this.scene.add(new T.Points(embers,emb));
 }
 merge(group:T.Group){group.updateMatrixWorld(true);const buckets=new Map<T.Material,T.BufferGeometry[]>();group.traverse(o=>{if(o instanceof T.Mesh){const mat=o.material as T.Material;const list=buckets.get(mat)||[];const copy=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();list.push(copy.applyMatrix4(o.matrixWorld));buckets.set(mat,list);}});const result=new T.Group();for(const [mat,list] of buckets){const geo=mergeGeometries(list,false)!;for(const g of list)g.dispose();result.add(new T.Mesh(this.geo(geo),mat));}return result;}
 monster(kind:EnemyKind){const g=new T.Group(),caster=kind==='caster',hound=kind==='hound',large=kind==='brute'||kind==='titan';const flesh=this.mat(caster?0x4d7761:hound?0xb84435:large?0x82372e:0xaa5140),armor=this.mat(large?0x393746:0x392936),bone=this.mat(colors.bone),eyes=this.basic(caster?0xa5ff9e:0xffbc46);
  const torso=this.box(g,large?1.15:.72,large?1.05:.85,.52,0,1.1,0,flesh);torso.rotation.x=hound?-.45:-.09;this.box(g,.58,.25,.58,0,1.51,-.01,armor);this.box(g,.55,.52,.46,0,1.88,-.04,flesh);this.box(g,.43,.18,.32,0,1.64,-.19,bone);this.box(g,.45,.085,.055,0,1.91,-.29,eyes);this.box(g,.04,.1,.1,0,1.91,-.3,armor);
  for(const side of [-1,1]){const horn=this.cylinder(g,.01,.14,.62,side*.32,2.21,.02,bone,5);horn.rotation.z=-side*.42;horn.rotation.x=-.23;const arm=this.box(g,.27,.83,.32,side*(large?.73:.52),1.17,-.03,flesh);arm.rotation.z=side*.18;this.box(g,.37,.22,.4,side*(large?.73:.52),.82,-.12,armor);for(let i=0;i<3;i++)this.cylinder(g,.015,.035,.24,side*(large?.73:.52)+(i-1)*.085,.64,-.23,bone,4);
   const leg=this.box(g,.27,.7,.33,side*.24,.36,.05,flesh);leg.rotation.x=side*.12;this.box(g,.35,.18,.51,side*.25,.095,-.08,armor);if(large){this.box(g,.5,.3,.6,side*.76,1.58,0,armor);const spike=this.cylinder(g,0,.12,.45,side*.82,1.9,0,bone,4);spike.rotation.z=-side*.3;}
  }
  if(caster){const orb=new T.Mesh(this.geo(new T.IcosahedronGeometry(.22,1)),eyes);orb.position.set(0,1.12,-.45);g.add(orb);}if(kind==='titan'){this.box(g,.46,.49,.08,0,1.24,-.3,eyes);for(const side of [-1,1])this.cylinder(g,0,.2,.85,side*.15,2.5,.07,bone,5);}
  const model=this.merge(g);model.scale.setScalar(kind==='titan'?2:kind==='brute'?1.4:hound?.7:1);if(hound)model.scale.z=1.3;return model;
 }
 buildGun(){this.gun.clear();const cached=this.gunCache.get(this.world.player.weapon);if(cached){this.gun.add(...cached);this.weapon=this.world.player.weapon;return;}const steel=this.mat(0x555e6d,{metalness:.75,roughness:.4}),dark=this.mat(0x1d222c,{metalness:.7}),edge=this.mat(0x87919e,{metalness:.8,roughness:.35}),skin=this.mat(0x856450),glove=this.mat(0x252b32),orange=this.basic(0xff8d3d);const id=this.world.player.weapon;this.weapon=id;
  this.box(this.gun,.25,.25,.46,.13,-.08,.15,dark);this.box(this.gun,.27,.15,.65,.1,.08,-.16,steel);const count=id===1?2:id===2?5:1;
  for(let i=0;i<count;i++){const x=id===1?(i-.5)*.105:id===2?Math.sin(i*Math.PI*2/5)*.085:0,y=id===2?Math.cos(i*Math.PI*2/5)*.085:0;const barrel=this.cylinder(this.gun,.052,.06,id===0?.36:.72,.1+x,.1+y,id===0?-.54:-.65,edge,10);barrel.rotation.x=Math.PI/2;const hole=this.cylinder(this.gun,.038,.038,.014,.1+x,.1+y,id===0?-.727:-1.018,dark,10);hole.rotation.x=Math.PI/2;}
  if(id===1){for(let i=0;i<7;i++)this.box(this.gun,.31,.12,.035,.1,-.025,-.4-i*.045,dark);this.box(this.gun,.04,.06,.055,.1,.21,-.74,orange);}else if(id===2){this.box(this.gun,.38,.3,.33,-.09,-.055,-.22,dark);for(let i=0;i<5;i++)this.box(this.gun,.07,.1,.09,-.29-i*.035,-.03,-.22,orange);}else this.box(this.gun,.04,.035,.045,.1,.18,-.49,orange);
  this.box(this.gun,.17,.26,.19,.12,-.22,.19,glove).rotation.z=-.16;this.box(this.gun,.21,.18,.42,.23,-.31,.35,skin).rotation.z=-.25;
  if(id!==0){this.box(this.gun,.2,.16,.22,-.055,-.15,-.43,glove);this.box(this.gun,.21,.18,.5,-.2,-.23,-.22,skin).rotation.y=-.45;}this.gun.position.set(.18,-.36,-.38);this.gunCache.set(id,[...this.gun.children]);
 }
 pickup(item:Pickup){const cached=this.lootTemplates.get(item.kind);if(cached)return cached.clone();const g=new T.Group();const col=item.kind==='health'?0x7cffb0:item.kind==='ammo'?0xffc06f:0x84c9ff,glow=this.basic(col),body=this.mat(0x303746);this.box(g,.55,.38,.4,0,.28,0,body);if(item.kind==='health'){this.box(g,.34,.1,.04,0,.3,.22,glow);this.box(g,.1,.3,.04,0,.3,.225,glow);}else for(let i=0;i<3;i++)this.box(g,.06,.23,.04,(i-1)*.12,.3,.22,glow);const ring=new T.Mesh(this.geo(new T.TorusGeometry(.45,.016,3,24)),glow);ring.rotation.x=Math.PI/2;ring.position.y=-.16;g.add(ring);this.lootTemplates.set(item.kind,g);return g.clone();}
 resize(){const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;this.width=r.width;this.height=r.height;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=this.gunCamera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.gunCamera.updateProjectionMatrix();}
 draw(dt:number){this.time+=dt;const w=this.world,p=w.player;const title=w.phase==='title';if(title){this.camera.position.set(4+Math.sin(this.time*.07)*2,9,18);this.camera.lookAt(-1,2,-8);}else{const moving=Math.hypot(p.x-this.lastX,p.z-this.lastZ)>.001;if(w.phase==='playing'&&moving)this.bob+=dt*11;this.camera.position.set(p.x,1.65+(moving?Math.sin(this.bob)*.035:0),p.z);this.camera.rotation.set(0,p.yaw,Math.sin(this.time*70)*w.shake*.04,'YXZ');this.camera.fov=78+(p.dashTime>0?8:0);this.camera.updateProjectionMatrix();}this.lastX=p.x;this.lastZ=p.z;
  for(const [i,g] of this.portals.entries()){(g.userData.energy.material as T.MeshBasicMaterial).opacity=.36+Math.sin(this.time*3+i)*.08;(g.userData.ring as T.Mesh).rotation.z=Math.sin(this.time*.5)*.025;}
  const ids=new Set(w.enemies.map(e=>e.id));for(const [id,obj] of this.objects)if(!ids.has(id)){this.scene.remove(obj);this.objects.delete(id);}
  let shadows=0;for(const e of w.enemies){let obj=this.objects.get(e.id);if(!obj){obj=this.templates.get(e.kind)!.clone();this.objects.set(e.id,obj);this.scene.add(obj);}obj.position.set(e.x,Math.sin(e.age*(e.kind==='hound'?17:9))*.055,e.z);obj.rotation.y=Math.atan2(p.x-e.x,p.z-e.z)+Math.PI;const scale=(e.kind==='titan'?2:e.kind==='brute'?1.4:e.kind==='hound'?.7:1)*Math.min(1,e.age/.55);obj.scale.set(scale,scale*(e.flash>0?.94:1),e.kind==='hound'?scale*1.6:scale);
   this.dummy.position.set(e.x,.014,e.z);this.dummy.rotation.set(-Math.PI/2,0,0);this.dummy.scale.setScalar(e.radius*1.55);this.dummy.updateMatrix();this.shadowMesh.setMatrixAt(shadows++,this.dummy.matrix);
  }this.shadowMesh.count=shadows;this.shadowMesh.instanceMatrix.needsUpdate=true;
  const bullets=new Set(w.bullets.map(b=>b.id));for(const [id,obj] of this.shots)if(!bullets.has(id)){this.scene.remove(obj);this.shots.delete(id);}for(const b of w.bullets){let obj=this.shots.get(b.id);if(!obj){this.bulletTemplate??=new T.Mesh(this.geo(new T.IcosahedronGeometry(.21,0)),this.basic(0xaeff78));obj=this.bulletTemplate.clone();this.shots.set(b.id,obj);this.scene.add(obj);}obj.position.set(b.x,1.2,b.z);obj.rotation.y=this.time*7;}
  const lootIds=new Set(w.pickups.map(i=>i.id));for(const [id,obj] of this.loot)if(!lootIds.has(id)){this.scene.remove(obj);this.loot.delete(id);}for(const item of w.pickups){let obj=this.loot.get(item.id);if(!obj){obj=this.pickup(item);this.loot.set(item.id,obj);this.scene.add(obj);}obj.position.set(item.x,.42+Math.sin(this.time*3+item.id)*.1,item.z);obj.rotation.y=this.time*.8;obj.visible=item.life>4||Math.floor(this.time*6)%2===0;}
  this.particleMesh.count=w.particles.length;for(const [i,fx] of w.particles.entries()){this.dummy.position.set(fx.x,fx.y,fx.z);this.dummy.rotation.set(this.time,fx.id,0);this.dummy.scale.setScalar(Math.max(.3,fx.life*2));this.dummy.updateMatrix();this.particleMesh.setMatrixAt(i,this.dummy.matrix);this.particleMesh.setColorAt(i,new T.Color(fx.color));}this.particleMesh.instanceMatrix.needsUpdate=true;if(this.particleMesh.instanceColor)this.particleMesh.instanceColor.needsUpdate=true;
  this.renderer.clear();this.renderer.render(this.scene,this.camera);
  if(!title){if(this.weapon!==p.weapon)this.buildGun();this.gun.position.set(.13+Math.sin(this.bob*.5)*.012,-.37+Math.cos(this.bob)*.014-w.shotFlash*.5,-.38+w.shotFlash*.8);this.gun.rotation.x=w.shotFlash*.9;this.muzzle.visible=w.shotFlash>.045;this.muzzle.position.set(.20,-.29,-1.12);this.muzzle.scale.set(1+Math.sin(this.time*113)*.4,1,1.5);this.muzzle.rotation.z=this.time*25;this.gunLight.intensity=this.muzzle.visible?6:0;this.renderer.clearDepth();this.renderer.render(this.gunScene,this.gunCamera);}
 }
 dispose(){for(const g of this.geometries)g.dispose();for(const m of this.materials)m.dispose();for(const t of this.textures)t.dispose();this.renderer.dispose();this.renderer.forceContextLoss();}
}
