import type {EngineModule,SessionOptions,RuntimeSession} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {World,readLevel,WEAPONS,UPGRADES,difficulty,type Upgrade,type Controls} from './world.ts';
import {Renderer} from './renderer.ts';
import {AudioEngine} from './audio.ts';
const time=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,'0')}:${Math.floor(seconds%60).toString().padStart(2,'0')}`;
export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');const root=options.container;const oldTitle=document.title;document.title=options.snapshot.manifest.name;root.classList.add('hellrift');
 root.innerHTML=`<canvas class="h-canvas" tabindex="0" aria-label="Разлом — шутер от первого лица"></canvas><div class="h-vignette"></div><div class="h-grain"></div><div class="h-damage"></div>
 <section class="h-title"><header><a class="h-brand" href="https://gadaev-sergey.github.io/shelter-arcade/" target="_blank" rel="noopener">SHELTER <i>/</i> ARCADE</a><span class="h-live"><i></i> СИГНАЛ ПОТЕРЯН · СЕКТОР 09</span><button data-action="sound" class="h-icon" aria-label="Выключить звук">ЗВУК ВКЛ.</button></header>
 <div class="h-intro"><div class="h-eyebrow"><i></i> БЕСКОНЕЧНЫЙ ШУТЕР ОТ ПЕРВОГО ЛИЦА</div><h1>РАЗЛОМ<span>ПОСЛЕДНИЙ РУБЕЖ</span></h1><p>Врата открыты. Подкрепления не будет.<br>У тебя есть оружие. У них — вечность.</p><button class="h-primary" data-action="start">ВОЙТИ В РАЗЛОМ <span>↗</span></button><div class="h-record">ЛИЧНЫЙ РЕКОРД <b data-best>00:00</b><span data-best-kills>0 УБИЙСТВ</span></div></div>
 <div class="h-stamp"><span>ПРОТОКОЛ ВЫЖИВАНИЯ</span><strong>∞</strong><p>НЕТ ПОСЛЕДНЕЙ ВОЛНЫ.<br>ЕСТЬ ТОЛЬКО ТВОЙ РЕКОРД.</p><i></i><small>СОБОР ПЕПЛА<br>59° N / 034° E</small></div>
 <footer><div><b>01</b> АРЕНА <i>/</i> <b>03</b> СТВОЛА <i>/</i> <b>∞</b> МОНСТРОВ</div><button class="h-text" data-action="help">УПРАВЛЕНИЕ И ПРАВИЛА ↗</button></footer></section>
 <div class="h-hud" hidden><header class="h-top"><div class="h-location"><span class="h-mark">R<span> / </span>09</span><div><small>РАЗЛОМ АКТИВЕН</small><strong>СОБОР ПЕПЛА</strong></div></div><div class="h-timer"><small>ВРЕМЯ ВЫЖИВАНИЯ</small><b data-time>00:00</b><div><i data-pressure></i></div></div><div class="h-actions"><div class="h-kills"><b data-kills>0</b><small>УБИЙСТВ</small></div><button data-action="sound" class="h-icon" aria-label="Выключить звук">♪</button><button data-action="pause" class="h-icon" aria-label="Пауза">Ⅱ</button></div></header>
 <div class="h-threat"><span>УРОВЕНЬ УГРОЗЫ <b data-tier>01</b></span><span data-enemies>4 ДЕМОНА</span></div><div class="h-boss" hidden><span>ТИТАН РАЗЛОМА</span><div><i></i></div></div><div class="h-crosshair"><i></i><i></i><i></i><i></i><b>×</b></div><div class="h-banner" role="status"></div><div class="h-hint"></div>
 <div class="h-radar"><canvas width="130" height="130" aria-label="Радар ближайших демонов"></canvas><span>РАДАР / 360°</span></div>
 <footer class="h-bottom"><div class="h-health"><small>✚ ЗДОРОВЬЕ</small><strong data-hp>100</strong><div><i data-health-bar></i></div><span>БРОНЯ <b data-armor>40</b></span></div><div class="h-dash"><kbd>SHIFT</kbd><div><b data-dash>ГОТОВ</b><small>РЫВОК</small></div></div><div class="h-arsenal"><div class="h-slots"><button data-weapon="0">1 <span>ИСКРА</span></button><button data-weapon="1" class="selected">2 <span>ПАЛАЧ</span></button><button data-weapon="2">3 <span>МОЛОХ</span></button></div><div class="h-ammo"><div><small data-weapon-type>ДРОБОВИК</small><b data-weapon-name>ПАЛАЧ</b></div><strong data-ammo>28</strong></div></div></footer></div>
 <section class="h-modal" hidden role="dialog" aria-modal="true" aria-labelledby="h-modal-title"><div class="h-panel"></div></section>
 <div class="h-touch" hidden><div class="h-stick" data-stick="move"><i></i><span>ХОД</span></div><div class="h-touch-actions"><button data-action="touch-weapon">1 / 2 / 3</button><button data-action="touch-dash">РЫВОК</button></div><div class="h-stick h-aim" data-stick="aim"><i></i><span>ОБЗОР + ОГОНЬ</span></div></div>`;
 const $=<E extends HTMLElement=HTMLElement>(q:string)=>root.querySelector<E>(q)!;const canvas=$<HTMLCanvasElement>('.h-canvas'),world=new World(readLevel(options.snapshot.scenes[options.sceneId])),audio=new AudioEngine();let renderer:Renderer;
 try{renderer=new Renderer(canvas,world);}catch(error){root.innerHTML='<div style="padding:40px;color:white;background:#17131b">Для Разлома нужен браузер с WebGL. Включите аппаратное ускорение и перезагрузите страницу.</div>';throw error;}
 const abort=new AbortController(),keys=new Set<string>();let touch=matchMedia('(pointer:coarse)').matches;root.classList.toggle('h-mobile',touch);
 const recordKey=storageKey(options.snapshot.manifest.projectId,'record','survival'),settingsKey=storageKey(options.snapshot.manifest.projectId,'settings','audio');let best={seconds:0,kills:0},disposed=false,frame=0,previous=performance.now(),acc=0,ui=0,lastPhase='',modal='',fire=false,dash=false,weapon=-1,move={x:0,y:0},aim=0,aiming=false,recorded=false,drag=false,lastPointerX=0;
 if(options.savePolicy==='persistent')try{const record=JSON.parse(localStorage.getItem(recordKey)||'null');if(record&&Number.isFinite(record.seconds)&&record.seconds>=0&&Number.isFinite(record.kills)&&record.kills>=0)best=record;audio.setMuted(localStorage.getItem(settingsKey)==='muted');}catch{}
 const listen=(el:EventTarget,event:string,fn:EventListener)=>el.addEventListener(event,fn,{signal:abort.signal});
 function clear(){keys.clear();fire=dash=aiming=drag=false;weapon=-1;move={x:0,y:0};aim=0;root.querySelectorAll<HTMLElement>('.h-stick i').forEach(i=>i.style.transform='translate(-50%,-50%)');}
 function unlockPointer(){if(document.pointerLockElement===canvas)document.exitPointerLock();}
 function lockPointer(){if(touch)return;try{const result=canvas.requestPointerLock?.();if(result)void result.catch(()=>{});}catch{}}
 function hide(){modal='';$('.h-modal').hidden=true;clear();canvas.focus({preventScroll:true});}
 function resume(){world.pause(false);hide();lockPointer();update();}
 function pause(){if(world.phase!=='playing')return;world.pause(true);clear();show('pause');unlockPointer();update();}
 function start(){void audio.unlock();world.start();recorded=false;hide();lockPointer();update();}
 function saveRecord(){if(recorded)return;recorded=true;if(world.seconds>best.seconds){best={seconds:world.seconds,kills:world.kills};if(options.savePolicy==='persistent')try{localStorage.setItem(recordKey,JSON.stringify(best));}catch{}}}
 const button=(action:string,label:string,primary=false)=>`<button class="${primary?'h-primary':'h-secondary'}" data-action="${action}">${label}${primary?'<span>↗</span>':''}</button>`;
 function show(kind:string){modal=kind;clear();const panel=$('.h-panel');$('.h-modal').hidden=false;panel.classList.toggle('h-wide',kind==='upgrade');
  if(kind==='pause')panel.innerHTML=`<div class="h-eyebrow">ОРДА ПОДОЖДЁТ</div><h2 id="h-modal-title">ПАУЗА</h2><p>${time(world.seconds)} в разломе · ${world.kills} убийств</p>${button('resume','ПРОДОЛЖИТЬ',true)}${button('help','Управление и правила')}${button('title','В главное меню')}<small>ESC / P — продолжить. Удерживай ЛКМ, чтобы стрелять.</small>`;
  if(kind==='help')panel.innerHTML=`<div class="h-eyebrow">ПРОТОКОЛ ВЫЖИВАНИЯ</div><h2 id="h-modal-title">ДВИГАЙСЯ.<br>СТРЕЛЯЙ. ЖИВИ.</h2><div class="h-controls"><span><kbd>W A S D</kbd> Движение</span><span><kbd>МЫШЬ / ← →</kbd> Поворот</span><span><kbd>ЛКМ / ПРОБЕЛ</kbd> Огонь</span><span><kbd>SHIFT</kbd> Рывок с неуязвимостью</span><span><kbd>1 / 2 / 3</kbd> Смена оружия</span><span><kbd>ESC / P</kbd> Пауза</span></div><p>Пистолет имеет бесконечные патроны. Дробовик особенно силён вблизи. Пулемёт открывается на 60-й секунде. Перезарядка автоматическая.</p><p>Собирай зелёные аптечки, янтарные патроны и синюю броню. Каждые 45 секунд выбирай улучшение. Каждые 90 секунд приходит титан. Укрытия задерживают выстрелы. Время на паузе не засчитывается.</p><small>Сенсорный экран: левый круг — движение; правый — поворот и огонь. Без захвата мыши: зажми ЛКМ и веди в сторону. Прицел по высоте автоматический, как в классических шутерах.</small>${button('touch-toggle',touch?'Сенсорное управление: включено':'Включить сенсорное управление')}${button('back','ПОНЯТНО',true)}`;
  if(kind==='upgrade')panel.innerHTML=`<div class="h-eyebrow">${time(world.seconds)} · ТЫ ВСЁ ЕЩЁ ЗДЕСЬ</div><h2 id="h-modal-title">СТАНЬ ОПАСНЕЕ.</h2><p>Выбери одно улучшение. Бой приостановлен. Любой выбор даёт +15 здоровья.</p><div class="h-upgrades">${world.choices.map((id,i)=>`<button data-upgrade="${id}"><div><b>${UPGRADES[id].icon}</b><small>0${i+1} / МОДИФИКАЦИЯ</small></div><strong>${UPGRADES[id].name}</strong><p>${UPGRADES[id].detail}</p><footer>ПРИНЯТЬ <span>↗</span></footer></button>`).join('')}</div>`;
  if(kind==='dead'){const record=world.seconds>=best.seconds;panel.innerHTML=`<div class="h-eyebrow">${record?'НОВЫЙ ЛИЧНЫЙ РЕКОРД':'СВЯЗЬ С БОЙЦОМ ПОТЕРЯНА'}</div><h2 id="h-modal-title">РУБЕЖ ПАЛ.</h2><p>Ты забрал с собой ${world.kills} демонов.<br>В следующий раз — ещё больше.</p><div class="h-results"><div><b>${time(world.seconds)}</b><span>ВРЕМЯ ВЫЖИВАНИЯ</span></div><div><b>${world.kills}</b><span>УБИЙСТВ</span></div><div><b>${world.score.toLocaleString('ru-RU')}</b><span>ОЧКОВ</span></div></div>${button('start','ЕЩЁ ОДНА ПОПЫТКА',true)}${button('title','В главное меню')}<small>Личный рекорд: ${time(best.seconds)} · ${best.kills} убийств</small>`;}
  requestAnimationFrame(()=>{if(!disposed)panel.querySelector<HTMLButtonElement>('button')?.focus();});
 }
 function radar(){const ctx=$<HTMLCanvasElement>('.h-radar canvas').getContext('2d')!,p=world.player;ctx.clearRect(0,0,130,130);ctx.strokeStyle='#8b817555';for(const r of [24,49]){ctx.beginPath();ctx.arc(65,65,r,0,Math.PI*2);ctx.stroke();}ctx.beginPath();ctx.moveTo(65,12);ctx.lineTo(65,118);ctx.moveTo(12,65);ctx.lineTo(118,65);ctx.stroke();for(const e of world.enemies){const dx=e.x-p.x,dz=e.z-p.z,s=Math.sin(p.yaw),c=Math.cos(p.yaw);let x=(dx*c-dz*s)*2,y=(dx*s+dz*c)*2;const d=Math.hypot(x,y);if(d>51){x*=51/d;y*=51/d;}ctx.fillStyle=e.kind==='titan'?'#ffc078':'#f76347';ctx.fillRect(64+x,64+y,e.kind==='titan'?5:3,e.kind==='titan'?5:3);}ctx.fillStyle='#efe9dc';ctx.beginPath();ctx.moveTo(65,59);ctx.lineTo(61,69);ctx.lineTo(69,69);ctx.fill();}
 function update(){const title=world.phase==='title',p=world.player;$('.h-title').hidden=!title;$('.h-hud').hidden=title;$('.h-touch').hidden=!touch||world.phase!=='playing';root.classList.toggle('h-playing',world.phase==='playing');$('[data-best]').textContent=time(best.seconds);$('[data-best-kills]').textContent=`${best.kills} УБИЙСТВ`;$('[data-time]').textContent=time(world.seconds);$('[data-kills]').textContent=String(world.kills);$('[data-tier]').textContent=String(difficulty(world.seconds).tier).padStart(2,'0');$('[data-enemies]').textContent=`В СОБОРЕ: ${world.enemies.length}`;$('[data-pressure]').style.width=`${(world.seconds%30)/30*100}%`;
  $('[data-hp]').textContent=String(Math.ceil(p.hp));$('[data-armor]').textContent=String(Math.ceil(p.armor));$('[data-health-bar]').style.width=`${p.hp/world.maxHP*100}%`;$('.h-health').classList.toggle('low',p.hp<30);$('[data-dash]').textContent=p.dashCD>0?p.dashCD.toFixed(1)+' С':'ГОТОВ';$('.h-dash').classList.toggle('cooldown',p.dashCD>0);$('[data-ammo]').textContent=p.weapon===0?'∞':String(p.ammo[p.weapon]);$('[data-weapon-name]').textContent=WEAPONS[p.weapon].name;$('[data-weapon-type]').textContent=WEAPONS[p.weapon].type;
  root.querySelectorAll<HTMLButtonElement>('[data-weapon]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.weapon)===p.weapon);b.disabled=b.dataset.weapon==='2'&&!world.unlocked;b.title=b.disabled?'Откроется на 60-й секунде':WEAPONS[Number(b.dataset.weapon)].type;});
  const boss=world.enemies.find(e=>e.kind==='titan');$('.h-boss').hidden=!boss;if(boss)$('.h-boss i').style.width=`${boss.hp/boss.maxHP*100}%`;$('.h-banner').textContent=world.banner;$('.h-banner').classList.toggle('show',world.bannerTime>0&&world.phase==='playing');$('.h-hint').textContent=world.seconds<16?(touch?'Двигайся левым кругом · целься и стреляй правым':'W A S D — движение    ЛКМ — огонь    SHIFT — рывок'):(world.phase==='playing'&&!touch&&document.pointerLockElement!==canvas?'Нажми на арену для захвата мыши · ← → тоже поворачивают':'');
  root.querySelectorAll<HTMLButtonElement>('[data-action="sound"]').forEach(b=>{b.setAttribute('aria-label',audio.muted?'Включить звук':'Выключить звук');b.setAttribute('aria-pressed',String(!audio.muted));b.textContent=b.closest('.h-title')?(audio.muted?'ЗВУК ВЫКЛ.':'ЗВУК ВКЛ.'):(audio.muted?'×♪':'♪');});radar();
  if(world.phase==='dead'&&!recorded)saveRecord();if(['upgrade','dead'].includes(world.phase)&&modal!==world.phase){show(world.phase);unlockPointer();}
 }
 function sound(){void audio.unlock();audio.setMuted(!audio.muted);if(options.savePolicy==='persistent')try{localStorage.setItem(settingsKey,audio.muted?'muted':'on');}catch{}update();}
 listen(root,'click',((event:MouseEvent)=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;const action=b.dataset.action;if(action==='start')start();if(action==='resume')resume();if(action==='pause')pause();if(action==='sound')sound();if(action==='help'){world.pause(true);show('help');unlockPointer();}if(action==='back'){if(world.phase==='paused')show('pause');else hide();}if(action==='title'){world.phase='title';hide();unlockPointer();}if(action==='touch-toggle'){touch=!touch;root.classList.toggle('h-mobile',touch);show('help');}if(action==='touch-dash')dash=true;if(action==='touch-weapon')weapon=(world.player.weapon+1)%(world.unlocked?3:2);if(b.dataset.weapon!==undefined){weapon=Number(b.dataset.weapon);canvas.focus();}if(b.dataset.upgrade){world.choose(b.dataset.upgrade as Upgrade);hide();lockPointer();}update();}) as EventListener);
 listen(window,'keydown',((event:KeyboardEvent)=>{if(event.metaKey||event.ctrlKey||event.altKey)return;const code=event.code;if(!['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','Digit1','Digit2','Digit3','Escape','KeyP','KeyM'].includes(code))return;
  if(code==='Escape'||code==='KeyP'){event.preventDefault();if(event.repeat)return;if(modal==='help'){world.phase==='paused'?show('pause'):hide();}else if(world.phase==='paused')resume();else pause();return;}if(code==='KeyM'&&!event.repeat){sound();return;}if(world.phase!=='playing')return;event.preventDefault();keys.add(code);if(!event.repeat){if(code.startsWith('Shift'))dash=true;if(code.startsWith('Digit'))weapon=Number(code.slice(-1))-1;}}) as EventListener);
 listen(window,'keyup',((e:KeyboardEvent)=>{keys.delete(e.code);}) as EventListener);
 listen(canvas,'pointerdown',((e:PointerEvent)=>{if(world.phase!=='playing'||e.pointerType==='touch')return;e.preventDefault();canvas.focus();void audio.unlock();if(e.button===0){fire=true;drag=true;lastPointerX=e.clientX;lockPointer();}}) as EventListener);
 listen(window,'pointerup',()=>{fire=false;drag=false;});listen(canvas,'pointercancel',()=>{fire=false;drag=false;});listen(canvas,'contextmenu',e=>e.preventDefault());
 listen(document,'mousemove',((e:MouseEvent)=>{if(world.phase!=='playing')return;if(document.pointerLockElement===canvas)world.player.yaw-=e.movementX*.0025;else if(drag){world.player.yaw-=(e.clientX-lastPointerX)*.005;lastPointerX=e.clientX;}}) as EventListener);
 listen(document,'pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&world.phase==='playing'&&!touch)pause();});
 listen(window,'blur',()=>{clear();pause();});listen(document,'visibilitychange',()=>{if(document.hidden){clear();pause();}});
 for(const stick of root.querySelectorAll<HTMLElement>('[data-stick]')){let pid=-1;const set=(e:PointerEvent)=>{const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.max(34,Math.hypot(dx,dy)),x=dx/l,y=dy/l;stick.querySelector<HTMLElement>('i')!.style.transform=`translate(calc(-50% + ${x*32}px),calc(-50% + ${y*32}px))`;if(stick.dataset.stick==='move')move={x,y};else{aim=-x;aiming=true;}};listen(stick,'pointerdown',((e:PointerEvent)=>{e.preventDefault();pid=e.pointerId;stick.setPointerCapture(pid);set(e);void audio.unlock();}) as EventListener);listen(stick,'pointermove',((e:PointerEvent)=>{if(pid===e.pointerId)set(e);}) as EventListener);const end=(e:Event)=>{if((e as PointerEvent).pointerId!==pid)return;pid=-1;if(stick.dataset.stick==='move')move={x:0,y:0};else{aim=0;aiming=false;}stick.querySelector<HTMLElement>('i')!.style.transform='translate(-50%,-50%)';};for(const type of ['pointerup','pointercancel','lostpointercapture'])listen(stick,type,end);}
 listen(root,'keydown',((e:KeyboardEvent)=>{if(e.key!=='Tab'||$('.h-modal').hidden)return;const b=[...$('.h-panel').querySelectorAll<HTMLButtonElement>('button')],first=b[0],last=b.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}) as EventListener);
 const observer=new ResizeObserver(()=>renderer.resize());observer.observe(canvas);world.onSound=n=>audio.play(n);
 const controls=():Controls=>({forward:Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown'))-move.y,strafe:Number(keys.has('KeyD'))-Number(keys.has('KeyA'))+move.x,turn:Number(keys.has('ArrowLeft')||keys.has('KeyQ'))-Number(keys.has('ArrowRight')||keys.has('KeyE'))+aim,fire:fire||keys.has('Space')||aiming,dash,weapon});
 function tick(now:number){if(disposed)return;const dt=Math.min(.05,(now-previous)/1000);previous=now;acc+=dt;while(acc>=1/120){world.step(1/120,controls());dash=false;weapon=-1;acc-=1/120;}renderer.draw(dt);audio.update(dt,world.phase==='playing',world.seconds);$('.h-damage').style.opacity=String(world.damageFlash*.95);$('.h-crosshair').classList.toggle('hit',world.hitFlash>0);$('.h-crosshair').classList.toggle('kill',world.killFlash>0);ui+=dt;if(ui>.08||lastPhase!==world.phase){lastPhase=world.phase;ui=0;update();}frame=requestAnimationFrame(tick);}
 if(import.meta.env.DEV)Object.defineProperty(window,'__HELLRIFT__',{configurable:true,value:{world,renderer,snapshot:()=>({phase:world.phase,time:world.seconds,kills:world.kills,player:structuredClone(world.player),enemies:world.enemies.length,bullets:world.bullets.length})}});
 update();frame=requestAnimationFrame(tick);
 return {pause(value){if(value)pause();else if(world.phase==='paused')resume();},dispose(){disposed=true;cancelAnimationFrame(frame);abort.abort();observer.disconnect();unlockPointer();audio.dispose();renderer.dispose();root.replaceChildren();root.classList.remove('hellrift','h-playing','h-mobile');document.title=oldTitle;if(import.meta.env.DEV)delete (window as any).__HELLRIFT__;},diagnostics:()=>({game:'hellrift',phase:world.phase,seconds:world.seconds,kills:world.kills,enemies:world.enemies.length})};
}
const module:EngineModule={id:'hellrift',sdk:1,components:[{id:'hellrift.cover',name:'Укрытие Разлома',fields:[{name:'style',label:'Вид',type:'select',default:'bunker',options:[{value:'pillar',label:'Колонна'},{value:'bunker',label:'Бронеблок'}]}]},{id:'hellrift.portal',name:'Портал демонов',fields:[]}],validateScene(scene){readLevel(scene);},createSession:startGame};
export default module;
