import type {EngineModule,SessionOptions,RuntimeSession} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {Puzzle,readLevel,rotatable,trace,COLORS} from './world.ts';
import {boardSvg,hitButtons} from './renderer.ts';
import {Sound} from './audio.ts';

const icon=(content:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${content}</svg>`;
const icons={logo:icon('<path d="m12 3 10 18H2Z"/><path d="m12 3 3 18M2 21l13-8 7 8"/>'),arrow:icon('<path d="M4 12h16m-6-6 6 6-6 6"/>'),undo:icon('<path d="M8 4 3 9l5 5M3 9h10a7 7 0 0 1 0 14"/>'),reset:icon('<path d="M20 7v5h-5M4 17v-5h5M5 7a8 8 0 0 1 14 0m0 10a8 8 0 0 1-14 0"/>'),hint:icon('<path d="M9 18v-3a6 6 0 1 1 6 0v3ZM9 21h6M10 18h4"/>'),levels:icon('<rect x="3" y="3" width="6" height="6" rx="1"/><rect x="15" y="3" width="6" height="6" rx="1"/><rect x="3" y="15" width="6" height="6" rx="1"/><rect x="15" y="15" width="6" height="6" rx="1"/>'),sound:icon('<path d="M4 9h4l5-5v16l-5-5H4ZM17 8c3 2 3 6 0 8m3-11c5 4 5 10 0 14"/>'),mute:icon('<path d="M4 9h4l5-5v16l-5-5H4ZM17 9l5 6m0-6-5 6"/>')};
const CHAPTERS=['Искусство отражения','Свет делится','Два цвета тишины'];
const numeral=(n:number)=>String(n).padStart(2,'0');
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');
 const root=options.container,oldTitle=document.title;document.title='Призма · Сад света';root.classList.add('prisma-root');
 const levels=options.snapshot.manifest.scenes.map(s=>readLevel(options.snapshot.scenes[s.id]));
 const key=storageKey(options.snapshot.manifest.projectId,'progress',options.snapshot.manifest.build.appId),soundKey=storageKey(options.snapshot.manifest.projectId,'sound');
 const stars=levels.map(()=>0),states:Array<ReturnType<Puzzle['save']>|null>=levels.map(()=>null);
 let current=Math.max(0,levels.findIndex(l=>l.id===options.sceneId)),hasSave=false,saveFailed=false,active=false,paused=false,disposed=false,hinted:string|null=null;
 const unlocked=()=>{const first=stars.findIndex(s=>s===0);return first<0?levels.length-1:first;};
 if(options.savePolicy==='persistent')try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.version===1&&Array.isArray(saved.stars)&&saved.stars.length===levels.length&&saved.stars.every((s:unknown)=>Number.isInteger(s)&&Number(s)>=0&&Number(s)<=3)&&Number.isInteger(saved.current)&&saved.current>=0&&saved.current<levels.length&&Array.isArray(saved.states)&&saved.states.length===levels.length){stars.splice(0,stars.length,...saved.stars);current=Math.min(saved.current,unlocked());states.splice(0,states.length,...saved.states);hasSave=true;}}catch{}
 let puzzle=new Puzzle(levels[current]);if(states[current])puzzle.restore(states[current]);
 const sound=new Sound();if(options.savePolicy==='persistent')try{sound.muted=localStorage.getItem(soundKey)==='off';}catch{}
 root.innerHTML=`<div class="prisma-atmosphere" aria-hidden="true"></div>
 <header class="prisma-header"><a class="brand" href="#" data-home>${icons.logo}<span>ПРИЗМА<small>САД СВЕТА</small></span></a><div class="header-caption">НЕБОЛЬШАЯ ИГРА О БОЛЬШИХ ОТКРЫТИЯХ</div><nav aria-label="Настройки"><button class="icon-button" data-action="sound" aria-label="Выключить звук"></button><button class="icon-button" data-action="help" aria-label="Как играть">?</button><button class="icon-button" data-action="levels" aria-label="Выбор уровня">${icons.levels}</button></nav></header>
 <section class="prisma-title"><div class="title-copy"><div class="eyebrow"><span class="tiny-sun">✦</span> ОПТИЧЕСКАЯ ГОЛОВОЛОМКА</div><h1>Всё начинается<br>с одного<br><em>луча.</em></h1><p>Поворачивайте зеркала, разделяйте свет<br class="desktop-break"> и зажигайте маленькие созвездия.</p><button class="primary" data-action="start"><span>${hasSave?'Продолжить путь':'Впустить свет'}</span>${icons.arrow}</button><div class="title-facts"><span>12 композиций</span><i></i><span>Без спешки</span><i></i><span>В вашем ритме</span></div></div><div class="title-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="demo-board"></div><div class="art-caption"><span>ЭТЮД № 11</span><span>СВЕТ ВСЕГДА НАЙДЁТ ПУТЬ</span></div></div></section>
 <main class="prisma-game" hidden><aside class="level-sidebar"><div class="eyebrow" data-chapter></div><div class="level-heading"><span class="level-number" data-number></span><div><span class="eyebrow">КОМПОЗИЦИЯ</span><h1 data-level-name></h1></div></div><p class="level-caption" data-caption></p><div class="chapter-progress" aria-label="Прогресс кампании" data-progress></div><section class="objective"><div class="eyebrow">ПУСТЬ СВЕТ ДОЙДЁТ ДО ЦЕЛИ</div><h2>Зажгите все огни</h2><div class="target-list" data-targets></div></section><section class="lesson"><span class="lesson-symbol">✧</span><p data-lesson></p></section><section class="completion" hidden><div class="eyebrow">КОМПОЗИЦИЯ ЗАВЕРШЕНА</div><h2>Свет найден.</h2><div class="earned-stars" aria-label="Звёзды за уровень"></div><button class="primary" data-action="next">Дальше ${icons.arrow}</button></section><button class="level-select" data-action="levels">${icons.levels} Все композиции <span>↗</span></button></aside>
 <section class="board-section" aria-label="Игровое поле"><div class="board-topline"><span><i></i> ОПТИЧЕСКИЙ СТОЛ</span><span class="receiver-count" data-receiver-count></span></div><div class="board-wrap"><div class="board-svg"></div><div class="board-inputs" role="group" aria-label="Зеркала и разделители. Нажмите, чтобы повернуть."></div></div><div class="board-under"><span class="board-instruction" data-board-instruction>Нажмите на зеркало, чтобы повернуть</span><span class="board-coordinate" data-dimensions></span></div><div class="board-toolbar"><div class="move-counter"><strong data-moves>0</strong><span>ПОВОРОТОВ<small data-par></small></span></div><div class="tools"><button data-action="undo" title="Отменить · Z">${icons.undo}<span>Отменить</span></button><button data-action="reset" title="Сначала · R">${icons.reset}<span>Сначала</span></button><button data-action="hint" title="Подсказка · H">${icons.hint}<span>Подсказка</span></button></div></div></section>
 <aside class="field-notes"><span class="eyebrow">ПОЛЕВЫЕ ЗАМЕТКИ</span><div class="legend-item"><span class="legend-source">▸</span><div><b>Источник</b><small>Отсюда начинается свет</small></div></div><div class="legend-item"><span class="legend-mirror">╱</span><div><b>Зеркало</b><small>Меняет направление</small></div></div><div class="legend-item"><span class="legend-splitter">◇</span><div><b>Разделитель</b><small>Прямо и в отражение</small></div></div><div class="legend-item"><span class="legend-target">◎</span><div><b>Приёмник</b><small>Ждёт свой цвет</small></div></div><div class="notes-bottom"><span>01 — 12</span><p>Хорошим идеям<br>нужно немного<br><em>пространства.</em></p><div class="mini-prism">${icons.logo}</div></div></aside></main>
 <footer class="prisma-footer"><span>SHELTER ENGINE <i>/</i> PRISMA</span><span data-save>ПРОГРЕСС СОХРАНЯЕТСЯ АВТОМАТИЧЕСКИ</span><span>СОЗДАНО ДЛЯ ЛЮБОПЫТНЫХ</span></footer>
 <div class="prisma-toast" role="status" aria-live="polite"></div><dialog class="prisma-dialog" aria-labelledby="prisma-dialog-title"><div class="dialog-inner"></div></dialog>`;
 const $=<T extends HTMLElement=HTMLElement>(selector:string)=>root.querySelector<T>(selector)!;
 const modal=$<HTMLDialogElement>('dialog'),abort=new AbortController();let toastTimer:ReturnType<typeof setTimeout>|undefined,lastFocus:HTMLElement|null=null;
 const demo=new Puzzle(levels[Math.min(10,levels.length-1)]);$('.demo-board').innerHTML=boardSvg(demo.level,demo.answers[0],trace(demo.level,demo.answers[0]),'demo');
 const save=()=>{states[current]=puzzle.save();if(options.savePolicy!=='persistent')return;try{localStorage.setItem(key,JSON.stringify({version:1,current,stars,states}));}catch{saveFailed=true;$('[data-save]').textContent='СОХРАНЕНИЕ В БРАУЗЕРЕ НЕДОСТУПНО';}};
 const toast=(message:string)=>{const el=$('.prisma-toast');el.textContent=message;el.classList.add('visible');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);};
 const soundUI=()=>{const b=$('[data-action="sound"]');b.innerHTML=sound.muted?icons.mute:icons.sound;b.setAttribute('aria-label',sound.muted?'Включить звук':'Выключить звук');b.setAttribute('aria-pressed',String(!sound.muted));};soundUI();
 const close=()=>{if(modal.open)modal.close();lastFocus?.focus({preventScroll:true});};
 const show=(content:string)=>{if(!modal.open)lastFocus=document.activeElement as HTMLElement;$('.dialog-inner').innerHTML=`<button class="dialog-close icon-button" data-action="close" aria-label="Закрыть">×</button>${content}`;if(!modal.open)modal.showModal();$('.dialog-inner').querySelector<HTMLElement>('button')?.focus();};
 const help=()=>show(`<div class="eyebrow">НЕСКОЛЬКО ПРОСТЫХ ПРАВИЛ</div><h2 id="prisma-dialog-title">Следуйте за светом.</h2><div class="help-rules"><p><b>01. Поверните</b>Нажмите на круглое зеркало. Оно повернётся на 90° и изменит направление луча.</p><p><b>02. Разделите</b>Ромб пропускает луч прямо и отражает вторую ветвь. Его тоже можно поворачивать.</p><p><b>03. Соедините</b>Зажгите все приёмники одновременно. Круг ждёт янтарный свет, ромб — бирюзовый. На пустых клетках лучи пересекаются свободно.</p><p><b>04. Не спешите</b>Нет таймера и проигрыша. Подсказка подсвечивает один элемент, который нужно повернуть.</p></div><p class="dialog-note">★★★ — без подсказок, за оптимальное число поворотов.<br>★★ — без подсказок, с любым числом поворотов.<br>★ — решение с подсказкой. Лучший результат сохраняется.</p><div class="key-guide">Tab — выбрать зеркало · Enter / пробел — повернуть<br>Z — отменить · R — сначала · H — подсказка · M — звук · Esc — композиции</div><button class="primary" data-action="close">Всё понятно ${icons.arrow}</button>`);
 const chooseLevels=()=>show(`<div class="eyebrow">САД СВЕТА · ${stars.filter(Boolean).length} ИЗ ${levels.length}</div><h2 id="prisma-dialog-title">Ваши композиции</h2>${CHAPTERS.map((chapter,c)=>`<section class="chapter-picker"><h3><span>${numeral(c+1)}</span> ${chapter}</h3><div class="level-grid">${levels.map((l,i)=>l.chapter!==c?'':`<button data-level="${i}" ${i>unlocked()?'disabled':''} class="${i===current?'current':''}" aria-label="${numeral(i+1)}. ${escape(l.name)}${i>unlocked()?'. Закрыто':stars[i]?`. Звёзд: ${stars[i]}`:''}"><b>${numeral(i+1)}</b><span>${escape(l.name)}</span><small>${i>unlocked()?'ЗАКРЫТО':stars[i]?'★'.repeat(stars[i])+'☆'.repeat(3-stars[i]):'ПОПРОБОВАТЬ'}</small></button>`).join('')}</div></section>`).join('')}<p class="dialog-note">Следующая композиция открывается после решения предыдущей. К пройденным можно вернуться в любое время.</p>`);
 const finale=()=>show(`<div class="finale-prism">${icons.logo}</div><div class="eyebrow">ВСЕ ОГНИ ЗАЖЖЕНЫ</div><h2 id="prisma-dialog-title">Теперь здесь<br><em>живёт свет.</em></h2><p>Двенадцать композиций сложились в один сад.<br>Спасибо, что дали свету найти свой путь.</p><div class="finale-score"><strong>${stars.reduce((a,b)=>a+b,0)}</strong><span>ИЗ ${levels.length*3} ЗВЁЗД<br>В ВАШЕМ СОЗВЕЗДИИ</span></div><button class="primary" data-action="levels">Вернуться к композициям ${icons.arrow}</button><button class="secondary" data-action="close">Посмотреть на сад</button>`);
 function render(newLevel=false){
  const l=puzzle.level,r=puzzle.result;
  if(r.won)stars[current]=Math.max(stars[current],puzzle.stars);
  $('.board-svg').innerHTML=boardSvg(l,puzzle.angles,r);
  if(newLevel)$('.board-inputs').innerHTML=hitButtons(l);
  root.querySelectorAll<HTMLButtonElement>('[data-optic]').forEach(b=>{const index=l.pieces.filter(rotatable).findIndex(p=>p.id===b.dataset.optic);b.disabled=r.won;b.classList.toggle('hinted',b.dataset.optic===hinted);b.setAttribute('aria-pressed',String(puzzle.angles[index]===1));});
  $('[data-chapter]').textContent=`ГЛАВА ${numeral(l.chapter+1)} / ${CHAPTERS[l.chapter].toUpperCase()}`;
  $('[data-number]').textContent=numeral(current+1);$('[data-level-name]').textContent=l.name;$('[data-caption]').textContent=l.caption;$('[data-lesson]').textContent=l.lesson;
  $('[data-progress]').innerHTML=levels.map((_,i)=>`<span class="${stars[i]?'done ':''}${i===current?'current':''}" title="Композиция ${i+1}"></span>`).join('');
  const targets=l.pieces.filter(p=>p.kind==='target');
  $('[data-targets]').innerHTML=targets.map((p,i)=>`<span class="target-chip ${r.lit.has(p.id)?'lit':''}" style="--light:${COLORS[p.color]}" title="${p.color==='amber'?'Янтарный':'Бирюзовый'} приёмник ${i+1}: ${r.lit.has(p.id)?'горит':'не горит'}">${p.color==='amber'?'◎':'◇'}<small>${numeral(i+1)}</small></span>`).join('');
  $('[data-receiver-count]').textContent=`${r.lit.size} / ${targets.length} ОГНЕЙ`;$('[data-receiver-count]').classList.toggle('complete',r.won);
  $('[data-dimensions]').textContent=`${l.size} × ${l.size}`;$('[data-moves]').textContent=String(puzzle.moves);$('[data-par]').textContent=`ЦЕЛЬ · ${puzzle.par}`;
  $<HTMLButtonElement>('[data-action="undo"]').disabled=puzzle.history.length===0;$<HTMLButtonElement>('[data-action="hint"]').disabled=r.won;
  $('.completion').hidden=!r.won;$('.lesson').hidden=r.won;$('.earned-stars').textContent='★'.repeat(puzzle.stars)+'☆'.repeat(3-puzzle.stars);$('.earned-stars').setAttribute('aria-label',`${puzzle.stars} из 3 звёзд`);
  $('[data-action="next"]').innerHTML=`${current===levels.length-1?'Увидеть весь сад':'Следующая'} ${icons.arrow}`;
  $('[data-board-instruction]').textContent=r.won?'Композиция завершена. Все огни горят.':hinted?'Поверните подсвеченный элемент':r.wrong.size?'Приёмнику нужен луч своего цвета':'Нажмите на зеркало, чтобы повернуть';
  $('.board-wrap').classList.toggle('solved',r.won);
 }
 function begin(index=current){save();current=index;puzzle=new Puzzle(levels[current]);if(states[current])puzzle.restore(states[current]);hinted=null;active=true;root.classList.add('playing');$('.prisma-title').hidden=true;$('.prisma-game').hidden=false;close();sound.unlock();render(true);save();const focus=root.querySelector<HTMLElement>('[data-optic]:not(:disabled)')||$('[data-action="next"]');focus.focus({preventScroll:true});}
 function rotate(id:string){const before=puzzle.result.lit.size;if(!puzzle.rotate(id))return;hinted=null;sound.turn();render();save();if(puzzle.result.won){sound.win();toast(current===levels.length-1?'Сад света завершён!':'Все огни зажжены. Новая композиция открыта.');$('[data-action="next"]').focus({preventScroll:true});}else if(puzzle.result.lit.size>before)sound.light();}
 function action(name:string){
  if(paused||disposed)return;
  if(name==='sound'){sound.muted=!sound.muted;if(sound.muted)sound.suspend();else{sound.unlock();sound.tone(660);}soundUI();if(options.savePolicy==='persistent')try{localStorage.setItem(soundKey,sound.muted?'off':'on');}catch{}return;}
  if(name==='close')return close();if(name==='help')return help();if(name==='levels')return chooseLevels();if(name==='start')return begin();
  if(!active)return;
  if(name==='next'&&puzzle.result.won){if(current===levels.length-1)return finale();return begin(current+1);}
  if(name==='undo'&&puzzle.undo()){hinted=null;render();save();sound.turn();}
  if(name==='reset'){puzzle.reset();hinted=null;render();save();toast('Композиция возвращена в начальное положение.');}
  if(name==='hint'){hinted=puzzle.hint();if(hinted){render();save();toast('Поверните элемент в светящейся рамке.');root.querySelector<HTMLElement>(`[data-optic="${hinted}"]`)?.focus({preventScroll:true});}}
 }
 root.addEventListener('click',event=>{const target=event.target as HTMLElement;if(target.closest('[data-home]')){event.preventDefault();if(active)chooseLevels();return;}const b=target.closest<HTMLButtonElement>('button');if(!b||b.disabled||paused)return;if(b.dataset.optic&&active&&!modal.open)rotate(b.dataset.optic);else if(b.dataset.level!==undefined){const index=Number(b.dataset.level);if(Number.isInteger(index)&&index>=0&&index<=unlocked())begin(index);}else if(b.dataset.action)action(b.dataset.action);},{signal:abort.signal});
 root.addEventListener('keydown',event=>{if(event.repeat||event.altKey||event.ctrlKey||event.metaKey||paused)return;if(event.code==='KeyM'){event.preventDefault();action('sound');return;}if(modal.open)return;if(event.code==='Escape'){event.preventDefault();chooseLevels();return;}if(!active)return;const names:Record<string,string>={KeyZ:'undo',KeyR:'reset',KeyH:'hint'};if(names[event.code]){event.preventDefault();action(names[event.code]);}},{signal:abort.signal});
 modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}},{signal:abort.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){save();sound.suspend();}else if(active&&!paused)sound.unlock();},{signal:abort.signal});window.addEventListener('pagehide',save,{signal:abort.signal});
 render(true);
 return {pause(value){paused=value;root.classList.toggle('paused',value);if(value){save();sound.suspend();}else if(active)sound.unlock();},dispose(){if(disposed)return;save();disposed=true;abort.abort();if(toastTimer)clearTimeout(toastTimer);sound.dispose();modal.close();root.innerHTML='';root.classList.remove('prisma-root','playing','paused');document.title=oldTitle;},diagnostics(){return {level:current,stars,saveFailed,...puzzle.save(),won:puzzle.result.won};}};
}

const module:EngineModule={id:'prisma',sdk:1,components:[{id:'prisma.optic',name:'Оптический элемент',fields:[{name:'kind',label:'Тип',type:'select',default:'mirror',options:['source','target','mirror','splitter','wall'].map(value=>({value,label:{source:'Источник',target:'Приёмник',mirror:'Зеркало',splitter:'Разделитель',wall:'Камень'}[value]!}))},{name:'color',label:'Цвет',type:'select',default:'amber',options:[{value:'amber',label:'Янтарный'},{value:'cyan',label:'Бирюзовый'}]},{name:'direction',label:'Направление источника',type:'number',default:0,min:0,max:3},{name:'angle',label:'Положение зеркала',type:'number',default:0,min:0,max:1}]}],validateScene(scene){readLevel(scene);},createSession:startGame};
export default module;
