import type {EngineModule,SessionOptions,RuntimeSession,ComponentType} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {World,readLevel,WEAPONS,UPGRADES,type UpgradeId,type Controls,type Save} from './world.ts';
import {Renderer} from './renderer.ts';
import {AudioEngine} from './audio.ts';
const arrow='<svg viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const icons={sound:'<svg viewBox="0 0 24 24"><path d="m11 5-5 4H3v6h3l5 4zm4 3c3 2 3 6 0 8m3-11c5 4 5 10 0 14"/></svg>',pause:'<svg viewBox="0 0 24 24"><path d="M8 5v14M16 5v14"/></svg>',full:'<svg viewBox="0 0 24 24"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/></svg>'};
const time=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const number=(n:number)=>Math.round(n).toLocaleString('ru-RU');
const components:ComponentType[]=[{id:'perimeter.cover',name:'Боевое укрытие',fields:[{name:'style',label:'Тип укрытия',type:'select',default:'crate',options:['crate','container','reactor','machine','server'].map(value=>({value,label:value}))}]},{id:'perimeter.spawn',name:'Точка входа оператора',fields:[]},{id:'perimeter.port',name:'Порт появления машин',fields:[]},{id:'perimeter.gate',name:'Шлюз в следующий сектор',fields:[{name:'next',label:'ID следующей сцены (пусто — финал)',type:'string',default:''}]},{id:'perimeter.decoration',name:'Техническая разметка',fields:[]}];
export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');for(const scene of Object.values(options.snapshot.scenes))options.registry.validate(scene,options.snapshot.manifest);
 const root=options.container,oldTitle=document.title;document.title=options.snapshot.manifest.name;root.classList.add('perimeter');
 root.innerHTML=`<canvas class="p-canvas" tabindex="0" aria-label="Периметр — игровой экран. WASD: движение, мышь: прицел, левая кнопка: огонь, Shift: рывок, пробел: ЭМИ."></canvas><div class="p-grain"></div>
 <header class="p-hud" hidden><div class="p-location"><span class="p-mark">P<span>•</span></span><div><small data-sector>СЕКТОР 01 / 03</small><strong data-location>Грузовой терминал</strong></div></div><div class="p-wave"><small data-wave>ПОДКЛЮЧЕНИЕ</small><span data-objective>Верни питание внешнему контуру</span><div class="p-wave-track"><i></i><i></i><i></i></div></div><div class="p-toolbar"><span class="p-score"><small>ОЧКИ</small><b data-score>00000</b></span><button data-sound class="p-icon" aria-label="Звук">${icons.sound}</button><button data-full class="p-icon" aria-label="На весь экран">${icons.full}</button><button data-pause class="p-icon" aria-label="Пауза">${icons.pause}</button></div></header>
 <div class="p-boss" hidden><div><span data-boss-name>НОЛЬ</span><small data-boss-percent>100%</small></div><i><b></b></i></div>
 <div class="p-banner" role="status"><small data-banner-sub></small><strong data-banner></strong></div><div class="p-combo" hidden><b data-multiplier>×2</b><span>ЦЕПЬ УНИЧТОЖЕНИЙ</span></div>
 <div class="p-tutorial" hidden><span>ПЕРВЫЙ КОНТАКТ</span><p><kbd>W A S D</kbd> движение &nbsp; <kbd>ЛКМ</kbd> огонь<br><kbd>SHIFT</kbd> рывок сквозь пули &nbsp; <kbd>ПРОБЕЛ</kbd> ЭМИ</p><small>Щит восстанавливается через 4 секунды без урона.</small></div>
 <div class="p-gate-prompt" hidden><kbd>E</kbd> Перейти в следующий сектор ${arrow}</div>
 <footer class="p-bottom" hidden><div class="p-vitals"><div class="p-vitals-top"><span>ОПЕРАТОР <b>07</b></span><strong><span data-hp>120</span><small> / <span data-maxhp>120</span></small></strong></div><div class="p-health-bar"><i></i></div><div class="p-shield-row"><span>◇</span><div class="p-shield-bar"><i></i></div><small data-shield>40</small></div></div><div class="p-abilities"><div data-dash-box><kbd>SHIFT</kbd><div><strong data-dash>ГОТОВ</strong><small>РЫВОК</small></div></div><div data-emp-box><kbd>ПРОБЕЛ</kbd><div><strong data-emp>ГОТОВ</strong><small>ЭМИ-ИМПУЛЬС</small></div></div></div><div class="p-weapon"><div class="p-slots"><button data-weapon="0" aria-label="Вектор: клавиша 1">1</button><button data-weapon="1" aria-label="Разлом: клавиша 2">2</button><button data-weapon="2" aria-label="Игла: клавиша 3">3</button></div><div><span data-weapon-name>ВЕКТОР</span><small data-weapon-type>Штурмовая винтовка</small></div><strong><span data-ammo>30</span><small data-mag> / 30</small></strong><span class="p-reload" data-reload>R · ПЕРЕЗАРЯДКА</span></div></footer>
 <section class="p-title"><div class="p-title-top"><span class="p-wordmark">SHELTER<span> / </span>ARCADE</span><div><span class="p-live-dot"></span> АВТОНОМНЫЙ КОМПЛЕКС · 07</div><button data-sound class="p-icon" aria-label="Звук">${icons.sound}</button></div><div class="p-title-content"><div class="p-eyebrow"><span></span> ТАКТИЧЕСКИЙ АРКАДНЫЙ ШУТЕР</div><h1>ПЕРИМЕТР<span>НУЛЕВОЙ СИГНАЛ</span></h1><p>Комплекс больше не отвечает.<br>Машины всё ещё охраняют его.<br><b>Войди. Отключи сигнал. Вернись.</b></p><div class="p-start-actions"><button class="p-primary" data-start>Начать операцию ${arrow}</button><button class="p-text" data-continue hidden>Продолжить с сектора 01 ${arrow}</button></div><div class="p-difficulty" aria-label="Сложность"><span>ПРОТОКОЛ</span><button data-difficulty="0">Разведка</button><button data-difficulty="1" class="selected">Штурм</button><button data-difficulty="2">Ветеран</button></div><small class="p-difficulty-note">Штурм — стандартная сложность. Щит регенерирует.</small></div><div class="p-title-side"><span>ОПЕРАТОР</span><strong>07</strong><div class="p-side-line"></div><small>СТАТУС</small><p>Ожидает<br>подключения<span>_</span></p></div><div class="p-title-bottom"><div><span>03</span> СЕКТОРА <i></i><span>03</span> СИСТЕМЫ ОРУЖИЯ <i></i><span>01</span> ЦЕЛЬ</div><button class="p-text" data-help>Управление и протокол ${arrow}</button></div></section>
 <section class="p-modal" hidden role="dialog" aria-modal="true" aria-labelledby="p-modal-title"><div class="p-modal-content"></div></section><div class="p-save" role="status"></div>
 <div class="p-touch" hidden><div class="p-stick" data-stick="move"><i></i><span>ДВИЖЕНИЕ</span></div><div class="p-touch-actions"><button data-touch="weapon">1 / 2 / 3</button><button data-touch="dash">РЫВОК</button><button data-touch="emp">ЭМИ</button><button data-touch="interact">E</button></div><div class="p-stick p-aim-stick" data-stick="aim"><i></i><span>ПРИЦЕЛ / ОГОНЬ</span></div></div>`;
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const canvas=$<HTMLCanvasElement>('canvas'),world=new World(options.snapshot.manifest.scenes.map(s=>options.snapshot.scenes[s.id]),options.sceneId),renderer=new Renderer(canvas,world),audio=new AudioEngine(),abort=new AbortController();
 const key=storageKey(options.snapshot.manifest.projectId,'progress','campaign'),settingsKey=storageKey(options.snapshot.manifest.projectId,'settings','controls');let saved:Save|undefined,difficulty=1,disposed=false,frame=0,previous=performance.now(),accumulator=0,uiTime=0,lastPhase='',modalKind='',pointerX=0,pointerY=0,fire=false,dash=false,emp=false,reload=false,interact=false,weapon=-1;const keys=new Set<string>();let moveTouch={x:0,y:0},aimTouch={x:0,y:0},touchingAim=false;const touch=matchMedia('(pointer: coarse)').matches;
 if(options.savePolicy==='persistent'){try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(world.validSave(raw)&&!raw.won)saved=raw;const settings=JSON.parse(localStorage.getItem(settingsKey)||'null');if(settings){audio.setMuted(!!settings.muted);difficulty=[0,1,2].includes(settings.difficulty)?settings.difficulty:1;}}catch{}}
 const listen=(el:EventTarget,type:string,cb:EventListener)=>el.addEventListener(type,cb,{signal:abort.signal});
 function saveSettings(){if(options.savePolicy==='persistent')try{localStorage.setItem(settingsKey,JSON.stringify({muted:audio.muted,difficulty}));}catch{}}
 function save(value:Save){if(options.savePolicy!=='persistent')return;try{localStorage.setItem(key,JSON.stringify(value));saved=value.won?undefined:value;$('.p-save').textContent=value.won?'Операция завершена':'Сектор сохранён';setTimeout(()=>{if(!disposed)$('.p-save').textContent='';},2500);}catch{$('.p-save').textContent='Сохранение недоступно в этом браузере';}}
 world.onSave=save;world.onSound=s=>audio.play(s);world.onScene=()=>renderer.snap();
 function clear(){keys.clear();fire=false;dash=emp=reload=interact=false;weapon=-1;moveTouch={x:0,y:0};aimTouch={x:0,y:0};touchingAim=false;root.querySelectorAll<HTMLElement>('.p-stick i').forEach(el=>el.style.transform='translate(-50%,-50%)');}
 function focus(){canvas.focus({preventScroll:true});}
 function hideModal(){$('.p-modal').hidden=true;modalKind='';clear();focus();}
 function resume(){world.pause(false);hideModal();}
 function openPause(){if(!['playing','cleared'].includes(world.phase))return;world.pause(true);clear();showModal('pause');}
 function start(resumeSaved=false){void audio.unlock();clear();if(resumeSaved&&saved)world.restore(saved);else world.newGame(difficulty);hideModal();update();}
 function title(){world.phase='title';hideModal();renderer.snap();update();}
 function modalButton(action:string,label:string,primary=false){return `<button class="${primary?'p-primary':'p-secondary'}" data-action="${action}">${label}${primary?arrow:''}</button>`;}
 function showModal(kind:string){modalKind=kind;const modal=$('.p-modal'),content=$('.p-modal-content');modal.hidden=false;clear();content.className='p-modal-content '+(kind==='upgrade'?'p-upgrade-modal':'');
  if(kind==='pause')content.innerHTML=`<span class="p-eyebrow">СВЯЗЬ ПРИОСТАНОВЛЕНА</span><h2 id="p-modal-title">Пауза</h2><p>Сектор ${world.level.theme+1} · ${world.level.name}<br>Волна ${world.wave || 1} / 3 &nbsp; · &nbsp; ${time(world.stats.seconds)}</p><div class="p-modal-actions">${modalButton('resume','Продолжить',true)}${modalButton('help','Управление')}${modalButton('retry','Повторить сектор')}${modalButton('title','В главное меню')}</div><small>Сохраняется начало сектора. Текущая волна начнётся заново после выхода.</small>`;
  if(kind==='help')content.innerHTML=`<span class="p-eyebrow">ИНСТРУКТАЖ / 07</span><h2 id="p-modal-title">Контроль периметра</h2><div class="p-controls-list"><div><kbd>W A S D / ↑ ↓ ← →</kbd><span>Движение</span></div><div><kbd>МЫШЬ + ЛКМ</kbd><span>Прицел и огонь</span></div><div><kbd>1 / 2 / 3</kbd><span>Винтовка / дробовик / карабин</span></div><div><kbd>SHIFT / ПКМ</kbd><span>Рывок, неуязвимость к пулям</span></div><div><kbd>ПРОБЕЛ</kbd><span>ЭМИ: урон рядом и уничтожение пуль</span></div><div><kbd>R / E</kbd><span>Перезарядка / следующий сектор</span></div><div><kbd>ESC / M</kbd><span>Пауза / звук</span></div></div><p>Три волны в каждом секторе. После первых двух выбери улучшение; в третьей уничтожь тяжёлую единицу. Укрытия задерживают пули. Щит восстанавливается через 4 секунды без урона. Боезапас бесконечен, магазины требуют перезарядки.</p>${modalButton('back','Всё понятно',true)}`;
  if(kind==='upgrade')content.innerHTML=`<span class="p-eyebrow">ВОЛНА ${world.wave} ЗАВЕРШЕНА / СЕКТОР 0${world.level.theme+1}</span><h2 id="p-modal-title">Адаптируй арсенал.</h2><p>Одна модификация. До конца операции.</p><div class="p-upgrade-grid">${world.choices.map((id,i)=>{const u=UPGRADES[id];return `<button class="p-upgrade-card" data-upgrade="${id}"><div><span>${u.icon}</span><small>0${i+1} / МОДУЛЬ</small></div><strong>${u.title}</strong><b>${u.label}</b><p>${u.description}</p><footer>Установить ${arrow}</footer></button>`;}).join('')}</div>`;
  if(kind==='dead')content.innerHTML=`<span class="p-eyebrow p-danger">ОПЕРАТОР ОТКЛЮЧЁН</span><h2 id="p-modal-title">Ещё одна попытка.</h2><p>Машины удержали ${world.level.name.toLowerCase()}.<br>Начни этот сектор заново с сохранёнными улучшениями.</p><div class="p-result-stats"><div><b>${world.sectorKills}</b><span>ЦЕЛЕЙ В СЕКТОРЕ</span></div><div><b>${number(world.stats.score)}</b><span>ОЧКОВ</span></div></div><div class="p-modal-actions">${modalButton('retry','Повторить сектор',true)}${modalButton('title','Главное меню')}</div>`;
  if(kind==='won'){const rank=world.stats.deaths===0&&world.stats.damage<300?'S':world.stats.deaths<3?'A':'B';content.innerHTML=`<span class="p-eyebrow">ПРОТОКОЛ ВЫПОЛНЕН / ВСЕ СЕКТОРА ОЧИЩЕНЫ</span><div class="p-victory-heading"><h2 id="p-modal-title">Тишина.<br>Наконец-то.</h2><span>${rank}</span></div><p>Нулевой сигнал прерван. Автономный комплекс отключён.<br>Оператор 07 возвращается домой.</p><div class="p-result-stats"><div><b>${number(world.stats.score)}</b><span>ОЧКОВ</span></div><div><b>${time(world.stats.seconds)}</b><span>ВРЕМЯ</span></div><div><b>${world.stats.kills}</b><span>ЦЕЛЕЙ</span></div></div><p class="p-run-modules">${world.upgrades.map(id=>UPGRADES[id].title).join(' · ')}</p><div class="p-modal-actions">${modalButton('new','Новая операция',true)}${modalButton('title','Главное меню')}</div>`;}
  requestAnimationFrame(()=>content.querySelector<HTMLButtonElement>('button')?.focus({preventScroll:true}));
 }
 function update(){const titlePhase=world.phase==='title',h=world.hero,boss=world.boss;$('.p-title').hidden=!titlePhase;$('.p-hud').hidden=titlePhase;$('.p-bottom').hidden=titlePhase;$('.p-touch').hidden=titlePhase||!touch||!['playing','cleared'].includes(world.phase);root.classList.toggle('p-in-game',['playing','cleared'].includes(world.phase));
  $('[data-sector]').textContent=`СЕКТОР 0${world.level.theme+1} / 03`;$('[data-location]').textContent=world.level.name;$('[data-wave]').textContent=world.phase==='cleared'?'КОНТУР ОТКЛЮЧЁН':world.wave?`ВОЛНА 0${world.wave} / 03`:'ВХОД В СЕКТОР';$('[data-objective]').textContent=world.phase==='cleared'?'Следуй к северному шлюзу':world.wave?`Активных целей: ${world.remaining}`:world.level.subtitle;root.querySelectorAll('.p-wave-track i').forEach((el,i)=>el.classList.toggle('active',i<world.wave));
  $('[data-score]').textContent=number(world.stats.score);$('[data-hp]').textContent=String(Math.ceil(h.hp));$('[data-maxhp]').textContent=String(world.maxHP);$('.p-health-bar i').style.width=`${h.hp/world.maxHP*100}%`;$('[data-shield]').textContent=String(Math.ceil(h.shield));$('.p-shield-bar i').style.width=`${h.shield/world.maxShield*100}%`;$('.p-vitals').classList.toggle('low',h.hp<world.maxHP*.3);
  $('[data-dash]').textContent=h.dashCD>0?h.dashCD.toFixed(1)+' С':'ГОТОВ';$('[data-emp]').textContent=h.empCD>0?h.empCD.toFixed(1)+' С':'ГОТОВ';$('[data-dash-box]').classList.toggle('cooldown',h.dashCD>0);$('[data-emp-box]').classList.toggle('cooldown',h.empCD>0);$('[data-weapon-name]').textContent=WEAPONS[h.weapon].name;$('[data-weapon-type]').textContent=WEAPONS[h.weapon].type;$('[data-ammo]').textContent=h.reload>0?'··':String(h.ammo[h.weapon]);$('[data-mag]').textContent=' / '+WEAPONS[h.weapon].mag;$('[data-reload]').textContent=h.reload>0?`ПЕРЕЗАРЯДКА ${h.reload.toFixed(1)}`:'R · ПЕРЕЗАРЯДКА';root.querySelectorAll<HTMLElement>('[data-weapon]').forEach(b=>b.classList.toggle('active',Number(b.dataset.weapon)===h.weapon));
  $('.p-boss').hidden=!boss;if(boss){$('[data-boss-name]').textContent=world.level.boss;$('[data-boss-percent]').textContent=Math.ceil(boss.hp/boss.maxHP*100)+'%';$('.p-boss i b').style.width=boss.hp/boss.maxHP*100+'%';}
  $('.p-banner').classList.toggle('visible',world.bannerTime>0&&['playing','cleared'].includes(world.phase));$('[data-banner]').textContent=world.banner;$('[data-banner-sub]').textContent=world.bannerSub;
  $('.p-tutorial').hidden=!(world.level.theme===0&&world.stats.seconds<18&&world.phase==='playing'&&!touch);$('.p-gate-prompt').hidden=!(world.phase==='cleared'&&Math.hypot(h.x-world.level.gate.x,h.y-world.level.gate.y)<145);$('.p-combo').hidden=world.multiplier<2||!['playing','cleared'].includes(world.phase);$('[data-multiplier]').textContent='×'+world.multiplier;
  root.querySelectorAll<HTMLElement>('[data-sound]').forEach(b=>{b.classList.toggle('muted',audio.muted);b.setAttribute('aria-label',audio.muted?'Включить звук':'Выключить звук');b.setAttribute('aria-pressed',String(!audio.muted));});root.querySelectorAll<HTMLElement>('[data-difficulty]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.difficulty)===difficulty));$('.p-difficulty-note').textContent=['Разведка — входящий урон снижен на 40%.','Штурм — стандартная сложность. Щит регенерирует.','Ветеран — машины прочнее, входящий урон выше на 30%.'][difficulty];$('[data-continue]').hidden=!saved;if(saved)$('[data-continue]').innerHTML=`Продолжить · ${world.levels.find(l=>l.id===saved!.scene)!.name} ${arrow}`;
  if(['upgrade','dead','won'].includes(world.phase)&&modalKind!==world.phase)showModal(world.phase);
 }
 listen(root,'click',((e:MouseEvent)=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;void audio.unlock();if(b.hasAttribute('data-start')){if(saved){world.pause(true);showModal('confirm');$('.p-modal-content').innerHTML=`<span class="p-eyebrow">НОВАЯ ОПЕРАЦИЯ</span><h2 id="p-modal-title">Начать заново?</h2><p>Сохранённый сектор и улучшения будут заменены новой операцией.</p><div class="p-modal-actions">${modalButton('new','Начать заново',true)}${modalButton('cancel','Отмена')}</div>`;}else start();}
  if(b.hasAttribute('data-continue'))start(true);if(b.hasAttribute('data-pause'))openPause();if(b.hasAttribute('data-help'))showModal('help');if(b.hasAttribute('data-sound')){audio.setMuted(!audio.muted);saveSettings();update();}if(b.hasAttribute('data-full')){if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});else void root.requestFullscreen?.().catch(()=>{});}if(b.dataset.difficulty!==undefined){difficulty=Number(b.dataset.difficulty);saveSettings();update();}if(b.dataset.weapon!==undefined){weapon=Number(b.dataset.weapon);focus();}if(b.dataset.upgrade){world.choose(b.dataset.upgrade as UpgradeId);hideModal();update();}
  const action=b.dataset.action;if(action==='resume')resume();if(action==='retry'){world.retry();hideModal();update();}if(action==='title')title();if(action==='new')start();if(action==='cancel')hideModal();if(action==='help')showModal('help');if(action==='back'){if(world.phase==='paused')showModal('pause');else hideModal();}
  if(b.dataset.touch==='weapon')weapon=(world.hero.weapon+1)%3;if(b.dataset.touch==='dash')dash=true;if(b.dataset.touch==='emp')emp=true;if(b.dataset.touch==='interact')interact=true;
 }) as EventListener);
 listen(window,'keydown',((e:KeyboardEvent)=>{if(e.ctrlKey||e.metaKey||e.altKey)return;const used=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','KeyR','KeyE','Digit1','Digit2','Digit3','Escape','KeyP','KeyM'];if(!used.includes(e.code))return;if(e.code!=='Space'||['playing','cleared'].includes(world.phase))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(modalKind==='help'){world.phase==='paused'?showModal('pause'):hideModal();}else if(world.phase==='paused')resume();else if(modalKind==='confirm')hideModal();else openPause();return;}if(e.code==='KeyM'&&!e.repeat){audio.setMuted(!audio.muted);saveSettings();update();return;}if(!['playing','cleared'].includes(world.phase))return;keys.add(e.code);if(!e.repeat){if(e.code.startsWith('Shift'))dash=true;if(e.code==='Space')emp=true;if(e.code==='KeyR')reload=true;if(e.code==='KeyE')interact=true;if(e.code.startsWith('Digit'))weapon=Number(e.code.slice(-1))-1;}}) as EventListener);
 listen(window,'keyup',((e:KeyboardEvent)=>{keys.delete(e.code);}) as EventListener);
 listen(canvas,'pointermove',((e:PointerEvent)=>{const rect=canvas.getBoundingClientRect();pointerX=e.clientX-rect.left;pointerY=e.clientY-rect.top;renderer.pointer={x:pointerX,y:pointerY,visible:e.pointerType!=='touch'};}) as EventListener);
 listen(canvas,'pointerdown',((e:PointerEvent)=>{if(!['playing','cleared'].includes(world.phase))return;e.preventDefault();void audio.unlock();focus();canvas.setPointerCapture(e.pointerId);const rect=canvas.getBoundingClientRect();pointerX=e.clientX-rect.left;pointerY=e.clientY-rect.top;if(e.button===0)fire=true;if(e.button===2)dash=true;}) as EventListener);
 const release=()=>{fire=false;};listen(window,'pointerup',release);listen(canvas,'pointercancel',release);listen(canvas,'lostpointercapture',release);listen(canvas,'contextmenu',e=>e.preventDefault());
 for(const stick of root.querySelectorAll<HTMLElement>('[data-stick]')){let pid=-1;const set=(e:PointerEvent)=>{const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(32,Math.hypot(dx,dy)),value={x:dx/len,y:dy/len};stick.querySelector<HTMLElement>('i')!.style.transform=`translate(calc(-50% + ${value.x*32}px),calc(-50% + ${value.y*32}px))`;if(stick.dataset.stick==='move')moveTouch=value;else{aimTouch=value;touchingAim=true;}};listen(stick,'pointerdown',((e:PointerEvent)=>{e.preventDefault();pid=e.pointerId;stick.setPointerCapture(pid);set(e);}) as EventListener);listen(stick,'pointermove',((e:PointerEvent)=>{if(e.pointerId===pid)set(e);}) as EventListener);const end=(e:Event)=>{if((e as PointerEvent).pointerId!==pid)return;pid=-1;if(stick.dataset.stick==='move')moveTouch={x:0,y:0};else touchingAim=false;stick.querySelector<HTMLElement>('i')!.style.transform='translate(-50%,-50%)';};listen(stick,'pointerup',end);listen(stick,'pointercancel',end);listen(stick,'lostpointercapture',end);}
 listen(window,'blur',()=>{clear();openPause();});listen(document,'visibilitychange',()=>{if(document.hidden){clear();openPause();}});
 // Keep tab navigation inside dialogs, while retaining native button activation.
 listen(root,'keydown',((e:KeyboardEvent)=>{if(e.key!=='Tab'||$('.p-modal').hidden)return;const buttons=[...$('.p-modal').querySelectorAll<HTMLButtonElement>('button')];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}) as EventListener);
 const observer=new ResizeObserver(()=>renderer.resize());observer.observe(canvas);
 function controls():Controls{const aim=renderer.screenToWorld(pointerX||renderer.w/2,pointerY||renderer.h/2);return {x:Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+moveTouch.x,y:Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'))+moveTouch.y,aimX:touchingAim?world.hero.x+aimTouch.x*500:aim.x,aimY:touchingAim?world.hero.y+aimTouch.y*500:aim.y,fire:fire||touchingAim,dash,emp,reload,interact,weapon};}
 function tick(now:number){if(disposed)return;const dt=Math.min(.05,(now-previous)/1000);previous=now;accumulator+=dt;while(accumulator>=1/120){world.step(1/120,controls());dash=emp=reload=interact=false;weapon=-1;accumulator-=1/120;}renderer.draw(dt);audio.update(world.phase==='playing',world.level.theme);uiTime+=dt;if(uiTime>.06||world.phase!==lastPhase){lastPhase=world.phase;update();uiTime=0;}frame=requestAnimationFrame(tick);}
 if(import.meta.env.DEV)Object.defineProperty(window,'__PERIMETER__',{configurable:true,value:{snapshot:()=>({phase:world.phase,scene:world.level.id,wave:world.wave,remaining:world.remaining,hero:structuredClone(world.hero),stats:{...world.stats},choices:[...world.choices],camera:{x:renderer.cameraX,y:renderer.cameraY,scale:renderer.scale},enemies:world.enemies.map(e=>({...e})),cover:world.level.cover,gate:world.level.gate}),world,renderer}});
 update();frame=requestAnimationFrame(tick);
 return {pause(value){if(value)openPause();else if(world.phase==='paused')resume();},dispose(){disposed=true;cancelAnimationFrame(frame);abort.abort();observer.disconnect();audio.dispose();renderer.dispose();root.replaceChildren();root.classList.remove('perimeter','p-in-game');document.title=oldTitle;if(import.meta.env.DEV)delete (window as any).__PERIMETER__;},diagnostics:()=>({game:'perimeter',scene:world.level.id,phase:world.phase,wave:world.wave,enemies:world.enemies.length,bullets:world.bullets.length})};
}
const module:EngineModule={id:'perimeter',sdk:1,components,validateScene(scene,project){const level=readLevel(scene);if(level.next&&!project.scenes.some(s=>s.id===level.next))throw new Error('Периметр: сцена следующего сектора не найдена.');},createSession:startGame};
export default module;
