import type {EngineModule,SessionOptions,RuntimeSession} from '@shelter/sdk.ts';
import {storageKey} from '@shelter/project.ts';
import {City,BLUEPRINTS,BUILD_ORDER,SEASONS,EVENTS,type Tool,type Kind} from './world.ts';
import {Renderer} from './renderer.ts';
import {Sound} from './audio.ts';
const svg=(body:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons={home:svg('<path d="m3 10 9-7 9 7v11H3Z"/><path d="M9 21v-8h6v8M7 9h.01M17 9h.01"/>'),coin:svg('<circle cx="12" cy="12" r="9"/><path d="M12 7v10m3-8c-6-3-8 4-2 3s4 6-4 3"/>'),wood:svg('<path d="m12 2-7 9h4l-5 6h7v5h2v-5h7l-5-6h4Z"/>'),food:svg('<path d="M5 21 18 4M9 16C2 16 3 10 6 10c3 0 3 6 3 6Zm4-5C6 11 7 5 10 5c3 0 3 6 3 6Zm-2 3c0-6 7-6 7-3 0 3-7 3-7 3Zm4-6c0-6 7-6 7-3 0 3-7 3-7 3Z"/>'),people:svg('<circle cx="9" cy="7" r="3"/><path d="M3 21v-5a6 6 0 0 1 12 0v5M17 4a3 3 0 0 1 0 6m1 3c4 1 4 4 4 8"/>'),happy:svg('<circle cx="12" cy="12" r="9"/><path d="M8 14c2 4 6 4 8 0M8 9h.01M16 9h.01"/>'),power:svg('<path d="m13 2-8 12h6l-1 8 9-13h-7Z"/>'),arrow:svg('<path d="M4 12h16m-6-6 6 6-6 6"/>'),map:svg('<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16"/>')};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function startGame(options:SessionOptions):Promise<RuntimeSession>{
 await import('./style.css');
 const scene=options.snapshot.scenes[options.sceneId],root=options.container,oldTitle=document.title;document.title='Тихая бухта · Город у моря';root.classList.add('bay-root');
 let city=new City(scene);
 const key=storageKey(options.snapshot.manifest.projectId,'progress',options.snapshot.manifest.build.appId),soundKey=storageKey(options.snapshot.manifest.projectId,'sound');let hasSave=false,saveError=false;
 if(options.savePolicy==='persistent')try{hasSave=city.restore(JSON.parse(localStorage.getItem(key)||'null'));}catch{}
 root.innerHTML=`<canvas class="bay-canvas" tabindex="0" aria-label="Карта города. Выберите здание внизу и нажмите на свободную клетку. Перетаскивание перемещает карту."></canvas>
 <div class="bay-vignette"></div>
 <header class="bay-header game-ui"><div class="brand"><span class="brand-mark">${icons.home}</span><div><strong>Тихая бухта</strong><small>ГОРОД У МОРЯ</small></div></div><div class="resources" data-resources></div><div class="top-actions"><button data-action="sound" class="square" title="Звук · M" aria-label="Выключить звук">♪</button><button data-action="help" class="square" title="Как играть" aria-label="Как играть">?</button><button data-action="menu" class="square" title="Меню" aria-label="Меню">☰</button></div></header>
 <aside class="mission game-ui"><div class="eyebrow"><span class="dot"></span> ПЛАН РАЗВИТИЯ <b data-chapter>01 / 03</b></div><h2 data-mission-title>Первые соседи</h2><p data-mission-copy>Начните с самого важного.</p><div data-objectives></div><div class="mission-reward" data-reward></div></aside>
 <aside class="inspector game-ui"><div class="eyebrow">ГОРОДСКОЙ АРХИТЕКТОР</div><div data-inspector></div></aside>
 <div class="map-tools game-ui"><button class="square" data-action="zoom-in" aria-label="Приблизить карту" title="Приблизить · +">+</button><button class="square" data-action="zoom-out" aria-label="Отдалить карту" title="Отдалить · −">−</button><button class="square" data-action="center" aria-label="Показать весь остров" title="Весь остров">${icons.map}</button><button class="square" data-action="grid" aria-label="Показать сетку" title="Сетка · G">▦</button></div>
 <div class="bay-toast" role="status" aria-live="polite"></div>
 <section class="bottom-ui game-ui"><div class="season-bar"><div class="calendar"><span class="season-symbol" data-season-symbol>✿</span><div><strong data-season-name></strong><small data-season-caption></small></div></div><div class="forecast" data-forecast></div><button class="next-season" data-action="next"><span>Следующий сезон</span>${icons.arrow}</button></div><div class="build-dock"><div class="build-heading"><span><b>ПОСТРОИТЬ</b><small>Выберите здание и место на острове</small><button class="tool-help" data-action="tool-help" aria-label="О выбранной постройке">Справка · ?</button></span><div class="utility"><button data-tool="inspect" title="Осмотр · Esc" aria-label="Осмотр">↖</button><button data-tool="bulldoze" title="Снести · возврат 50%" aria-label="Снести здание">♧</button><button data-action="undo" title="Отменить последнее строительство · Z" aria-label="Отменить строительство">↶</button></div></div><div class="blueprints" data-blueprints></div></div><div class="statusline"><span data-status>Потяните карту, чтобы осмотреть остров · Колесо мыши — масштаб</span><span data-save>Автосохранение</span></div></section>
 <section class="title-screen"><div class="title-top"><span>ТИХАЯ БУХТА / SHELTER ENGINE</span><span>МАЛЕНЬКИЙ ОСТРОВ. БОЛЬШИЕ ПЛАНЫ.</span></div><div class="title-card"><span class="eyebrow">ГРАДОСТРОИТЕЛЬНАЯ ИГРА</span><h1>Хорошее место<br>для <em>нового<br>начала.</em></h1><p>Пара домов, морской ветер и целый остров возможностей. Постройте город, в который хочется вернуться.</p><button class="primary" data-action="start">${hasSave?'Продолжить город':'Основать город'} ${icons.arrow}</button>${hasSave?'<button class="title-new" data-action="new">Начать на чистом острове</button>':''}<div class="title-meta"><span>10 построек</span><i></i><span>4 сезона</span><i></i><span>Ваш ритм</span></div></div><div class="title-bottom"><span>СОЗДАНО НА SHELTER ENGINE</span><span>СТРОЙТЕ. ЗАБОТЬТЕСЬ. ОСТАВЬТЕ СЛЕД.</span></div></section>
 <section class="bay-modal" hidden role="dialog" aria-modal="true" aria-labelledby="bay-dialog-title"><div class="dialog-card"></div></section>`;
 const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
 const canvas=$<HTMLCanvasElement>('canvas'),renderer=new Renderer(canvas,city),sound=new Sound(),abort=new AbortController(),modal=$('.bay-modal'),card=$('.dialog-card');
 try{if(options.savePolicy==='persistent')sound.muted=localStorage.getItem(soundKey)==='off';}catch{}
 let active=false,disposed=false,paused=false,frame=0,lastDraw=0,tool:Tool='inspect',selected=-1,hover=-1,toastTimer:ReturnType<typeof setTimeout>|null=null,dialog='',lastFocus:HTMLElement|null=null;
 const save=()=>{if(options.savePolicy!=='persistent')return;try{localStorage.setItem(key,JSON.stringify(city.save()));$('[data-save]').textContent='Город сохранён';}catch{saveError=true;$('[data-save]').textContent='Сохранение недоступно';}};
 function toast(message:string){if(!message)return;const box=$('.bay-toast');box.textContent=message;box.classList.add('visible');if(toastTimer)clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('visible'),5500);}
 const soundUI=()=>{$('[data-action="sound"]').textContent=sound.muted?'♩':'♪';$('[data-action="sound"]').setAttribute('aria-label',sound.muted?'Включить звук':'Выключить звук');$('[data-action="sound"]').classList.toggle('muted',sound.muted);};soundUI();
 const showDialog=(kind:string,html:string)=>{lastFocus=document.activeElement as HTMLElement;dialog=kind;modal.hidden=false;card.innerHTML=html;card.querySelector<HTMLElement>('button')?.focus();};
 const closeDialog=()=>{modal.hidden=true;dialog='';lastFocus?.focus({preventScroll:true});};
 const help=()=>showDialog('help',`<span class="eyebrow">СПРАВОЧНИК АРХИТЕКТОРА</span><h2 id="bay-dialog-title">Город начинается с заботы.</h2><div class="help-grid"><p><b>01 · Соедините</b>Стройте рядом с дорогой, связанной с ратушей. Жёлтый «!» над зданием означает, что дороги нет. Диагонали не считаются.</p><p><b>02 · Обеспечьте</b>Фермы дают еду, лесопилки — дерево. Один житель съедает 0,5 еды за сезон. Стройте фермы на светлых лугах слева, лесопилки у леса.</p><p><b>03 · Развивайте</b>У домов есть вместимость. До 10 новых жителей приезжает за сезон при счастье от 50%. Следите за едой и энергией.</p><p><b>04 · Откройте бухту</b>Выполните три главы, постройте маяк на берегу и завершите сезон. После финала можно строить дальше без ограничения.</p></div><p class="dialog-note">Время идёт только по кнопке. Под кнопкой — прогноз текущего сезона. В торговле можно купить дерево и еду. Снос возвращает 50% стоимости. «↶» отменяет последнюю постройку до смены сезона или покупки.</p><div class="key-guide">Мышь / палец — строить и двигать карту · + / − — масштаб · 1–9, 0 — постройки · Esc — осмотр · Z — отменить · M — звук</div><button class="primary" data-action="close">Всё понятно ${icons.arrow}</button>`);
 const menu=()=>showDialog('menu',`<span class="eyebrow">ТИХАЯ ПАУЗА</span><h2 id="bay-dialog-title">Город вас подождёт.</h2><p>Прогресс ${saveError?'не удалось записать в браузер':'автоматически сохранён в этом браузере'}. Сезоны меняются только по вашей команде.</p><button class="primary" data-action="close">Вернуться к городу ${icons.arrow}</button><button class="secondary" data-action="help">Как играть</button><button class="secondary" data-action="trade">Торговля с материком</button><button class="secondary" data-action="journal">Городская хроника</button><button class="text-button" data-action="new">Начать новый город</button>`);
 const newDialog=()=>showDialog('new',`<span class="eyebrow">ЧИСТЫЙ ЛИСТ</span><h2 id="bay-dialog-title">Основать новый город?</h2><p>Текущий город и его сохранение будут заменены. Это действие нельзя отменить.</p><button class="primary" data-action="close">Оставить текущий город</button><button class="secondary" data-action="confirm-new">Да, начать заново</button>`);
 const showEvent=()=>{if(city.event===null)return;const e=EVENTS[city.event];showDialog('event',`<span class="event-seal">✉</span><span class="eyebrow">ПИСЬМО В РАТУШУ</span><h2 id="bay-dialog-title">${e.title}</h2><p>${e.story}</p><div class="event-choices">${e.choices.map((c,i)=>`<button data-choice="${i}" ${city.coins+(c.coins||0)<0?'disabled':''}><strong>${c.label}</strong><span>${c.detail}</span>${icons.arrow}</button>`).join('')}</div>`);};
 const showWin=()=>{const stars=city.season<=16&&city.aidCount===0?3:city.season<=28?2:1;showDialog('win',`<span class="victory-mark">☀</span><span class="eyebrow">ТИХАЯ БУХТА ОТКРЫТА МИРУ</span><h2 id="bay-dialog-title">Здесь теперь — дом.</h2><p>Маяк встречает первые корабли. На месте пустого берега вырос город, о котором будут рассказывать.</p><div class="victory-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><div class="win-stats"><div><strong>${city.population}</strong><span>жителей</span></div><div><strong>${city.season}</strong><span>сезонов</span></div><div><strong>${city.stats().happiness}%</strong><span>счастье</span></div></div><p class="dialog-note">3 звезды: до 16 сезонов без помощи. 2 звезды: до 28 сезонов. Город принадлежит вам — продолжайте строить.</p><button class="primary" data-action="close">Остаться в бухте ${icons.arrow}</button><button class="text-button" data-action="new">Создать другой город</button>`);};
 function begin(fresh=false){if(fresh){city=new City(scene);renderer.city=city;renderer.reset();selected=-1;tool='inspect';}active=true;root.classList.add('playing');$('.title-screen').hidden=true;closeDialog();sound.unlock();update();save();canvas.focus();if(city.event!==null)showEvent();else if(!hasSave||fresh){toast('Добро пожаловать! Постройте ещё 2 дома, ферму и лесопилку.');setTool('cottage');}hasSave=true;}
 function setTool(next:Tool){tool=next;renderer.tool=next;selected=-1;renderer.selected=-1;update();}
 function inspector(){const t=city.tiles[selected],building=t?.building;const isBuild=tool!=='inspect'&&tool!=='bulldoze',kind=isBuild?tool as Kind:building;
  if(kind){const b=BLUEPRINTS[kind];$('[data-inspector]').innerHTML=`<span class="building-icon" style="--building-color:${b.color}">${b.icon}</span><h3>${b.name}</h3><p>${b.description}</p>${isBuild?`<div class="cost"><span>${icons.coin}<b>${b.cost}</b></span><span>${icons.wood}<b>${b.wood}</b></span></div><div class="inspector-note">${b.stage>city.stage?'Выполните предыдущую главу.':'Нажмите на свободную клетку.<br>Можно построить несколько подряд.'}</div>`:`<div class="inspector-note">${city.stats().connected.has(selected)?'● Подключено к ратуше':'! Нужна дорога до ратуши'}<br>Содержание: ${b.upkeep} монет / сезон</div>`}`;
  }else if(tool==='bulldoze')$('[data-inspector]').innerHTML='<span class="building-icon">↯</span><h3>Освободить место</h3><p>Нажмите на здание или дорогу. Вернётся половина потраченных монет и дерева.</p><div class="inspector-note">Отмена последнего действия: ↶ или Z.</div>';
  else $('[data-inspector]').innerHTML=`<span class="building-icon">${icons.map}</span><h3>${t?({water:'Морская гладь',meadow:'Плодородный луг',forest:'Возобновляемый лес',grass:'Свободная земля'}[t.terrain]):'У каждого дома своя история'}</h3><p>${t?(t.terrain==='meadow'?'Идеальное место для фермы: на 25% больше урожая.':t.terrain==='forest'?'Лес рядом с лесопилкой увеличивает производство дерева. При строительстве на клетке деревья убираются.':t.terrain==='water'?'На воде строить нельзя. А на соседнем берегу можно поставить маяк.':'Выберите здание внизу и постройте его здесь. Не забудьте дорогу.'):'Нажмите на здание, чтобы узнать, как оно работает. Или выберите новую постройку внизу.'}</p><button class="trade-button" data-action="trade">${icons.coin} Торговля с материком</button>`;
 }
 function update(){const s=city.stats();$('[data-action="tool-help"]').textContent=(tool==='inspect'?'Справка':tool==='bulldoze'?'Снос':BLUEPRINTS[tool].short)+' · ?';
  const resources=[['coin','Казна',city.coins,`${s.balance>=0?'+':''}${s.balance} / сезон`],['wood','Дерево',city.wood,`+${s.wood} / сезон`],['food','Еда',city.food,`${s.food-s.consumption>=0?'+':''}${s.food-s.consumption} / сезон`],['people','Жители',city.population,`из ${s.capacity} мест`],['happy','Счастье',s.happiness+'%',s.happiness>=75?'Прекрасная жизнь':s.happiness>=50?'Город растёт':'Нужна забота'],['power','Энергия',s.demand+'/'+s.power,s.demand<=s.power?'Хватает всем':'Перегрузка']];
  $('[data-resources]').innerHTML=resources.map(([icon,name,value,hint])=>`<div class="resource ${icon==='food'&&city.food+s.food<s.consumption||icon==='power'&&s.demand>s.power?'warning':''}" title="${name}: ${value}. ${hint}">${icons[icon as keyof typeof icons]}<span><small>${name}</small><strong>${value}</strong><em>${hint}</em></span></div>`).join('');
  $('[data-chapter]').textContent=city.won?'ГОТОВО':`0${city.stage+1} / 03`;
  $('[data-mission-title]').textContent=city.won?'Город продолжается':['Первые соседи','Место для жизни','Свет большой бухты'][city.stage];
  $('[data-mission-copy]').textContent=city.won?'Маяк горит. Создайте город своей мечты.':['Соедините постройки дорогами и пригласите новые семьи.','Торгуйте, озеленяйте улицы и дайте городу энергию.','Позаботьтесь о жителях и постройте маяк на берегу.'][city.stage];
  $('[data-objectives]').innerHTML=city.objectives().map(o=>`<div class="objective ${o.value>=o.max?'done':''}"><span>${o.value>=o.max?'✓':'○'}</span><span>${o.text}</span><b>${Math.min(o.value,o.max)}/${o.max}</b></div>`).join('');
  $('[data-reward]').textContent=city.won?'✓ Кампания завершена':city.stage===0?'Награда: 120 монет + 40 дерева':city.stage===1?'Награда: 180 монет + 60 дерева':'Финал: 80 жителей · счастье 75%';
  $('[data-season-symbol]').textContent=['✿','☀','❧','❄'][city.season%4];$('[data-season-name]').textContent=`${SEASONS[city.season%4]}, год ${Math.floor(city.season/4)+1}`;$('[data-season-caption]').textContent=`Сезон ${city.season+1} · время в ваших руках`;
  $('[data-forecast]').innerHTML=`<span>ИТОГ ЭТОГО СЕЗОНА</span><b class="${s.balance<0?'negative':''}">${s.balance>=0?'+':''}${s.balance} монет</b><small>${s.food-s.consumption>=0?'+':''}${s.food-s.consumption} еды &nbsp; · &nbsp; +${s.wood} дерева</small>`;
  $('[data-blueprints]').innerHTML=BUILD_ORDER.map((kind,i)=>{const b=BLUEPRINTS[kind],locked=b.stage>city.stage;return`<button class="blueprint ${tool===kind?'selected':''} ${locked?'locked':''} ${city.coins<b.cost||city.wood<b.wood?'unaffordable':''}" data-tool="${kind}" title="${b.name}. ${locked?'Откроется после главы '+b.stage:b.description}" aria-label="${b.name}" aria-pressed="${tool===kind}"><span class="key">${i===9?'0':i+1}</span><span class="bp-icon" style="color:${b.color}">${locked?'⌑':b.icon}</span><strong>${b.short}</strong><small>${locked?'Глава '+(b.stage+1):`${b.cost} ◉ <i>·</i> ${b.wood} ♧`}</small></button>`;}).join('');
  root.querySelectorAll<HTMLElement>('.utility [data-tool]').forEach(b=>b.classList.toggle('selected',b.dataset.tool===tool));$<HTMLButtonElement>('[data-action="undo"]').disabled=!city.undoState;
  $<HTMLButtonElement>('[data-action="next"]').disabled=city.event!==null;
  inspector();renderer.tool=tool;renderer.selected=selected;
 }
 const trade=()=>{showDialog('trade',`<span class="eyebrow">ТОРГОВЛЯ С МАТЕРИКОМ</span><h2 id="bay-dialog-title">Корабль уже у причала.</h2><p>В казне ${city.coins} монет. Заказы доставляются сразу.</p><div class="event-choices"><button data-buy="wood" ${city.coins<40?'disabled':''}><strong>20 дерева</strong><span>40 монет</span>${icons.wood}</button><button data-buy="food" ${city.coins<35?'disabled':''}><strong>30 еды</strong><span>35 монет</span>${icons.food}</button></div>${city.coins<40?`<button class="secondary" data-action="aid" ${city.season-city.aidSeason<4?'disabled':''}>Помощь ратуше: 100 монет</button><p class="dialog-note">При казне менее 40 монет, раз в 4 сезона. С помощью можно получить до 2 звёзд.</p>`:''}<button class="secondary" data-action="close">Вернуться в город</button>`);};
 const handleAction=(action:string)=>{
  if(action==='sound'){sound.unlock();sound.muted=!sound.muted;soundUI();try{if(options.savePolicy==='persistent')localStorage.setItem(soundKey,sound.muted?'off':'on');}catch{}return;}
  if(action==='tool-help'){if(tool==='inspect'||tool==='bulldoze')return help();const b=BLUEPRINTS[tool];return showDialog('building',`<span class="eyebrow">СПРАВОЧНИК ПОСТРОЕК</span><h2 id="bay-dialog-title">${b.name}</h2><p>${b.description}</p><p>Строительство: ${b.cost} монет и ${b.wood} дерева.<br>Содержание: ${b.upkeep} монет за сезон.</p><button class="primary" data-action="close">Выбрать место ${icons.arrow}</button>`);}if(action==='start')return begin();if(action==='new')return newDialog();if(action==='confirm-new')return begin(true);if(action==='close')return closeDialog();if(action==='help')return help();if(action==='menu'){save();return menu();}if(action==='trade')return trade();
  if(action==='journal')return showDialog('journal',`<span class="eyebrow">ГОРОДСКАЯ ХРОНИКА</span><h2 id="bay-dialog-title">История вашей бухты</h2><ol class="journal">${city.log.map(x=>`<li>${escape(x)}</li>`).join('')}</ol><button class="primary" data-action="close">Вернуться</button>`);
  if(action==='zoom-in')renderer.zoomBy(1.2);if(action==='zoom-out')renderer.zoomBy(1/1.2);if(action==='center')renderer.reset();if(action==='grid'){renderer.grid=!renderer.grid;$('[data-action="grid"]').classList.toggle('selected',renderer.grid);}
  if(action==='undo'){if(city.undo()){save();update();toast('Последнее строительство отменено.');}return;}
  if(action==='aid'){if(city.aid()){save();update();trade();}return;}
  if(action==='next'){const won=city.won,stage=city.stage;const text=city.advance();sound.season();save();update();toast(text);if(!won&&city.won)showWin();else if(city.event!==null)showEvent();else if(stage!==city.stage)showDialog('milestone',`<span class="victory-mark">✦</span><span class="eyebrow">НОВАЯ ГЛАВА</span><h2 id="bay-dialog-title">${city.stage===1?'Больше, чем посёлок.':'Теперь это город.'}</h2><p>${text}</p><button class="primary" data-action="close">Продолжить строительство ${icons.arrow}</button>`);}
 };
 root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;if(b.dataset.tool){const k=b.dataset.tool as Tool;if(k!=='inspect'&&k!=='bulldoze'&&BLUEPRINTS[k].stage>city.stage){toast(`Откроется после выполнения главы ${BLUEPRINTS[k].stage}.`);return;}setTool(k);return;}if(b.dataset.choice!==undefined){if(city.choose(Number(b.dataset.choice))){closeDialog();save();update();}}else if(b.dataset.buy){if(city.trade(b.dataset.buy as 'food'|'wood')){sound.build();save();update();trade();}}else if(b.dataset.action)handleAction(b.dataset.action);},{signal:abort.signal});
 let pointer:{id:number;x:number;y:number;lastX:number;lastY:number;drag:boolean}|null=null;
 canvas.addEventListener('pointerdown',e=>{if(!active||!modal.hidden||e.button!==0)return;canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:false};},{signal:abort.signal});
 canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();if(pointer&&e.pointerId===pointer.id){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>6)pointer.drag=true;if(pointer.drag){renderer.panX=Math.max(-renderer.width,Math.min(renderer.width,renderer.panX+e.clientX-pointer.lastX));renderer.panY=Math.max(-renderer.height,Math.min(renderer.height,renderer.panY+e.clientY-pointer.lastY));renderer.layout();}pointer.lastX=e.clientX;pointer.lastY=e.clientY;}hover=renderer.pick(e.clientX-r.left,e.clientY-r.top);renderer.hover=hover;if(active){const reason=city.reason(tool,hover);$('[data-status]').textContent=tool==='inspect'?'Нажмите на здание · Потяните карту для перемещения':reason||`${tool==='bulldoze'?'Снести':BLUEPRINTS[tool].name} · нажмите для ${tool==='bulldoze'?'сноса':'строительства'}`;}},{signal:abort.signal});
 canvas.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dragged=pointer.drag;pointer=null;if(dragged||!active||!modal.hidden)return;const r=canvas.getBoundingClientRect(),i=renderer.pick(e.clientX-r.left,e.clientY-r.top);if(i<0)return;selected=i;if(tool==='inspect')update();else{const error=city.build(tool,i);if(error){toast(error);sound.tone(150,.1,.025);}else{sound.build();save();update();}}},{signal:abort.signal});
 canvas.addEventListener('pointercancel',()=>{pointer=null;},{signal:abort.signal});canvas.addEventListener('pointerleave',()=>{if(!pointer){renderer.hover=-1;hover=-1;}},{signal:abort.signal});
 canvas.addEventListener('wheel',e=>{if(!active||!modal.hidden)return;e.preventDefault();renderer.zoomBy(e.deltaY<0?1.07:1/1.07);},{passive:false,signal:abort.signal});
 root.addEventListener('keydown',e=>{if(e.code==='Tab'&&!modal.hidden){const buttons=[...card.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(e.code==='KeyM'){handleAction('sound');return;}if(!modal.hidden){if(e.code==='Escape'&&dialog!=='event')closeDialog();return;}if(!active)return;if(e.code==='Space'&&(e.target as HTMLElement).tagName!=='BUTTON'){e.preventDefault();if(!e.repeat)handleAction('next');}if(e.code==='Escape')setTool('inspect');if(e.code==='KeyZ')handleAction('undo');if(e.code==='KeyG')handleAction('grid');if(e.code==='Equal'||e.code==='NumpadAdd')renderer.zoomBy(1.15);if(e.code==='Minus'||e.code==='NumpadSubtract')renderer.zoomBy(1/1.15);if(e.code.startsWith('Digit')){const n=Number(e.code.slice(-1)),k=BUILD_ORDER[n===0?9:n-1];if(k&&BLUEPRINTS[k].stage<=city.stage)setTool(k);}if(e.code.startsWith('Arrow')){e.preventDefault();renderer.panX+=e.code==='ArrowLeft'?25:e.code==='ArrowRight'?-25:0;renderer.panY+=e.code==='ArrowUp'?25:e.code==='ArrowDown'?-25:0;renderer.layout();}},{signal:abort.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){save();sound.suspend();}else if(active&&!paused)sound.unlock();},{signal:abort.signal});window.addEventListener('pagehide',save,{signal:abort.signal});
 const resize=new ResizeObserver(()=>renderer.resize());resize.observe(root);
 function draw(now:number){if(disposed)return;if(!paused&&now-lastDraw>30){renderer.draw(now/1000);lastDraw=now;}frame=requestAnimationFrame(draw);}frame=requestAnimationFrame(draw);update();
 return{pause(value){paused=value;if(value){save();sound.suspend();}else if(active)sound.unlock();},dispose(){disposed=true;save();cancelAnimationFrame(frame);if(toastTimer)clearTimeout(toastTimer);resize.disconnect();abort.abort();sound.dispose();root.innerHTML='';root.classList.remove('bay-root','playing');document.title=oldTitle;},diagnostics(){return{...city.save(),stats:{...city.stats(),connected:[...city.stats().connected]},tool};}};
}
const module:EngineModule={id:'tidehaven',sdk:1,components:[{id:'tidehaven.tile',name:'Клетка города',fields:[{name:'terrain',label:'Ландшафт',type:'select',default:'grass',options:['water','grass','meadow','forest'].map(value=>({value,label:{water:'Вода',grass:'Земля',meadow:'Луг',forest:'Лес'}[value]!}))},{name:'building',label:'Начальная постройка',type:'select',default:'',options:[{value:'',label:'Нет'},...Object.entries(BLUEPRINTS).map(([value,b])=>({value,label:b.name}))]}]}],validateScene(scene){new City(scene);},createSession:startGame};
export default module;
